### ISSUE TITLE
StealJS warnings despite paths specification

### ISSUE THREAD

**Issue by georgesunil81** [stealjs/steal#1000]
I have some WARNINGS that show up in the browser console and during the steal-build process about some external libraries I am using in my app. These warning come up as -

npm-convert.js:374 WARN: Could not find braintreeClient in node_modules. Ignoring.
npm-convert.js:374 WARN: Could not find braintreeHostedFields in node_modules. Ignoring.

Although, I have explicitly specified the paths to these libraries in my package.json like -
 {
  "name": "myapp",  
  "dependencies": {        
    "braintree-web": "^3.2.0",
    "can": "^2.3.24",    
    "jquery": "^2.2.4",    
    "steal": "^0.16.35",
    "steal-cache-bust": "^0.2.1",
    "steal-tools": "^0.16.6",
  },
  "devDependencies": {
  },
  "system": {
    "npmAlgorithm": "flat",
    "configDependencies": [
      "cache-bust"
    ],
    "directories": {
      "lib": "app"
    },
    "meta": {
      "braintreeClient": {
        "format": "global",
        "deps": [
          "jquery"
        ]
      },
      "braintreeHostedFields": {
        "format": "global",
        "deps": [
          "jquery"
        ]
      }
    },
    "paths": {
      "braintreeClient": "node_modules/braintree-web/client.js",
      "braintreeHostedFields": "node_modules/braintree-web/hosted-fields.js"
    }
  }
}

Here is how I use it in my AMD-based module -
 define([
  'jquery',
  'can',
  'braintreeClient',
  'braintreeHostedFields',
], function($, can) {
  ...
}

I believe these warnings should not be shown since I am explicitly providing paths to these libraries within the paths property in package.json.

**Comment by matthewp** [comment]
Those warnings were removed in 1.0.

**Comment by georgesunil81** [comment]
Thanks @matthewp for the resolution. I will upgrade to version 1.0.
