### ISSUE TITLE
Problems with relative paths in Angular 2 after upgrading to from stealjs version 0.16.42 to 1.0.10

### ISSUE THREAD

**Issue by repolevedavaj** [stealjs/steal#1001]
I am developing an Angular 2 application with Steal as the module loader. In all Angular 2 components I use the "Component-Relative URLs" feature (https://angular.io/docs/ts/latest/cookbook/component-relative-paths.html) of Angular 2. As described in the docs, this feature only works with CommonJS modules, therefore I configured the Typescript compiler accordingly:

```
{
  "compilerOptions": {
    "module": "commonjs",
   ...
  }
 ...
}
```

Now after upgrading the steal version, angular tries to load all templates from the root folder - so the "Component-Relative URLs" feature no longer works.

Example:
Version 0.16.42: angular loaded the component template html file successfully from `app/example/example.html`
Version 1.0.10: angular tries to load the template from `/example.html` and failes

Example Component:
```
@Component({
    moduleId: module.id,
    selector: "example",
    templateUrl: "example.html"
})
export class ExampleComponent {}
```

Output:

```
"use strict";
var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
    var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
    if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
    else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
    return c > 3 && r && Object.defineProperty(target, key, r), r;
};
var core_1 = require("@angular/core");
var ExampleComponent = (function () {
    function ExampleComponent() {
    }
    return ExampleComponent;
}());
ExampleComponent = __decorate([
    core_1.Component({
        moduleId: module.id,
        selector: "example",
        templateUrl: "example.html"
    })
], ExampleComponent);
exports.ExampleComponent = ExampleComponent;
//# sourceMappingURL=ExampleComponent.js.map
```

After I switched back to the old version, the loading of the html templates was working again. Did I missed something while upgrading the steal version?

I created an [example application](https://github.com/stealjs/steal/files/706948/Example.zip) which uses steal version 0.16.42. You can start the example after `npm install` with `npm start`. If you change the version to 1.0.10 the loading of the html templates no longer works.

**Comment by pYr0x** [comment]
Can you pls post the commmjs output of the component.
How does the require statement look?

**Comment by repolevedavaj** [comment]
I updated my question with the output. A complete example will follow in the next days.

**Comment by pYr0x** [comment]
in your output is not require statement for the HTML file.... ?

**Comment by repolevedavaj** [comment]
I added an example application (see in my first comment). The code which loads the template belongs to the Angular 2 code - see `compiler.umd.js`. 
While debugging, I realised that the value of the `module.id` variable is different after upgrading the stealjs version. Thats probably the cause of my problem. You can see the used id on line `17875` in `compiler.umd.js`.

**Comment by pYr0x** [comment]
in your first comment you say, that the HTML file is not loaded. but in your last comment you say that the module-name is different. but the `example.component.js` loads successfully, right?

**Comment by repolevedavaj** [comment]
Yes, maybe I explained it a little bit unprecise. The only thing that breaks if I upgrade the steal version is the "Component-Relative URLs" feature of Angular 2. Since this feature only works, if you put the module id into the decorator (moduleId: module.id in the decorator), the feature broke because of the changed id.

**Comment by matthewp** [comment]
Is there a bug in Steal you are reporting? We can't really help with Angular issues.

**Comment by matthewp** [comment]
Will need a reduced down example that doesn't include a framework. Happy to help if you can provide this.
