### ISSUE TITLE
Package.json parsing : jam section whitout main failure

### ISSUE THREAD

**Issue by jcarbou** [stealjs/steal#1006]
Hi all,

I add jquery-mousewheel in my package.json. This module declare a "jam" section without "main' attribute :
```
...
"jam": {
    "dependencies": {
        "jquery": ">=1.2.2"
    }
  },
...
"main": "./jquery.mousewheel.js",
..
```
The npm-utils finds `main`  of this module with the `main` method :
```
main: function(pkg) {
			var main;
			var steal = utils.pkg.config(pkg);
			if(steal && steal.main) {
				main = steal.main;
			} else if(typeof pkg.browser === "string") {
				if(utils.path.endsWithSlash(pkg.browser)) {
					main = pkg.browser + "index";
				} else {
					main = pkg.browser;
				}
			}  else if(typeof pkg.jam === "object") {
				main = pkg.jam.main;
			}  else if(pkg.main) {
				main = pkg.main;
			} else {
				main = "index";
			}
...
```
This function execute `` main = pkg.jam.main; ``and return null instead of ./jquery.mousewheel.js. 

Simple fix :

`` else if(typeof pkg.jam === "object" && pkg.jam.main)  ``

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-npm #217](https://github.com/stealjs/steal-npm/issues/217) via [**ZenHub**](https://www.zenhub.com/)

**Comment by matthewp** [comment]
Thanks, moved it to the repo where it belongs.
