### ISSUE TITLE
semantic-ui-react not loading.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#1021]
When I `npm install semantic-ui-react --save` and then try to use the module like this:

```js
import {Container} from 'semantic-ui-react';
```

I get a whole bunch of errors.  I thought that it's maybe from Steal trying to load in a Modlet format, but the page using the module stops loading.  There are a lot of modules in this package, so creating a custom file map would be really cumbersome.  Is there anything I can do to force Steal to treat this module as a node module instead of a browser module as far as imports go?

![screen shot 2017-01-25 at 9 03 17 am](https://cloud.githubusercontent.com/assets/128857/22298586/45c3d6f8-e2de-11e6-837d-604c286c4c91.jpg)

**Comment by marshallswain** [comment]
Here's the PR I opened on their repo trying to fix this: https://github.com/Semantic-Org/Semantic-UI-React/pull/1221

**Comment by levithomason** [comment]
It may help to know that those paths are directories with `.js` appended to them.  Each directory has an entry file with the same name as the folder, an `index.js` that exports the entry file, and an `index.d.ts` typings definition.  Here is an example, the Button directory:

```
Semantic-UI-React/dist/commonjs/elements/Button/Button.js   // the entry file
Semantic-UI-React/dist/commonjs/elements/Button/index.js    // exports the entry
Semantic-UI-React/dist/commonjs/elements/Button/index.d.ts  // typings
```

>There are additional files for subcomponents (i.e. `ButtonGroup.js`) but all subcomponents are imported and exposed in the entry file (i.e. `Button.Group`).

**Comment by matthewp** [comment]
Yeah, this is not code that is meant to run in the browser, you should use the UMD build. Unfortunately it's common of libraries these days to be written exclusively for bundlers.  We work around it as best we can, but it's better not to fight it.
