### ISSUE TITLE
some wrong with tests

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#1027]
@matthewp it looks something is going wrong with the tests

1. we dont run `testee` in travis anymore. in travis only the node-tests are triggered. https://github.com/stealjs/steal/blob/master/.travis.yml#L10
the `npm run test` was removed. 
@m-mujica and i added your extension-tests to the testee grunt task. so your tests will be actually not run.
2. sauce-labs only runs the main test of steal. https://github.com/stealjs/steal/blob/master/test/test-sauce-labs.js#L114

solutions: 
1. add testee tests to travis again
2. add the extension-tests to the main steal test like the `json` extension.

what do you prefer @matthewp ?

**Comment by matthewp** [comment]
We should do (2). We don't need to run testee in travis b/c saucelabs already runs it in every browser (including Firefox, which is what testee previously did).

Yes, json was added to the main test file. That's how the others should do it as well.

**Comment by pYr0x** [comment]
ok i will do a refactor of the tests if you merged the cachebust extension in.
