### ISSUE TITLE
Loading scripts from a CDN

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal#1028]
When trying to import `can-define` from https://unpkg.com with **Steal**, I feel like this _**should**_ work:
https://plnkr.co/edit/9wdvenhebhRhAqCiBPFu

The relevant code part is

```js

steal.config({
  paths: {
    'can-define/*': 'https://unpkg.com/can-define@1.0.15/*',
    'can-define': 'https://unpkg.com/can-define@1.0.15',
    'can-util/*': 'https://unpkg.com/can-util@3.2.2/*',
    'can-util': 'https://unpkg.com/can-util@3.2.2',
    'can-event/*': 'https://unpkg.com/can-event@3.0.2/*',
    'can-event': 'https://unpkg.com/can-event@3.0.2',
    'can-cid/*': 'https://unpkg.com/can-cid@1.0.1/*',
    'can-cid': 'https://unpkg.com/can-cid@1.0.1',
    'can-compute/*': 'https://unpkg.com/can-compute@3.0.5/*',
    'can-compute': 'https://unpkg.com/can-compute@3.0.5',
    'can-observation/*': 'https://unpkg.com/can-observation@3.0.7/*',
    'can-observation': 'https://unpkg.com/can-observation@3.0.7',
    'can-types/*': 'https://unpkg.com/can-types@1.0.2/*',
    'can-types': 'https://unpkg.com/can-types@1.0.2',
    'can-namespace/*': 'https://unpkg.com/can-namespace@1.0.0/*',
    'can-namespace': 'https://unpkg.com/can-namespace@1.0.0',
    'can-construct/*': 'https://unpkg.com/can-construct@3.1.0/*',
    'can-construct': 'https://unpkg.com/can-construct@3.1.0',
  },
  map: {
    
  }
});
```

But it errors at [`can-compute`](https://unpkg.com/can-compute@3.0.5) where it tries to import a relative file `./proto-compute`...
```js
var Compute = require('./proto-compute');
```

![image](https://cloud.githubusercontent.com/assets/76821/22400276/1a9ae918-e576-11e6-9e91-13a5a8b95f71.png)

...But it tries to import `./proto-compute` from the root, not relative to where the script is.

Is this a bug?
Have I configured incorrectly?
Is this something we just have never done before?

**Comment by matthewp** [comment]
Nope, just the weird way AMD normalization works. A flat module name of `foo` that has a relative import of `./bar` will normalize that identifier to `bar` and not `foo/bar` like you might expect. The fix is to create a map for can-compute like `map: { "can-compute": "can-compute/can-compute" }` and then change your can-compute paths to `paths: { "can-compute/can-compute": "https://unpkg.com/can-compute@3.0.5" }`
