### ISSUE TITLE
Support customizing Babel / core JS transpiler

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1040]
Ideally, this could be done via `plugins` so if someone loads ES8 code, it can work within someone's ES7 app, but my guess is that to start, we can make it one configuration.

Along with this, it would be good to allow transpiling of CJS modules. 

## Things to consider

- How would steal-tools be configured with the same transpiler?
- What if different plugins wanted their own extensions?

**Comment by ccummings** [comment]
This would also enable ES6+ code coverage via a plugin like https://github.com/istanbuljs/babel-plugin-istanbul which is a big pain point for me in a few projects.

**Comment by matthewp** [comment]
That plugin probably wouldn't work in the browser, it seems to depend on a lot of filesystem access.

This is the one big downside to supporting Babel plugins, none of them are written to be used in the browser and user expectations will be that any Babel plugin they use will work just like it does when using Babel directly.  The ones that only do AST transformations should work, but others like that probably won't.

**Comment by matthewp** [comment]
Just realized that plugin maybe is only used during a build? If that's the case you can probably make it work.

**Comment by matthewp** [comment]
For now let's go with having just a single global configuration for Babel plugins. Only the end-developer should be able to configure this, not dependencies. Tackling the latter is a nice-to-have for the future.

Babel options are specified by the [babelOptions](http://stealjs.com/docs/config.babelOptions.html) configuration. What we want is the user to be able to specify their own plugins/presets like so:

```json
"steal": {
  "babelOptions": {
    "presets": [
      "react", "stage-0"
    ],
    "plugins": [
      "some-weird-babel-plugin"
    ]
  }
}
```

The plugins are used [here](https://github.com/stealjs/steal/blob/9b8cff8c87304061cd55bf86375c09ebbf2dd016/src/loader/lib/transpiler.js#L100) in Steal.

> **Important**: We need to always use the "es2015-no-commonjs" preset and "transform-es2015-modules-systemjs" plugin in the browser.  Otherwise we should only use the presets/plugins the user provides (if they provide any).

The Babel that is packaged with Steal comes from [babel-standalone](https://github.com/babel/babel-standalone). You can look at it to see a list of presets/plugins that it comes with.

To make 3rd party plugins/presets work, we need to `loader.import` them and provide that in the options passed into babel.transform. It will look something like this (pseudocode):

```js
loader.import("some-weird-babel-plugin").then(function(plugin){
  var options = {
    presets: [
      // These are bundled presets, is why we can use strings
      "es2015-no-commonjs", "react", "stage-0"
    ],
    plugins: [
      // This is a bundled plugin
      "transform-es2015-modules-systemjs",

      // Include the object (or function?) itself here
      plugin
    ]
  };

  var source = babel.transform(load.source, options).code;
});
```

To test this you should be able to create a small example babel plugin that does something trivial like replace the `"foo"` string with the `"bar"` string.

**Comment by matthewp** [comment]
The ability to transpile non-import/export code should be done in https://github.com/stealjs/steal/issues/768.

**Comment by m-mujica** [comment]
Example https://github.com/m-mujica/steal-babel-plugin-example
