### ISSUE TITLE
Move es6-module-loader into core.

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1056]
https://github.com/stealjs/steal/issues/746#issuecomment-278837024

**Comment by matthewp** [comment]
Can you run the steal-tools tests against master now, just as a sanity-check that this didn't break anything? 🙈

**Comment by m-mujica** [comment]
@matthewp done! https://github.com/stealjs/steal-tools/pull/614 I got some troubles with a test but it was due to the `when.js` version that I locked down in the PR about steal-npm

**Comment by matthewp** [comment]
Great, don't forget to update the readme with a depreciation message.

**Comment by m-mujica** [comment]
yup, done!
