### ISSUE TITLE
Proposal: commit message format and automagic changelog 

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1059]
If we adopt a commit message format like `eslint`:

```
Tag: Short description (fixes #1234)

Longer description here if necessary
```

The first line of the commit message (the summary) must have a specific format. This format is checked by our build tools.

The Tag is one of the following:

- `Fix` - for a bug fix.
- `Update` - for a backwards-compatible enhancement or a change to a rule that increases the number of reported problems.
- `New` - implemented a new feature.
- `Breaking` - for a backwards-incompatible enhancement or feature.
- `Docs` - changes to documentation only.
- `Build` - changes to build process only.
- `Upgrade` - for a dependency upgrade.
- `Chore` - for refactoring, adding tests, etc. (anything that isn’t user-facing).

We could use something like https://github.com/conventional-changelog/conventional-changelog to automatically generate a [nice looking changelog](https://github.com/eslint/eslint/blob/master/CHANGELOG.md)

We could [enforce the commit format](https://github.com/eslint/eslint/blob/6445d2a55af7e3b797c5f7a187227cf267e0017c/package.json#L23) for the build.

I know it's a barrier to contributions but I like the idea of keeping automatic/up-to-date changelogs. Thoughts? @matthewp @pYr0x

**Comment by m-mujica** [comment]
There are other templates available, like [jquery's](https://contribute.jquery.org/commits-and-pull-requests/#preparing-to-commit), [angular's](https://github.com/angular/angular/blob/master/CONTRIBUTING.md#commit) ewww, or [jshint](https://github.com/jshint/jshint/blob/master/CONTRIBUTING.md#commit-message-guidelines)

I liked the one used by eslint, seems simple enough.

**Comment by m-mujica** [comment]
There is also http://commitizen.github.io/cz-cli/ as an UI to create the commit messages

**Comment by matthewp** [comment]
I think this does it without needing to follow any conventions: https://github.com/zeit/release

**Comment by m-mujica** [comment]
@matthewp it'll ask you the type of each commit 

https://github.com/zeit/release/wiki/Change-Types

This one is simpler though, it only has three categories.

**Comment by chasenlehara** [comment]
Related: https://github.com/canjs/canjs/issues/2763

I disagree with this being a barrier to contributions. I think it’s really helpful to have a specific format documented in the contribution guide. Here are some examples of projects that specify how commit messages should be formatted:

- https://github.com/angular/angular/blob/master/CONTRIBUTING.md#-commit-message-guidelines
- https://github.com/formly-js/angular-formly/blob/master/CONTRIBUTING.md#pull-requests
- https://guides.emberjs.com/v2.11.0/contributing/adding-new-features/#toc_commits

If someone has the time to look at our options, this would be a great topic for [our next contributors meeting](http://forums.donejs.com/t/donejs-contributors-meeting-2017-02-17/552).

**Comment by matthewp** [comment]
We've started using GitHub Releases instead of a changelog.md file. I think Releases are better as they are more linkable and can contain a bigger description (you can write as many paragaphs as you want, include pictures, etc).

I don't think strong conventions would add much value there, and would definitely be a barrier to contributions. We have very few outside contributions to this project so I don't want to add barriers unless there's a strong advantage to it.

**Comment by matthewp** [comment]
@m-mujica let's use `release`, agree?

**Comment by m-mujica** [comment]
@matthewp sounds good to me. Is there anything we need to do?

The only step seems to be create the tag https://github.com/zeit/release/wiki/Example 

wondering if it adds the commit with the version number.

**Comment by matthewp** [comment]
Looks like we still have to create the tag ourselves. Think the only thing to do here is to create an npm script like `"gh-release": "release"` that we can run.
