### ISSUE TITLE
Turn off console.log/warn/error 

### ISSUE THREAD

**Issue by santoshgiridhar** [stealjs/steal#1062]
Under GruntFile.js  have configured steal-build to remove/suppress the console.*  by adding option (quite and debug) But, after final build I still see the console.log/warn/error message in the console.
```
'steal-build': {
      main: {
        options: {
          system: {
            config: __dirname + '/package.json!npm',
            main: 'index'
          },
          buildOptions: {
            bundleSteal: true,
            quiet: true,
            debug:false
          }
        }
      }
    },

```
Please suggest the right way of doing it?
Under node_modules/steal/Gruntfile.js, you guys have already configured the uglify task to turn off console warning.
https://github.com/gruntjs/grunt-contrib-uglify/blob/master/docs/uglify-examples.md#turn-off-console-warnings

But still its not working. 

Help needed.

**Comment by matthewp** [comment]
Which messages do you see?

**Comment by santoshgiridhar** [comment]
@m-mujica Usage scenario, when we deploy the application and run on chrome web browser and open developer console we can still see the console.log coded in application.
Any idea how to suppress these in the build process ?

**Comment by phillipskevin** [comment]
can you give some examples of the messages you're seeing?

**Comment by pYr0x** [comment]
http://stealjs.com/docs/steal-tools.BuildOptions.html
```

removeDevelopmentCode=true {Boolean}Optional

Remove any development code from the bundle specified using //!steal-remove-start, and //!steal-remove-end comments.
```

**Comment by matthewp** [comment]
The quiet option of steal-tools turns off logging that steal-tools. There's no way to disable console messages that may happen inside of a library or your own code.

As @pYr0x points out above, you can wrap your own development code using steal-remove-start/stop comments.

**Comment by m-mujica** [comment]
@santoshgiridhar you could also use [`steal.dev.log`](http://stealjs.com/docs/@dev.html) (instead of `console.log`); steal-tools removes them during the build.
