### ISSUE TITLE
steal produces bigger bundles then rollup

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1083]
https://github.com/rollup/rollup ES6 bundler has at present better results maybe watch into it and adapt the good stuff from it.

http://jspm.io/ <- is using rollup and looks similar to steal even also based on systemjs

**Comment by matthewp** [comment]
We have this covered in a couple of RFC issues: 

* https://github.com/stealjs/rfcs/pull/5
* https://github.com/stealjs/rfcs/issues/8

Let's take the conversation over there.
