### ISSUE TITLE
Potentially unhandled rejection - (WARNING: non-Error used) 

### ISSUE THREAD

**Issue by santoshgiridhar** [stealjs/steal#1090]
Am trying to de-obfuscate the response returned from XHR.responseText placed inside promise.all method.
And I am ending up with above error and promise.all is getting rejection caught and UI is not loading up even after the xhr.responseText is as expected(after decoding).

How do I go about fixing this issue? 

![unhandledexception_1](https://cloud.githubusercontent.com/assets/40515/23661927/0bf99780-0374-11e7-9656-72d62dc5957f.png)

```
`$(document).ajaxComplete(function(ev, xhr, options) {
...
var response = null,parsedResponse;
  if (xhr.status === 200) {
    Object.defineProperty(xhr, 'responseText', {writable: true});
    var rawResponse = xhr.responseText || xhr.responseJSON;
    console.log('rawResponse -->', rawResponse);
    // var responseObj = rawResponse;
    var responseObj = (rawResponse)?b64DecodeUnicode(rawResponse):rawResponse;
    xhr.responseText = responseObj;

    console.log('b64-rawResponse -->', xhr.responseText);
    parsedResponse = typeof responseObj === 'string' && JSON.parse(responseObj) || responseObj;
    response = parsedResponse;
  }

function b64DecodeUnicode(str) {
  // return decodeURIComponent( escape( atob( str ) ) );
  return decodeURIComponent(Array.prototype.map.call(atob(str), function(c) {
          return '%' + ('00' + c.charCodeAt(0).toString(16)).slice(-2);
      }).join(''));
}

Promise.all([
    ...//list of API calls
    ]).then(function(data){ 
    .. //loadUI..}).catch(function(ex) {
        console.error('Exception', ex);
    });
`
```
__How often can you reproduce it?__ 

- [x ] Always

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 0.15.7
| Steal-tools version    | 0.15.5
| node -v                       | v4.2.2
| npm -v                        | 2.14.7
| Browser                      | Version 56.0.2924.87 (64-bit) Chrome
| Operating system      | Sierra 10.12.3

**Comment by matthewp** [comment]
How is this related to Steal?

**Comment by matthewp** [comment]
Going to close, let me know if this is related to Steal. I think this is a problem you are having with Promises, and you are happening to use the Promise polyfill that comes with Steal. I think you would still experience your problem using native Promises. Let me know if you can clarify. 😁
