### ISSUE TITLE
1.4.0

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1091]
Steal 1.4.0 will be centered around an improved ability to run Babel plugins and possibly decorators.

**Comment by matthewp** [comment]
I'm leaving off the ability to transpile non-import/export code for now as the API isn't ready. https://github.com/stealjs/steal/issues/768#issuecomment-285061490 is meant to start the discussion about what the API could be for that.

**Comment by matthewp** [comment]
Not necessarily for this milestone, but it might be nice if there was a way to tell Steal to load the `.babelrc` and use that for configuration (as opposed to using babelOptions).

**Comment by BigAB** [comment]
That would be a nice to have. Of course you could probably only look in the root directory for it though, except for the build where I suppose you could do the thing where it looks up the directories until it finds a `.babelrc` or a package.json with a `babel` option

**Comment by mjstahl** [comment]
I 100% in favor of this. I also think that both `babelOptions` and `.babelrc` should be able to exist in the same directory. 

I am not sure which one should take precedence, but we should inform that the user that both exist in the directory, AND which one steal is going to be using. 

This will compensate for the idiocy of users like myself who will forget what they configured.

**Comment by m-mujica** [comment]
- [x] Release steal@1.40
- [ ] Update StealJS website
- [ ] Update https://github.com/stealjs/steal-tools/pull/642
- [ ] Release steal-tools@1.3.0
