### ISSUE TITLE
Make Steal 0.16 work with "steal" config

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#1099]
It would be nice if Steal 0.16 would support using `steal` or `system` in the package.json so that libraries can update their package.json to use `steal`, but still be compatible with apps using Steal 0.16.

**Comment by matthewp** [comment]
You can always use both.

**Comment by phillipskevin** [comment]
You mean like this?
```
"steal": {
  "directories": {
    "lib": "lib"
  }
},
"system": {
  "directories": {
    "lib": "lib"
  }
}
```

**Comment by matthewp** [comment]
Yep, 2.0 will likely drop system so might be a good idea if a lib needs to support 0.16 indefinitely.

**Comment by matthewp** [comment]
I don't think this is needed anymore.
