### ISSUE TITLE
steal.import with relative path

### ISSUE THREAD

**Issue by reinaldoarrosi** [stealjs/steal#1101]
I have a simple project created based on https://stealjs.com/docs/StealJS.quick-start.html.
Within this project I have only 2 files (index.js and test.js):

```javascript
// index.js
import Test from './test.js';
alert(Test.text);

steal.import('./test.js').then(function(test) {
    alert(test.default.text);
});
```

```javascript
// test.js
export default { text: 'test' }; 
```

The first "alert" in index.js works fine. The second one (that runs when the promise returns) is never called.
The call to steal.import throws "Cannot resolve a relative module identifier with no parent module".

Is this the expected behavior and, if so, how can I import a module relative to another when using steal.import?

**Comment by matthewp** [comment]
You can do that like this:

```js
var someImport = require("some-import");

steal.loader.import("./test", {
  name: module.id
});
```

This only works with CommonJS and AMD though.

**Comment by reinaldoarrosi** [comment]
I've ended up using the package name instead of ./
For example, if the package.json of my application has "name: myapp" the steal.import call must be like this (notice the prefix "myapp" on steal.import):

```javascript
// index.js
import Test from './test.js';
alert(Test.text);

steal.import('myapp/test.js').then(function(test) {
    alert(test.default.text);
});
// test.js
export default { text: 'test' }; 
```

It also seems to work using "~":
```javascript
steal.import('~/test.js').then(function(test) {
    alert(test.default.text);
});
```

**Comment by matthewp** [comment]
It doesn't have to be like that, but yes that's a good way to do it. Any non-relative module identifier will work. You can still use relative, but must provide the current module name like in https://github.com/stealjs/steal/issues/1101#issuecomment-286528977
