### ISSUE TITLE
Support environment dependant babel plugins

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1102]
https://github.com/stealjs/steal/pull/1100 adds the ability to load babel plugins not included in `babel-standalone`. 

Some babel plugins are meant to be run in certain environments, e.g https://github.com/istanbuljs/babel-plugin-istanbul uses `fs` and should not be loaded in the browser.

Babel supports an `env` option https://babeljs.io/docs/usage/babelrc/#env-option

- [x] Collect plugins set in the `env` object
- ~~[ ] Make steal set the BABEL_ENV somehow ?~~
- [x] Only import the plugins if `loder.isEnv(pluginEnv)` is true 

cc: @matthewp

**Comment by matthewp** [comment]
I think setting BABEL_ENV using `loader.getEnv()` wounds right to me.

**Comment by matthewp** [comment]
@m-mujica Thinking about it more, I don't think we should be setting `BABEL_ENV` ourselves. The user can do that the normal way.

We should only use BABEL_ENV to decide which env config to support.

**Comment by matthewp** [comment]
I would do something like:

```js
var babelEnv = process.env.BABEL_ENV || loader.getEnv();
```

And use that to add config.
