### ISSUE TITLE
Code coverage through Istanbul

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1118]
I've been looking at https://github.com/istanbuljs/babel-plugin-istanbul and if I understand correctly how it works, the workflow to setup coverage would look like this:

1) Build the app using babel-plugin-istanbul which adds instrumentation to the ES6 code
2) Run the tests using **the built version of the code** and integrate with some test runner to generate the report 

Ref: that's actually how it works with karma https://github.com/istanbuljs/babel-plugin-istanbul#karma

But that is not the workflow we tend to use in our apps, We

1) Use testee to load the test page
2) The test page loads Steal which transpiles the ES6 code on the fly using babel (or traceur)

Since `babel-plugin-istanbul` [runs on node](https://github.com/istanbuljs/babel-plugin-istanbul/blob/eeb33282d12128882ffde866e7f314e1b0d52125/src/index.js#L1-L2), we need a way to [instrument the code on the browser](http://gotwarlost.github.io/istanbul/public/apidocs/classes/Instrumenter.html#method_instrument) and let the test runner generate the report; maybe this should be a steal plugin @matthewp?

Also we'd have to add a flag so testee [skips the instrumentation part](https://github.com/bitovi/testee/blob/e8610368469c3e294a89d087b3213be816acc299/lib/host/coverage.js#L31) and only generates the report assuming code has already being instrumented.

I'm not familiar with Istanbul though and I might me missing something. Thoughts? cc: @ccummings @daffl

**Comment by m-mujica** [comment]
https://blog.engineyard.com/2015/measuring-clientside-javascript-test-coverage-with-istanbul

**Comment by matthewp** [comment]
I can sort of see why Testee has to work the way that it does. I can see why instrumentation needs to be done server side.

But that just makes me confused as to what the problem is, exactly. If you have to do a build before doing instrumentation, then why is a babel plugin necessary? You can just do a normal steal build and run your tests after transpilation. I think I'm probably missing something here, but I need some help to figure it out.  @ccummings

**Comment by m-mujica** [comment]
> If you have to do a build before doing instrumentation, then why is a babel plugin necessary?

Because the plugin adds instrumentation during the transpilation process. With a regular build, we'd still need to instrumented the built code before running tests.

Basically the plugin will add more code during the build, counters and stuff that allows istanbul later when tests are run to tell whether all lines/expressions/conditionals were covered. 

That's why the plugin is used on a specific environment, you don't want to use the instrumented build in production for example.

**Comment by m-mujica** [comment]
I guess it makes sense in a regular workflow with babel, you have to transpile your code anyways before using it. 

So, you just need to use the plugin while building the app before tests are run. Our "problem" is that we need to do it on the fly, on the browser.

**Comment by matthewp** [comment]
@m-mujica 

> Because the plugin adds instrumentation during the transpilation process. With a regular build, we'd still need to instrument the built code before running tests.

I might be reading it wrong, but [from the code](https://github.com/bitovi/testee/blob/e8610368469c3e294a89d087b3213be816acc299/lib/host/coverage.js#L31) it looks like Testee instruments in its http server middleware. As JavaScript is being requested by the browser it instruments that code and serves it up.

Given that, it makes sense that if Istanbul doesn't have an ESx parser it cannot instrument the code.

So if the only option is to serve transpiled code for tests, I don't see what value a babel plugin adds; Testee instruments on the fly.

I think we need to talk to @ccummings to figure out what is going on. I'm certain I'm missing something here.

**Comment by matthewp** [comment]
It makes sense to me that if you're not using Testee and using something else where you need to pre-instrument your code, then the babel plugin might be useful for that. You would instrument the code during the build.

**Comment by andrejewski** [comment]
Now that Testee has ES6 coverage support, is this issue needed? This is discussing instrumentation via Steal which now has babel plugin support so `babel-plugin-istanbul` could be used, but Testee already has a solution for it.

**Comment by matthewp** [comment]
Agreed, no longer needed.
