### ISSUE TITLE
Remove references to configMain in documentation

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1124]
I think we should remove most (all?) references to configMain in the documentation and instead better document `config`. config makes sense to people. configMain feels like an internal implementation detail that people shouldn't need to be aware of.

**Comment by matthewp** [comment]
I'm not totally sure what semver says about removing documentation. We are not removing the functionality or prevent people from using this (in the edge cases where they might).

**Comment by justinbmeyer** [comment]
My interpretation is that it's ok to remove documentation but not functionality (once that functionality has been documented)
