### ISSUE TITLE
Delete old gh-pages branches

### ISSUE THREAD

**Issue by leoj3n** [stealjs/steal#1126]
Having this https://github.com/stealjs/steal/branches/all?utf8=%E2%9C%93&query=gh-pages

And this https://github.com/stealjs/stealjs/branches/all?utf8=%E2%9C%93&query=gh-pages

Is confusing.

Can we please delete the no-longer-used `gh-pages` branch(es) on this (`stealjs/steal`) repo?

**Comment by matthewp** [comment]
i'd prefer not to lose the old history. Since that history is not in `master` like most code, not sure what to do with it.

**Comment by leoj3n** [comment]
I suppose we can rename it then?

**Comment by matthewp** [comment]
I moved it to [old-site](https://github.com/stealjs/steal/tree/old-site)
