### ISSUE TITLE
Saucelab matrix only shows firefox

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1133]
Caused by https://github.com/stealjs/steal/issues/1116 =(

**Comment by matthewp** [comment]
Currently showing everything:

<img width="692" alt="screen shot 2017-04-06 at 11 23 09 am" src="https://cloud.githubusercontent.com/assets/361671/24762149/79096bc6-1abb-11e7-849c-361313e3f4eb.png">

**Comment by matthewp** [comment]
We might want to check when merging stuff, to see if it changes.

**Comment by m-mujica** [comment]
It's currently showing everything as expected but steal-css is using the same Saucelabs accounts and unlike steal, steal-css runs all test pages in all the platforms..... We need to get steal-css its own Saucelabs account and then try to run some builds in steal.

**Comment by m-mujica** [comment]
the matrix is still looking good. I'm going to close this.
