### ISSUE TITLE
Error loading can-fixture when using dev bundles

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1135]
It seems Steal doesn't look for can-fixture in node_modules with dev bundles, trying to replicate this.

**Comment by m-mujica** [comment]
Created a simple app to replicate the issue

https://github.com/m-mujica/steal-dev-bundle-fixture

It works as expected, I sent the repo to the issue reporter to make sure the set up is the same.

**Comment by matthewp** [comment]
Let's close until we get more info then.
