### ISSUE TITLE
Update the contributing guide to add all steps needed to run tests

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1146]
The [contributing guide](http://stealjs.com/docs/guides.Contributing.html#developing-steal) should be updated to mention needing to run `npm run npm-copy` after the initial clone.  Not sure if anything else is missing.

**Comment by m-mujica** [comment]
@matthewp I think it'd be simple to make people run `npm test` since 1) it runs `npm-copy` and 2) it opens up all of the test pages and not only `test.html`. I'll make this change, let me know if you disagree
