### ISSUE TITLE
Cache the module name of imported modules

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1158]
When a module is imported, cache the module name for faster `normalize` look-up the next time it is imported.

this is an experimental feature. I plan on implementing it in a branch and releasing under an npm tag for testing.

**Comment by justinbmeyer** [comment]
This should cache the promise.

**Comment by matthewp** [comment]
Why?

**Comment by justinbmeyer** [comment]
That way if two modules are trying to normalize the same thing at about the same time (maybe common), only one full normalize will happen.

**Comment by matthewp** [comment]
This issue isn't trying to ensure that normalization only happens once. It's trying to ensure that once an application is fully loaded, subsequent imports are not slowed down by normalization. This is related to [this issue](https://github.com/donejs/done-component/issues/26).

**Comment by matthewp** [comment]
This is being done in done-ssr instead: https://github.com/donejs/done-ssr/pull/224
