### ISSUE TITLE
Steal + deck.gl unable to build

### ISSUE THREAD

**Issue by julia-allyce** [stealjs/steal#1166]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I am unable to load or build [deck.gl](https://github.com/uber/deck.gl) with steal. In the docs deck.gl is using browserify or webpack. I am unsure if this is a deckgl issue or a steal issue :/ but even when I try to build deckgl and import the built library I run into errors with steal :[

__Steps to reproduce:__
https://github.com/julia-allyce/deck.gl-stealjs
- `npm install && node build` produces the error:
```
OPENING: /.../deck.gl-stealjs/package.json!npm
Potentially unhandled rejection [11] Error: Error loading "assert" at file:/.../deck.gl-stealjs/assert.js
Error loading "assert" from "deck.gl-stealjs@1.0.0#index" at file:/.../deck.gl-stealjs/index.js
ENOENT: no such file or directory, open '/.../deck.gl-stealjs/assert.js'
    at Error (native)
```

I get the error regardless if I am using the built or unbuilt version of deckgl.
Without the deckgl import the project builds without errors.

__Expected results:__
deckgl should build.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.4.1
| Steal-tools version    | 1.3.0
| node -v                       | 7.8.0
| npm -v                        | 4.2.0
| Operating system      | Ubuntu 16.04

Thanks :)

**Comment by julia-allyce** [comment]
Just wondering if anyone has had a chance to look at this.

**Comment by matthewp** [comment]
I did, and found it to be a rabbit hole of issues. Let me take a look again to at least figure out what the essential problem is.

**Comment by julia-allyce** [comment]
Thank you!!

**Comment by matthewp** [comment]
I wasn't able to figure this one out when I did some investigating. Unfortunately I doubt I'll have time to investigate it more in the near-term future. If possible it would be good if this bug could be reduced down not to depend on external libraries.

**Comment by julia-allyce** [comment]
No worries. Sorry to have dumped a pretty open ended issue. I'll let you
know if I get a chance to spend more time on it.
