### ISSUE TITLE
Remove 'release' package

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1167]
It doesn't support tags with the `v` prefix: https://github.com/zeit/release/issues/84

**Comment by chasenlehara** [comment]
Do you think we could contribute to that project, or is there an alternative that could be better?

**Comment by matthewp** [comment]
I'm not aware of alternatives, I haven't looked into it though.

**Comment by morrme** [comment]
I am new to your codebase but I'm happy to help (with a little support).
