### ISSUE TITLE
Descriptive version mismatch error

### ISSUE THREAD

**Issue by andrejewski** [stealjs/steal#1176]
When linking `can-util` in `canjs` I get the error:
```
steal - error loading @config. Error: Error loading "package.json!npm" at file:/github-repos/canjs/package.json
Did not find ./node_modules/can-util/package.json
```
Although it is correctly linked. The reason it is not found is because the version of my local `can-util` does not match the `canjs` version.

We should provide a more descriptive error message when a dependency (or multiple) are found but none match the required version.

**Comment by matthewp** [comment]
Maybe something like:

```
Did not find ./node_modules/can-util/package.json
Unable to find a compatible version **^1.0.0** of **can-util**.
Deps: my-app -> can-event -> can-util
```

or something like that, so you can see the dep graph that is causing the package to be loaded.

**Comment by phillipskevin** [comment]
This error message is giving confusing messages in some cases:

```
Error: Error loading "can-react-component@0.1.6#test/test" at http://localhost/canjs/node_modules/can-react-component/test/test.js
Error loading "can-react-component@0.1.6#test/test" from "can@3.10.0-pre.3#test/test" at http://localhost/canjs/test/test.js
Did not find ./node_modules/can-stache/package.json
Unable to find a compatible version of can-stache@^3.0.24
Deps: can -> can-stache-converters -> can-view-href -> can-stache-bindings -> can-connect -> can-connect -> can-stache
```

The actual problem was that the main package had
```
  "dependencies": {
    "can-react-component": "0.1.6",
    "can-stache": "3.4.0-pre.2"
  }
```

and `can-react-component had
```
  "devDependencies": {
    "can-stache": "^3.0.24"
  }
```

Since the `-pre` version didn't match the version `can-react-component` wanted and `can-react-component` had `can-stache` as a `devDependency`, the correct version wasn't found, but the error message made this difficult to figure out. It would have been nice if the error message showed something like:

```
Did not find ./node_modules/can-stache/package.json
Unable to find a compatible version of can-stache@^3.0.24
Wanted:
can
├── can-react-component
│ └── can-stache@^3.0.24
Found: 
can
├── can-stache@3.4.0-pre.2
```
