### ISSUE TITLE
Failing with Zombie!

### ISSUE THREAD

**Issue by leoj3n** [stealjs/steal#1177]
Check out this repo → https://github.com/leoj3n/steal-zombie

The `temp` is generated by [this](https://github.com/bit-docs/bit-docs-tag-demo/blob/mocha-qunit-tests-working/test.js#L30-L66) using a [pre-release of `bit-docs-generate-html`](https://github.com/bit-docs/bit-docs-generate-html/tree/minor) with steal `1.X` stuff, and embeds an example of a `bit-docs-tag-demo` widget.

If you open `temp/index.html` in a regular browser like:

```console
$ http-server -a localhost -p 8081 -c-1
$ open http://localhost:8081/temp/index.html
```

Then there won't be any errors, but if you use the [`zombie-express.js`](https://github.com/leoj3n/steal-zombie/blob/master/zombie-express.js) example script:

```console
$ npm test
```

[Steal errors will be printed to the console](https://github.com/leoj3n/steal-zombie/blob/master/README.md), and the assertions looking for JavaScript manipulations of the DOM will fail!

**Comment by leoj3n** [comment]
When the [`indexOf` error](https://github.com/leoj3n/steal-zombie/blob/master/README.md) happens, it seems to be this line:

https://github.com/stealjs/steal/blame/master/src/startup.js#L41

**Comment by leoj3n** [comment]
See this repo for repro: https://github.com/leoj3n/generate-temp#zombie-issue

You might want to `.only` the second test once you `temp` generated if you plan on editing anything in `temp` so it doesn't get override.

**Comment by matthewp** [comment]
Looks like the newest version of Zombie doesn't support `attr.nodeName`, but does support `attr.name`. That's the only issue I see.
