### ISSUE TITLE
Cannot load a compiled template.stache.js

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#1180]
I want to use a built version of my published can-component module, but the compiled template `template.stache.js`  is not getting loaded in my app.

After I built my module (using steal-tools.export) to `cjs` my component's template gets saved as `dist/template.stache.js`. I can test this built module from its own project fine. However, when I publish it to NPM and try importing my built module from inside my app project, it fails with 404:

```
GET http://localhost:8080/node_modules/candlestick-volume-chart/dist/template.stache
404 (Not Found)
```

When debugging steal loading the module I can see that `moduleName.parse` removes `.js` extension from the module path and `parsedModuleName` value becomes:
```js
{
  "moduleName": "./template.stache.js",
  "modulePath": "./dist/template.stache",
  "packageName": "candlestick-volume-chart",
  "version": "0.1.1"
}
```

**Comment by matthewp** [comment]
If it were named `template.js` instead I bet it would work.  This problem is because there are "two" extensions in the filename, and once you remove the dot js steal thinks it's a stache file.  You can customize steal-tools export to name files however you wish.

Check out the `dest` option here: http://stealjs.com/docs/steal-tools.export.output.html

🤠

**Comment by ilyavf** [comment]
@matthewp I am not sure I understand how to do this.

Currently I have:
```js
stealTools.export({
  steal: {
    config: 'package.json!npm',
    main: 'candlestick-volume-chart/candlestick-volume-chart'
  },
  outputs: {
    "+cjs": {
      dest: __dirname + '/dist',
      minify: true
    }
  }
});
```

Can I specify the output only for certain files so that other files of my module will import it correctly?

If I create an separate output for `template.stache` and set its dest to be `template.js` this does not work.

Also, I was trying to use `dest` as function but it gets ignored, only a string works.

**Comment by matthewp** [comment]
File an issue in steal-tools.  A function for `dest` should work. A function where you filter to the name that you want is the way to fix your problem. It might not be supported by +cjs currently though.

**Comment by ilyavf** [comment]
>filter to the name that you want

Yeah, this is what I was thinking to do. OK, thanks, will file an issue about dest for cjs.
