### ISSUE TITLE
Docs: inaccurate source link to babel plugin list

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#1192]
https://stealjs.com/docs/StealJS.babel.html
```
Steal's bundled version of Babel comes with the presets and plugins 
provided by the babel-standalone project. You can see the full list 
here.
```
The link `here` should point to:
```
https://github.com/babel/babel-standalone/blob/master/src/index.js#L112
```

**Comment by chasenlehara** [comment]
It might be better to link to that line in a specific commit so it doesn’t change over time: https://github.com/babel/babel-standalone/blob/38475316d32c8957e9887728597915f6bf61bd10/src/index.js#L113-L185

**Comment by m-mujica** [comment]
Closed by https://github.com/stealjs/steal/pull/1193
