### ISSUE TITLE
Why babel option `transform-object-assign` does not work?

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#1194]
I believe that `transform-object-assign` is included into `babel-standalone`, and I was trying to use this plugin to transform `Object.assign` calls into ES5 (as it is described in babel docs https://babeljs.io/docs/plugins/transform-object-assign/):

My `package.json`:
```
"steal": {
    "babelOptions": {
        "plugins": [
            "transform-object-assign"
        ]
    },
}
```
Then I created a module `test.js` that uses `Object.assign`:
```js
console.log( Object.assign({}, {a: 1}) );
```
and I import it from my `app.js`:
```js
import "./test"
```
And finally my html looks like:
```html
<script src="../node_modules/steal/steal.js" main="src/app"></script>
```

IE11 still complains about `Object.assign` being undefined.

**Comment by matthewp** [comment]
Can you provide code examples of what it produces?

**Comment by matthewp** [comment]
This gist is working: https://gist.github.com/matthewp/0027f14633ccd185dff4ca8178dc65da

The transform makes it look like this:

![screen shot 2017-05-10 at 9 53 33 am](https://cloud.githubusercontent.com/assets/361671/25902103/931288c0-3566-11e7-802d-aeb64d37c47f.png)

Just a guess, but are you using ES module syntax in this module? Steal only uses Babel for ES modules.
