### ISSUE TITLE
Saucelabs failing due to environment not existing

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1195]
```
>.>.>.>.>.>>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>.>Error calling driver.init: Error: [init({"maxDuration":1800,"commandTimeout":300,"idleTimeout":300,"build":"230219300","tunnelIdentifier":"2989.4","browserName":"Safari","appium-version":"1.6.0","platformName":"iOS","platformVersion":"10.0","deviceName":"iPhone 7 Simulator","name":"steal tests - iPhone 7 Simulator iOS 10.0 Safari "})] The environment you requested was unavailable.
```

**Comment by matthewp** [comment]
Anyone know where to look up the possible environment names? Maybe saucelabs changed one.

**Comment by matthewp** [comment]
@m-mujica have any idea why this may be happening?

**Comment by m-mujica** [comment]
@matthewp I've seen that error a couple of times. I assumed it was just Saucelabs unable to start the environment and usually a rebuild would "fix it".... 

I think you can see the name for a specific environment through this UI https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

**Comment by m-mujica** [comment]
if you go to saucelabs you can see that it seemed to be an error on the Saucelabs side.  /shrug

![google chrome](https://cloud.githubusercontent.com/assets/724877/25903500/d502ac90-3559-11e7-87a5-42d5701d0796.png)

**Comment by phillipskevin** [comment]
We had this error in canjjs also. I think `'appium-version': '1.6.0'` is no longer available. We resolved this by changing it to `1.6.3` in the [config](https://github.com/stealjs/steal/blob/master/test/saucelabs.js#L40).

**Comment by matthewp** [comment]
Thanks @phillipskevin, I'll try that.

**Comment by m-mujica** [comment]
I'll see myself out 

![tumblr_inline_npe56bidqb1sjtv2m_500](https://cloud.githubusercontent.com/assets/724877/25904106/79572d1a-355b-11e7-93f6-297bc6c52f6c.gif)

**Comment by phillipskevin** [comment]
Also, you can get the available environments from here: https://wiki.saucelabs.com/display/DOCS/Platform+Configurator#/

**Comment by m-mujica** [comment]
I had an old master version locally.
