### ISSUE TITLE
errors while qunit (live-reload?)

### ISSUE THREAD

**Issue by christopherjbaker** [stealjs/steal#1202]
__How often can you reproduce it?__

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

This appears to be related to using live-reload, but not positive. When going through the [stealjs progressive loading guide](https://stealjs.com/docs/StealJS.guides.progressive_loading.html), the tests pass, but produce the error below.

__Steps to reproduce:__

Follow the guide up through testing.

__Expected results:__

No error.

__Actual results:__

```
Potentially unhandled rejection [1] TypeError: reload.once is not a function
    at eval (http://localhost:5000/node_modules/steal-css/css.js:233:13)
    at tryCatchReject (http://localhost:5000/node_modules/steal/steal.js:1183:30)
    at runContinuation1 (http://localhost:5000/node_modules/steal/steal.js:1142:4)
    at Fulfilled.when (http://localhost:5000/node_modules/steal/steal.js:930:4)
    at Pending.run (http://localhost:5000/node_modules/steal/steal.js:821:13)
    at Scheduler._drain (http://localhost:5000/node_modules/steal/steal.js:97:19)
    at Scheduler.drain (http://localhost:5000/node_modules/steal/steal.js:62:9)
    at MutationObserver.run (http://localhost:5000/node_modules/steal/steal.js:268:4)
```

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              |  1.5.2
| Steal-tools version    |  1.3.3
| node -v                       |  6.10.2
| npm -v                        |  3.10.10
| yarn -v                        | 0.24.4
| Browser                      |  Chrome 58.0.3029.110 (64-bit)
| Operating system      |  MacOS 10.12.5

**Comment by matthewp** [comment]
Hi, I tried to replicate this issue with steal-css, steal-qunit, and live-reload: https://gist.github.com/matthewp/2fb0044f58e7f0779474bdc516292cba

I was unable to create this problem.  If you want, clone that gist and get it to break, then we can reopen.

**Comment by justinbmeyer** [comment]
Everyone had this problem at training. Let's keep this open, assign it to Christopher and me, and we'll make sure we figure it out.

**Comment by christopherjbaker** [comment]
I've recreated the issue based on your gist. The only file changed is index.js
https://gist.github.com/christopherjbaker/409371195e8860566a29eefdc4915fdc.

It seems to be tied to using `steal-clone` to import a css file (directly or indirectly, and the file need not contain anything). Using `require('@loader').load('reload-app/styles.css')` does not error. It also errors if the import is inside a test, instead of setup.

**Comment by matthewp** [comment]
Closing in favor of https://github.com/stealjs/steal/issues/1213
