### ISSUE TITLE
"mod.default" causes a syntax error in IE9

### ISSUE THREAD

**Issue by bmomberger-bitovi** [stealjs/steal#1216]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Error in the built files:

https://github.com/stealjs/steal/blob/80f92ebef4705b8e2143bb8b9554e51001ed0e2c/src/loader/loader-sans-promises.js#L1394

https://github.com/stealjs/steal/blob/ba6c84710c01c97a081960b0f5670bc81dbd5318/steal.js#L2664

https://github.com/stealjs/steal/blob/05227f5b4979c2cdd611e9c8bfe100eabc042467/src/loader/loader.js#L2664

Stemming from the source file:

https://github.com/stealjs/steal/blob/05227f5b4979c2cdd611e9c8bfe100eabc042467/src/loader/lib/transpiler.js#L222

https://github.com/stealjs/steal/blob/05227f5b4979c2cdd611e9c8bfe100eabc042467/src/loader/lib/transpiler.js#L429

For these lines to be compatible with IE9, `mod.default` should be rewritten `mod["default"]` (as default is a JS keyword and IE is stricter than others about using reserved words as property names)

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.3
| Steal-tools version    | 
| node -v                       | 
| npm -v                        | 
| Browser                      | IE9
| Operating system      | Windows 7

**Comment by matthewp** [comment]
Thanks, will fix in the morning. Really weird that this wasn't picked up by CI (we run tests in Saucelabs with IE9).

**Comment by bmomberger-bitovi** [comment]
Now that I've had a day to mull on it, I realize that the problem is only going to rear its head in quirks rendering mode (remember that?) which also removes other important things for Steal, like Function.prototype.bind.  I'm assuming the Saucelabs test has the proper !DOCTYPE on the page so strict mode is enforced and these errors don't happen, whereas lots of our individual QUnit testbeds for CanJS modules don't even have a full HTML tag set.

**Comment by matthewp** [comment]
Ah! Ok, that makes me feel better as to why our tests weren't failing.  If you update those pages with the doctype will that be enough to fix those?

**Comment by justinbmeyer** [comment]
Yeah, I think we decided not to support quirksmode with CanJS 3.0 / DoneJS 1.0.  We probably should document this explicitly somewhere.

**Comment by bmomberger-bitovi** [comment]
Just adding <!DOCTYPE html> to our normal three-line QUnit html was enough to make it work.  Obviously I couldn't test the native Promise version because IE9 has no such thing, but then it works with full Steal.  I agree with Justin, but would suggest  a canjs/canjs epic that includes general doc updates and boyscouting test files to have DOCTYPEs as people work on the individual test files.

**Comment by phillipskevin** [comment]
If you're using the latest version of Testee, the DOCTYPE is inserted for you automatically, so updating every test file isn't necessary.

**Comment by andrejewski** [comment]
Maybe Steal can warn when [`document.doctype`](https://developer.mozilla.org/en-US/docs/Web/API/Document/doctype) is null or when [`document.compatMode`](https://stackoverflow.com/questions/627097/how-to-tell-if-a-browser-is-in-quirks-mode) is "Quirks"?

**Comment by airhadoken** [comment]
To be clear, I use http-server for serving tests more often than Testee, and I think that Testee inserting the DOCTYPE is a great idea but it's not a panacea.

And if `document.compatMode` only exists in IE9, that should really just throw a meaningful error: `Steal is incompatible with Quirks Mode. Please set the DOCTYPE on this document`

**Comment by matthewp** [comment]
It couldn't warn or log an error because the syntax error prevents the code from ever executing.

**Comment by bmomberger-bitovi** [comment]
With this item fixed now, it's not a syntax error that makes quirks mode crash, but the absence of `Function.prototype.bind`, so some early checks are possible.

**Comment by matthewp** [comment]
Yeah, feature detecting fn#bind is fine, i agree.
