### ISSUE TITLE
Circular Dependency issue

### ISSUE THREAD

**Issue by christopherjbaker** [stealjs/steal#1218]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

In dev, one of my circular pair is undefined, and later is the expected default export. In prod, it is an object which later gets the default key which is the default export. So while the circular dependencies are eventually resolved, the final value is incorrect in prod.

I have been unable to produce a reduced case. Creating a simple circular dependency in a new project did not recreate this issue. This was [the fix](https://github.com/donejs/bitcentive/blob/2c19d93ff5aa7074a33d4c5b86f0985b74238935/public/models/contribution-month/monthly-os-project.js#L14-L17) needed to compensate.

__Steps to reproduce:__

1. Clone [the repo](https://github.com/donejs/bitcentive/tree/2c19d93ff5aa7074a33d4c5b86f0985b74238935) (currently staging and master reproduce it as well)
2. Install / Setup as per readme.
3. add the following after line 6 of `public/models/contribution-month/monthly-os-project.js`
```javascript
console.log(OSProject);
setTimeout(() => {
  console.log(OSProject);
}, 1000);
```
4. run `donejs develop` and observe the browser console when viewing the main page.

__Expected results:__

it should log `undefined`, and later `[function OSProject]`

__Actual results:__

it logs `{}`, and later `{ default: [funcion OSProject] }`

**Comment by matthewp** [comment]
One thing to note is that this code is wrong: https://github.com/donejs/bitcentive/blob/staging/public/models/contribution-month/contribution-month.js#L37

You can't use a circular reference in the module body because circular references are not resolved until both modules have been executed, and execution order is not deterministic. Not sure if that is related to your bug though.

**Comment by justinbmeyer** [comment]
Yeah, @christopherjbaker fixed a few of these last night.

**Comment by matthewp** [comment]
Ok, so I don't understand, what's the bug here? This is a limitation of circular dependencies. Not of steal's implementation, it's a limitation of the fact that JavaScript is single threaded and can only execute one function at a time.

**Comment by christopherjbaker** [comment]
re: using `MonthlyOSProject.List`, That half of the relationship is consistently behaving properly (as it is used first).

The issue is the finally resolved value. It should be the exported function (as it is on the other side of the circle and the simple tests I created), but instead is `{ default: [function] }`, which can only be used if you use `ContributionMonth.default` or othewise detect it as I did in [the fix](https://github.com/donejs/bitcentive/blob/2c19d93ff5aa7074a33d4c5b86f0985b74238935/public/models/contribution-month/monthly-os-project.js#L14-L17).

**Comment by matthewp** [comment]
It might be working, but it's incorrect, as the relationship is not guaranteed to execute in that order always. A change in the graph elsewhere might cause the other module to execute first which will cause errors.

Anyways, given that this hasn't been reduced yet can we move this issue into the bitcentive repo since, as of now, it's a bitcentive bug.

**Comment by justinbmeyer** [comment]
@christopherjbaker it was also the initially resolved value too right?  Instead of being undefined, it was an object.

**Comment by christopherjbaker** [comment]
Yes. it logs `{}`, and later `{ default: [funcion OSProject] }`

Where should it be moved to?

**Comment by justinbmeyer** [comment]
@matthewp I don't understand .. we've fixed the cycle issue in bitcentive, but the fact that development behaves different than production is still a problem.

**Comment by matthewp** [comment]
I don't doubt that it's a problem, I doubt that this is the appropriate place to file a bug, since it hasn't been reduced down yet. So I think bitcentive is the place for the bug until we are able to figure out what condition causes steal to fail.

**Comment by justinbmeyer** [comment]
It's almost certainly a steal bug though.

**Comment by matthewp** [comment]
So let's file an issue when we have a better understanding of what the condition is that causes the bug. You wouldn't submit an issue to jquery that required them to setup Mongo to see the bug.

**Comment by m-mujica** [comment]
I moved this issue to steal-tools
