### ISSUE TITLE
react-intl not loading

### ISSUE THREAD

**Issue by h1059773** [stealjs/steal#1219]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
I'm trying to use react-intl in my project. After I add import ReactIntl from 'react-intl'; I see errors in the chrome console:
```
Error: Error loading "locale-data/index" at http://mydomain.com/locale-data/index.js
Error loading "locale-data/index" from "mypackage@1.0.0#index" at http://mydomain.com/js/index.js
Not Found: http://mydomain.com/locale-data/index.js
```

My index.js file:
```
import ReactIntl from 'react-intl';
```

In node_modules/react-intl/lib/index.js in line 13 there is:
```
var allLocaleData = _interopDefault(require('../locale-data/index.js'));
```
and Steal probably tries to load this file in the project's scope, not from node_modules/react-intl. Any ideas how to fix it?

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.4
| Steal-tools version    | 1.3.5
| node -v                       | 7.10.0
| npm -v                        | 5.0.1
| Browser                      | Chrome
| Operating system      | Win10

**Comment by matthewp** [comment]
Can you reduce this down to what is breaking? We don't have the bandwidth to debug what every library is doing.

**Comment by justinbmeyer** [comment]
One thing you could print out for us is the arguments and result of `System.normalize` for that call (identifier === `../locale-data/index.js`).

```
System.normalize = function(identifier, parentModuleName, parentAddress, pluginNormalize){

}
```

**Comment by matthewp** [comment]
Need more info to debug what is going on.
