### ISSUE TITLE
Proposal: Chunk Option by Lines. for big bundels

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1220]
__Description:__
We Should Add a Option to split bundels over more then 1 bundle file if the result reaches x lines or a configured size i simply think lines get calculated already so we should use that

__Expected results:__
lets bundle a big app.js result 3x dist/bundels/index.js, dist/bundels/index-1.js,  dist/bundels/index-2.js 

__Actual results:__
Current we create a single bundle per package.

**Comment by matthewp** [comment]
Thanks, moving to steal-tools.

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-tools #768](https://github.com/stealjs/steal-tools/issues/768) via [**ZenHub**](https://www.zenhub.com/)
