### ISSUE TITLE
Unable to import ESM using CJS require

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1223]
```js
// sum.js
export default function sum(a, b) {
  return a + b;
}
```

```js
// main.js
var sum = require("./sum");
sum(2, 2); // throws! 
```

Breaking test https://github.com/stealjs/steal/tree/cjs-esm-interop

**Comment by frank-dspeed** [comment]
@m-mujica i am not sure if this is a bug i think the both require systems arn't compatible @matthewp should choose if steal should make that compatible but in nodejs as far as i know this shouldn't work also

**Comment by matthewp** [comment]
Right, I'm pretty sure you've always needed to do `sum.default(2, 2)` in this case. This is how it works with bundlers as well, I believe.
