### ISSUE TITLE
Nested dependency "ms" not loading correctly

### ISSUE THREAD

**Issue by andrejewski** [stealjs/steal#1224]
__How often can you reproduce it?__ 

Sometimes when served from localhost, always served from Testee on Firefox.

__Description:__

*Note: this is in the context of my attempt to get `can-fixture-socket`'s build passing again.*

I am loading the library `ms` which is a dependency of `debug` which is a dependency of a lot of other projects. Two versions of `ms` are needed looking at `npm ls ms`, versions ^2.0.0 and ^0.7.1. When I load a few dependencies in Steal I get the following errors:

In Firefox (which was run with Testee):
<img width="758" alt="screen shot 2017-07-12 at 3 57 39 pm" src="https://user-images.githubusercontent.com/1660953/28170861-9bd07dca-67b4-11e7-8a1c-f46a83a60e32.png">

In Chrome (serving from http-server):
<img width="761" alt="screen shot 2017-07-13 at 9 42 30 am" src="https://user-images.githubusercontent.com/1660953/28170872-a2b861e8-67b4-11e7-895d-261b9bdda0e1.png">

If not run in Testee, this issue is intermittent even if the code and `node_modules` have not changed. Somehow something is not deterministic.

__Steps to reproduce:__

I created a [slimmed down version of `can-fixture-socket`](https://ufile.io/pv22x) however I was unable to reduce the number of dependencies as this seems, to me, to be a perfect storm issue.

`npm install && npm test` in the project folder to see the issue. If you don't re-try a few times, but this fails on my local and on CI with `can-fixture-socket`.

__Expected results:__

I expect the `ms` module to be found and Steal allow the `can-fixture-socket` test suite to run.

__Actual results:__

The `ms` module is not found and Steal prevents the `can-fixture-socket` test suite from running.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | ^1.2.8
| Steal-tools version    | ^1.1.2
| node -v                       | 8.1.2
| npm -v                        | 4.6.1
| Browser                      | Firefox/Chrome
| Operating system      | Mac OS / Travis's

**Comment by matthewp** [comment]
Noting that to recreate I had to throttle my network a little bit. This makes me suspect the problem is a race condition.

**Comment by m-mujica** [comment]
I was able to replicate this by loading `socket.io-client` alone, with no other deps. (although it fails to load a different dependency, but same problem)

`socket.io-client` depends on `socket.io-parser`, both libraries depend on different versions of 
`component-emitter` (socket.io-client depends on 1.2.1 while the parser depends on 1.1.2); at the top level of the node_modules folder the newer component-emitter (1.2.1) is installed and the version requested by the parser is nested in its own node_modules folder

When npm-crawl tries to fetch socket.io-client's component-emitter, it returns the nested fileUrl b/c `context.paths` has socket.io-parser's component-emitter entry. 

https://github.com/stealjs/steal/blob/f988df2e76ef0b9d8af1c66bde9a89f3a94da1d6/ext/npm-crawl.js#L346-L352

**Comment by m-mujica** [comment]
Setting `context.paths` at this point is an issue, b/c fetch might "fail" for the first fileUrl leaving the context in a wrong state.

https://github.com/stealjs/steal/blob/f988df2e76ef0b9d8af1c66bde9a89f3a94da1d6/ext/npm-crawl.js#L535

But we can't wait until fetch is successful b/c other module's `normalize` hooks get executed while the async fetch is pending...

**Comment by andrejewski** [comment]
@m-mujica Please let me know when this fix is released, I or someone else will use this fix to get the `can-fixture-socket` build working again (hopefully).
