### ISSUE TITLE
Development Bundles doesn't work

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#1227]
__How often can you reproduce it?__ 

- [x] Always

__Description:__
i installed steal and steal-tools on a fresh project.
i want to create a deps bundle. i followed the guides https://stealjs.com/docs/StealJS.guides.development_bundles.html#add-npm-script-to-generate-the-bundle and added the new script tag `<script src="node_modules/steal/steal.js" deps-bundle></script>`

__Steps to reproduce:__

1. clone repo https://github.com/pYr0x/jss-steal-app
2. npm install
3. npm run deps-bundle

__Expected results:__
the dev.html is working.

__Actual results:__
i get an error:
```steal.js:7194 Error: Error loading "dev-bundle" at http://localhost:63342/jss-steal-app/dev-bundle.js
TypeError: define is not a function
	    at Object.eval (http://localhost:63342/jss-steal-app/dev-bundle.js:4:110682)
	    at eval (http://localhost:63342/jss-steal-app/dev-bundle.js:5:4)
	    at eval (http://localhost:63342/jss-steal-app/dev-bundle.js:5:98)
	Evaluating http://localhost:63342/jss-steal-app/dev-bundle.js null
```

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.5
| Steal-tools version    | 1.7.0
| node -v                       | 6
| npm -v                        | 3.10
| Browser                      | chrome
| Operating system      | mac

**Comment by pYr0x** [comment]
Any suggestions @m-mujica ?

**Comment by m-mujica** [comment]
@pYr0x I haven't looked into this yet.... Once I'm done with my current issue I'll see what I can do, I'll let you know.

**Comment by pYr0x** [comment]
Ok thanks

**Comment by m-mujica** [comment]
@pYr0x I can see the error, seems to be caused by the minifier. 

I'm looking deep into  it but while I get a fix you could just pass `--no-minify` to the bundle command and it should load fine (and it should still be faster that loading each dep individually)


```json
"deps-bundle": "steal-tools bundle --deps --no-minify"
```

Thanks for the example app, I'll update this issue once I find/fix the problem.

**Comment by matthewp** [comment]
Am I wrong in thinking that dev bundles are unminified by default?

**Comment by m-mujica** [comment]
@matthewp I can't remember, looking at the code now. 😬

**Comment by m-mujica** [comment]
@matthewp https://github.com/stealjs/steal-tools/blob/master/lib/build/bundle.js#L20

**Comment by pYr0x** [comment]
I wonder if there is no test for the deps bundle?

**Comment by m-mujica** [comment]
> I wonder if there is no test for the deps bundle?

sure, there are tests https://github.com/stealjs/steal-tools/blob/master/test/dev_bundle_build_test.js, the bug will show up only if a dependency package.json has a `"/*" in one of its properties.

> Can we not set that midule pre definded as amd, with the meta config ?
maybe, not sure how though.

**Comment by pYr0x** [comment]
You are talking about that piece of code ?
https://github.com/stealjs/steal-tools/blob/master/lib/bundle/add_npm_packages_node.js

**Comment by matthewp** [comment]
Should dev bundles be unminified? I can't think of when/why you'd want them to be minified. Just takes longer to build that way.

**Comment by m-mujica** [comment]
I think we should have made that the default, I can't remember why we did not do it. 

I'm in to change it though.

**Comment by matthewp** [comment]
So if we just make that the default that takes away this bug, right?

**Comment by m-mujica** [comment]
@matthewp yup, there you go https://github.com/stealjs/steal-tools/pull/905
