### ISSUE TITLE
can not load JSS with steal

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#1228]
__How often can you reproduce it?__ 

- [x] Always

__Description:__
tried to load JSS https://github.com/cssinjs/jss
```
import jss from 'jss';
import preset from 'jss-preset-default';
```
in my index.js file.

__Steps to reproduce:__

1. clone repo https://github.com/pYr0x/jss-steal-app/tree/jss-bug
2. npm install
3. open dev.html

__Expected results:__
all modules are loaded.

__Actual results:__
there is a problem with the module `jss-global`. the package.json is loaded correctly. this module tries to load `jss` in `node_modules/jss-global/lib/index.js` line 13. 
`jss-global` defines `jss` as a peerDependency (see the package.json of jss-global). but i get an error that steal can not load the package.json of `jss`
`http://localhost:63342/jss-steal-app/node_modules/jss-global/node_modules/jss/package.json`
it seems that steal tries to load `jss` within `jss-global` folder. but thats not correct.

does steal not correctly handle peerDependencies?

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.5
| Steal-tools version    | 1.7.0
| node -v                       | 6
| npm -v                        | 3.10
| Browser                      | chrome
| Operating system      | mac

**Comment by m-mujica** [comment]
looking into this...
