### ISSUE TITLE
Steal workaround for IE CSS Limit in IE10

### ISSUE THREAD

**Issue by amcdnl** [stealjs/steal#123]
Steal has code ( https://github.com/bitovi/steal/blob/master/steal.js#L1361 ) that accommodates Internet Explorer's CSS limit for versions 6-9 but in 10 the limit has changed.  See: http://blogs.msdn.com/b/ieinternals/archive/2011/05/14/internet-explorer-stylesheet-rule-selector-import-sheet-limit-maximum.aspx

We should remove this hack for code in IE10.  We could do a check like:

```
 document.body.style.msTouchAction == undefined
```

that is outlined here: http://stackoverflow.com/questions/9900311/how-do-i-target-only-internet-explorer-10-for-certain-situations-like-internet-e to bypass this code.

**Comment by m-mujica** [comment]
@matthewp I'm going to release steal-css@1.2.3 and then close this issue, sounds good?

**Comment by m-mujica** [comment]
Fixed in steal-css@1.2.3
