### ISSUE TITLE
Unable to load named AMD module with dependencies

### ISSUE THREAD

**Issue by m-mujica** [stealjs/steal#1237]
@imaustink found this one, the problem is very strange. I was able to replicate with the following code.

```javascript
// index.js 
var foo = require("./foo");
console.log(foo);
```

```javascript
// foo.js
define("foo", ["./bar"], function(bar) {
  return "foo";
});
```

Basically if main requires an amd module with deps, boom, it throws

![screen shot 2017-08-03 at 18 09 26](https://user-images.githubusercontent.com/724877/28949020-05eb4104-7877-11e7-8d29-606cc1de4c48.png)

:/

**Comment by m-mujica** [comment]
so, the code below works.... The dependency does not seem to be the problem but the fact that it's also a named define.

```javascript
// index.js 
var foo = require("./foo");
console.log(foo);
```

```javascript
// foo.js
define(["./bar"], function(bar) {
  return bar;
});
```

**Comment by imaustink** [comment]
Very strange indeed. I'm glad it wasn't just a stupid thing I was doing wrong. For now, I think I'm going to move forward using your workaround. I just wish I could leave a comment in the `package.json`.

**Comment by m-mujica** [comment]
The issue is definitely with named amd modules with dependencies.

Around here 
https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-amd.js#L215-L224

`anonDefine` is set to null for this scenario.

Then AMD's extension `instantiate` hook only sets an `execute` function if `anonDefine` is truthy.

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-amd.js#L317-L320

Then down the instantiate pipeline, since `load.metadada.execute` is not set, `entry` is undefined.

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-register.js#L504-L512

No `entry` means that the module does not get to `loader.defined`.

And finally, when the module is going to be evaluated.

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-register.js#L381-L385

`getModule` tries to get `foo` from `loader.defined` but it's not there https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-register.js#L335-L343

... I'm guessing the special logic are named `define` modules has to do with bundles in production, but I'm not sure if that's true or how to fix this issue.

cc: @matthewp

**Comment by matthewp** [comment]
So, I think the issue here is that because `foo` is an npm package it's actual module name is likely `foo@1.0.0#index`. So because that never gets defined, it throws.

What we could possibly do is, when a named-define is registered, see if the currently-executing module's package name === the define name, and if so double-register under both `foo` and `foo@1.0.0#index`.

**Comment by m-mujica** [comment]
@matthewp why is `foo` an npm package? I have it as a local package in my example.

```js
// index.js
var foo = require("./foo");
console.log(foo);
```

```js
// foo.js
define("foo", ["./bar"], function(bar) {
  return bar;
});
```

this example fails and `foo` is a regular module, not a package. Am I missing something?

**Comment by matthewp** [comment]
Are you using the npm plugin to load your app or a stealconfig.js? If you are using the npm plugin then all modules are in an npm package and will have the whacky module names.

**Comment by m-mujica** [comment]
gotcha, I was confused... just tried the same example with a `stealconfig.js` instead and it worked fine.

**Comment by m-mujica** [comment]
Just to explain the problem to myself, with a package.json like this:

```json
{
  name: "app",
  version: "1.0.0"
}
```

`foo` needs to be also registered as `app@1.0.0#foo` because when the npm plugin is used, the converted name is the one to be looked up in the registry.

So, around here:

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-amd.js#L235

we need to register the converted name, too.

`loader.npmContext.convert.name` comes to mind, but first, I need to figure out where to get all the arguments to apply that function to and also, registerModule logic is sync and I think `convert.name` might be async sometimes.  

> see if the currently-executing module's package name

I'm not sure about this part yet.

**Comment by matthewp** [comment]
@m-mujica you could change here:

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/src/base/lib/extension-amd.js#L309

to something like:

```
var oldName = currentModuleName;
currentModuleName = load.name;
loader.__exec(load);
currentModuleName = oldName;
```

where `currentModuleName` is defined somewhere within the scope that the define() function can access it.

Then use npmUtils.moduleName.parse(currentModuleName) to see if the name === packageName.  You might have to stick npmUtils on the npmContext if it's not already.

**Comment by m-mujica** [comment]
@matthewp something I noticed about `convert.name` is that "bare identifiers" are assumed to be dependencies (makes sense to me)

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/ext/npm-convert.js#L173-L176

So, local named modules won't be converted as we want. I think it's safe to assume named modules will be bare identifiers and if for some reason we get a name with "./" on it we should totally ignore that.

I wonder, should we make a simplified `convertBareIdentifier` that only does this part:

https://github.com/stealjs/steal/blob/d0e96bae5c672bfd859e9e13eef9e2e53f52163b/ext/npm-convert.js#L162-L167

We might even make it local to the AMD extension.

Also, is it safe to assume that `pkg` is the root package? What if the named module is inside a dependency, shouldn't we be using its parent package?

I was thinking of using 

```js
var convertedName = loader.npmContext.convert.name(
  loader.npmContext,
  loader.npmContext.utils.pkg.getDefault(loader),
  false,
  false,
  name
);
```

but `loader.npmContext.utils.pkg.getDefault(loader)` but this will alway return the root package.

**Comment by matthewp** [comment]
npm-convert isn't the right thing to use here. It's for converting names. You don't want to convert the name, you want to check if the `name` === the current pkg.name. npm-convert is used to convert pkg.steal configuration. It does weird stuff like wait until a module is loaded and update the object. I think you just want to use npmUtils.moduleName.parse directly.

In fact, I would go ahead and in the npm plugin, maybe in the `locate` hook, store the result of `utils.moduleName.parse(load.name)` in the metadata. That way any hook can use that information.

```js
locate = function(load){
  load.metadata.parsedModuleName = utils.moduleName.parse(load.name);
   ....
};
```

Then you just need to check if `load.metadata.parsedModuleName.packageName === name` in the amd function.
