### ISSUE TITLE
Steal 2.0

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1250]
__tldr__; release a stealjs 2.0 that is closely compatible with 1.0, but removes the promise polyfill from *steal.js*, and a few other minor not-often-used features.

> This was discussed on a [recent live stream (37:01)](https://youtu.be/coSEECcyi00?t=37m01s) and a [previous live stream (4:03)](https://youtu.be/ndAlLvRmyNI?t=4m03s).

# Proposal

Release Steal 2.0 that makes a few small breaking change that most people won't care about, and many will love!

* Remove the promise polyfill from *steal.js*. The polyfill will be included in a separate build, maybe called *steal-with-promises.js*. This will greatly improve debugging asynchronous code.
* Remove support for the bower plugin.
* Remove support for npm 2 (which almost no one uses any more).
* Make including a `main` attribute in the steal script tag required. This will improve understanding that steal does load a main, and make demo pages less weird.
* Cleaned up logging output for steal-tools.
* Make `envify` on by default.

## Todos 

- [x] migration guide
- [ ] article

**Comment by m-mujica** [comment]
Can we get rid of bower support for 2.0?

**Comment by matthewp** [comment]
We decided that tree-shaking should be a 2.0 issue. As a result we are doing 2.0 now! However, it will be a slimmed down version, not everything mentioned above will be part of 2.0. Instead we will defer those issues for 3.0.

2.0 will feature:

* Tree-shaking, on by default.
* Promise polyfill not included in steal.js, instead a `steal-with-promises.js` module will be created for those that need it.
* `envify` on by default in steal-tools.
* Removal of npm2 and bower support.
* Revisit browser and Node support (likely IE11+ browsers, and Node 6+).

**Comment by chasenlehara** [comment]
I think we can close this issue. 🎉https://www.bitovi.com/blog/steal-2.0
