### ISSUE TITLE
steal.joinURIs returns the wrong result when an @ is part of the path

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1253]
```js
steal.joinURIs("http://127.0.0.1:8080/node_modules/@priv/dep/styles.less", "/images/bird.png");
```

should return `http://127.0.0.1:8080/images/bird.png` but instead returns `http://127.0.0.1:8080/node_modules/@priv/images/bird.png`.

This is because the regex in [parseURI](https://github.com/stealjs/steal/blob/547aa532076a934588158adb0cc86db278cb8c9a/src/start.js#L57) doesn't account for the `@`. I have a branch with a breaking test.

**Comment by matthewp** [comment]
Breaking test is in the `joinuris` branch.

**Comment by PieterSwitten** [comment]
@James0x57 @matthewp 
Any updates on this issue? I'm having the same error when building my application.

**Comment by matthewp** [comment]
No updates yet, we are working on it.
