### ISSUE TITLE
babel-preset-env issues

### ISSUE THREAD

**Issue by BigAB** [stealjs/steal#1256]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

Thought leaders in the Babel community are recommending **[babel-preset-env](https://github.com/babel/babel-preset-env)** as a best practice when using Babel.

[![As much as I'm excited we're all publishing our own Babel presets, can we work together to recommend using babel-preset-env?](https://user-images.githubusercontent.com/76821/29637788-d478da74-881a-11e7-817e-9cb74d121c4f.png)](https://twitter.com/left_pad/status/847525616480079873)

[![Friendly tip! Try using babel-preset-env!](https://user-images.githubusercontent.com/76821/29637915-3c9f9dd6-881b-11e7-8363-f717e3ce7987.png)](https://twitter.com/TheLarkInn/status/886674992930242560)

[![Starting to think libs should not polyfill stdlib and leave it to app. E.g. via babel-preset-env & useBuiltIns:](https://user-images.githubusercontent.com/76821/29637983-68e1f42a-881b-11e7-99b5-8441ec2b2344.png)](https://twitter.com/rauschma/status/898300357159374848)

...etc.

But **it currently throws an error when trying to use [babel-preset-env](https://github.com/babel/babel-preset-env)** with StealJS.

![image](https://user-images.githubusercontent.com/76821/29638145-e6720934-881b-11e7-85a4-799997da4884.png)

__Steps to reproduce:__

1. here is a link https://glitch.com/edit/#!/standing-recess
2. configure babel in package.json to use **babel-preset-env**
3. watch the world burn

__Expected results:__

I want steal to work when configured with **babel-preset-env** without error 

__Actual results:__
It errors

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              |  1.5.9
| Steal-tools version    |  ???
| node -v                       | 6.11.1
| npm -v                        | 3.10.10
| Browser                      | Chrome
| Operating system      | Mac

**Comment by matthewp** [comment]
A proverbial who's who of [jscelebz](https://twitter.com/jscelebz?lang=en) !!

**Comment by BigAB** [comment]
Some more news to increase urgency in this issue:
https://babeljs.io/blog/2017/09/12/planning-for-7.0#deprecate-es20xx-presets

> Developers shouldn’t even need to make the decision of what yearly preset to use? If we drop/deprecate these presets then everyone can use babel-preset-env instead which will already update as the spec changes.

**Comment by matthewp** [comment]
Going to close in favor of the more descriptive bug: https://github.com/stealjs/steal/issues/1277
