### ISSUE TITLE
Show more of the package.json in the progressive loading guide

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1267]
![stealjs_-_progressive_loading](https://user-images.githubusercontent.com/78602/30141422-fbd1136c-9340-11e7-9438-25e59b05c561.png)

People think to insert this where it says: `"steal": "^1.5.0"`

**Comment by matthewp** [comment]
Do you mean in the progressive loading guide? How much would you suggest showing?

**Comment by justinbmeyer** [comment]
We should probably get diffs to work and give people the ability to see all of it.

**Comment by justinbmeyer** [comment]
One other thing I noticed is that there's not a link telling people to open `/index.html`.  It's implied.  This confused a bunch of folks.
