### ISSUE TITLE
Move guides out of this repo

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#1269]
It would be nice if all the guides/pages/topics that aren’t specific to `steal` were moved to the [website repo](https://github.com/stealjs/stealjs/) so a new release of this module wasn’t required to update the site.

Moving the [pages directory](https://github.com/stealjs/steal/tree/master/docs/pages) would be a good start, but there might be other pages that should be moved too.

**Comment by matthewp** [comment]
This are now in the website repo.
