### ISSUE TITLE
optimize build maybe not working with done-autorender?

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#1275]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
try to build a optimized bundle with done-autorender `"main": "steal-pwa-example/index.stache!done-autorender/no-zone"`
with steal-tools `build` all worked fine.

__Steps to reproduce:__

1. https://github.com/pYr0x/steal-pwa-example/tree/manifest
2. clone and follow the instructions on the readme for nodejs (production)
3. build with `npm run optimize`
4. open the webpage and see the error
```
Uncaught TypeError: Cannot read property 'call' of undefined
    at stealRequire (index.js:187)
    at Object.<anonymous> (index.js:15521)
    at stealRequire (index.js:187)
    at index.js:328
    at index.js:329
```

__Expected results:__
working

__Actual results:__
some module can not loaded.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.13
| Steal-tools version    | 1.8.4
| node -v                       | 8
| npm -v                        | 5
| Browser                      | chrome
| Operating system      | mac

**Comment by matthewp** [comment]
Thanks! Will take a look.

**Comment by matthewp** [comment]
Going to move this over to steal-tools.

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-tools #845](https://github.com/stealjs/steal-tools/issues/845) via [**ZenHub**](https://www.zenhub.com/)

**Comment by pYr0x** [comment]
yep sorry.. was on the wrong repo...
