### ISSUE TITLE
use npmignore

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#1286]
use the npmignore to exclude files we dont want to publish to npm like:
- test/
- docs/
- scripts/
and i think src/ as well because we are building your steal 

see https://github.com/npm/npm/wiki/Files-and-Ignores

the same applies to steal-tools

**Comment by matthewp** [comment]
We do want to include docs/ as that is how stealjs/stealjs consumes the documentation.

**Comment by pYr0x** [comment]
Ok
