### ISSUE TITLE
Dev bundles are built without any dev messages

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal#1288]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

When I load the app in development mode (no bundles at all) lots of log messages are displayed from stache and other packages. If I build to dev-bundles, and run the app, all is well, but no messages are logged. So steal is probably removing the code when it is built (like in production). 

__Steps to reproduce:__

1. Run app in non-bundled dev mode
2. Log messages are displayed from can-util/js/dev/dev
3. Build app using 
```
"dev-bundle": "steal-tools bundle --deps --no-minify",
```
4. Run app and no log messages are displayed

__Expected results:__

I would expect to see the dev messages since these are dev bundles. 

__Actual results:__

Dev messages are not displayed in dev bundles.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.5.15
| Steal-tools version    | 1.9.1
| node -v                       | 6.11.0
| npm -v                        | 5.4.2
| Browser                      | Any
| Operating system      | Windows 7

**Comment by matthewp** [comment]
Yeah, we should turn off that option by default in the dev bundles.

**Comment by roemhildtg** [comment]
Oh, Just realized I could probably add `--removeDevelopmentCode=false` right?

**Comment by matthewp** [comment]
I'm not sure if we have a cli flag for that, but using steal tools.bundle from JS you can pass that flag through the second arg.

**Comment by tracer99** [comment]
Would this be the same issue we're experiencing that runtime errors are also being disappeared by steal when using dev bundles?

**Comment by matthewp** [comment]
This is fixed in steal-tools 1.10.0
