### ISSUE TITLE
Proposal: Loading importing of WebComponents

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1289]
Its Time to make Steal Load WebComponents

**Comment by matthewp** [comment]
Web components are written in JavaScript and steal has no problem loading JavaScript.

**Comment by frank-dspeed** [comment]
@matthewp nope my frind reopen that WebComponents are written in html and get loaded via link import tag

**Comment by matthewp** [comment]
Oh, sorry, I misunderstood. I'll reopen and then move to stealjs/rfcs as that's the place for plugin requests.

**Comment by matthewp** [comment]
Issue moved to [stealjs/rfcs #17](https://github.com/stealjs/rfcs/issues/17) via [**ZenHub**](https://www.zenhub.com/)
