### ISSUE TITLE
Cache Busting Extension

### ISSUE THREAD

**Issue by Wizardum** [stealjs/steal#129]
Hey guys,

So when I build my application, I get the following structure:
```
production.js
packages/clients-default.js
packages/clients.js
packages/default.js
```
`clients.js` and `default.js` are two packages, which depend on `clients-default.js` because it contains the shared dependencies between both packages.

Everything runs as expected.

There is only one concerning issue, which is when steal loads the files in production mode.

I've configured steal to append a suffix value to all files, in order to prevent the browser from caching new files.

When loading, steal appends the suffix to all files except the shared dependency file `clients-default.js`.

I did a quick look around on the code in hopes I could find where a `ConfigManager.addSuffix` call is missing, but I'm afraid I can't spend much more time on this.

If someone knows where it can be fixed I would gladly submit a pull request to quickly solve this issue.

Thanks,
Mario

**Comment by matthewp** [comment]
SystemJS has a proposal for a way to do this: https://github.com/systemjs/systemjs/issues/172#issuecomment-75236888

**Comment by whitecolor** [comment]
Any progress on this?

**Comment by matthewp** [comment]
There's https://github.com/stealjs/cache-bust now.  Any advancements should be filed there.
