### ISSUE TITLE
Website logo broken

### ISSUE THREAD

**Issue by TheJaredWilcurt** [stealjs/steal#1290]
Your website logo has been broken for a long time. Doesn't really, ya know, inspire confidence.

**Comment by matthewp** [comment]
@TheJaredWilcurt Those types of comments don't help. Please be cordial when reporting issues.

**Comment by TheJaredWilcurt** [comment]
@matthewp 
You're fucking welcome?

Last time I visited your site was like a month ago and it was broken then too. Which means one of the following:

* Even you guys don't visit your own site
* You have no attention to detail
* or, you just don't care

None of options makes me confident about using StealJS.

Sorry for making you fix your broken shit. Clearly this should have gone unfixed for a few more months, as it was of no help.

**Comment by chasenlehara** [comment]
@TheJaredWilcurt, I appreciated you letting us know about the issue, although your comments are not in line with [our Code of Conduct](https://github.com/donejs/donejs/blob/master/CODE_OF_CONDUCT.md). Please use welcoming language and show empathy towards the maintainers of this project.

**Comment by matthewp** [comment]
@TheJaredWilcurt You're now banned from the stealjs organization. Good luck finding open source projects that let you talk to them that way.
