### ISSUE TITLE
Feature - ability to define implicit dependencies using meta deps

### ISSUE THREAD

**Issue by DesignByOnyx** [stealjs/steal#1297]
We are using `semantic-ui-react` and its sister `semantic-ui-css`. Each component depends on one or more CSS files, and we are wanting to do something like this so that developers can easily use components without thinking about the other dependencies:

```js
{
  map: {
    'semantic-ui-react/dropdown': 'semantic-ui-react/dist/es/modules/Dropdown/DropDown'
  },
  meta: {
    'semantic-ui-react/dropdown': {
      deps: ['semantic-ui-css/components/dropdown.css', 'semantic-ui-css/components/icon.css']
    }
  }
}
```

Right now the above code does not work _with non-global modules_.

**Comment by matthewp** [comment]
I think @justinbmeyer pointed out on chat that this could probably be done by simply prepending the appropriate import/require as a string. To make this work with ES modules I think you'd have to hook on the `transpile` hook like the [trace extension does](https://github.com/stealjs/steal/blob/0e5714b79f8eaf18f42a2509f781a1dc18fdfe2b/src/trace/trace.js#L179).

**Comment by DesignByOnyx** [comment]
Sounds good - I'll hit you up.
