### ISSUE TITLE
PR: steal-element replaces steal <script tag>

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1309]
This is to track state of steal-element a way to supply custom scope to steal-module-element
-https://github.com/at-nikolaus/steal-element

## Example
```html
<!-- Global -->
<steal>
// Steal module code here like Steal.import
// This is not scoped so this innerText === Steal Module
</steal>
<steal-module>
// Steal Module with global window.Steal 
// Steal.import
</steal-module>
<!-- Scoped The Steal tag it self holds a own Steal version that can be shared via selecting the tag-->
<steal baseURL="" scoped>
// All steal-module tags between the Tag is using this.currentScript.Steal
<!-- When scoped is set this is not a script tag content its HTML element-->
<steal-module>
// All between the Tag is using this.currentScript.Steal
//import myView ...
</steal-module>
</steal>
```

## Why
This is to handle future upcoming challenges with web components and also make existing implementations more easy adopt able 

Steal Scoped can be runned in service webworkers

**Comment by matthewp** [comment]
This appears to be the same as https://github.com/stealjs/steal/issues/1308, so closing this for the same reason as that one.

**Comment by frank-dspeed** [comment]
@matthewp why do you close my PR befor i even sended it and the code i think that should not be done so fast!

**Comment by matthewp** [comment]
Explanation is in the other issue that you filed.

**Comment by frank-dspeed** [comment]
@matthewp 
- demonstration customScript Element in action https://jsbin.com/pizorolape/edit?html,js,output
