### ISSUE TITLE
PR: steal-tree

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1310]
Sorry for the not so well explained PR information but i was forced here https://github.com/canjs/can-component/issues/173 to talk about it and so that this is complet 

This issue tracks the upcoming pr for steal tree that aims to create nativ tar.gz bundles with file meta and browser support that can be expanded into a object with original folder file names so we work on same structure in bundles and development.

it returns nativ blobs that can be returned with mime type as extra url data object that can directly be integrated into a website this allows also assets bundles.

Includes versioning features.

about the name **steal-fs** would also be cool or **steal-tar**

The Service worker untar implamentation is already done now working on a way to run in single th env efficent will take some weeks

```
StorageObj.getJs() === the script as js export as when you would import it
StorageObj.getBlob('mime')
```

## Documentation
The module is a function that returns a modified Promise with a progress callback.
This callback is executed every time a file is extracted. 
The standard Promise.then method is also called when extraction is done, with all extracted files as argument. 
The extraction is done in a [Web Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API) to allow the main UI thread to continue.

### Example:

	// Load the source ArrayBuffer from a XMLHttpRequest (or any other way you may need).
	var sourceBuffer = [...];
	
	untar(sourceBuffer)
	.progress(function(extractedFile) {
		... // Do something with a single extracted file.
	})
	.then(function(extractedFiles) {
		... // Do something with all extracted files.
	});

	// or

	untar(sourceBuffer).then(
		function(extractedFiles) { // onSuccess
			... // Do something with all extracted files.
		},
		function(err) { // onError
			... // Handle the error.
		},
		function(extractedFile) { // onProgress
			... // Do something with a single extracted file.
		}
	);

### File object
The returned file object(s) has the following properties. Most of these are explained in the [Tar wikipedia entry](https://en.wikipedia.org/wiki/Tar_(computing)#File_format).

* name = The full filename (including path and ustar filename prefix).
* mode
* uid
* gid
* size
* modificationTime
* checksum
* type
* linkname
* ustarFormat
* buffer An ArrayBuffer with the contents of the file.
* blob A [Blob](https://developer.mozilla.org/en-US/docs/Web/API/Blob) object with the contents of the file.
* getBlobUrl() 
  A unique [ObjectUrl](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) to the data can be retrieved with this method for easy usage of extracted data in &lt;img&gt; tags etc. 
  
  			document.getElementById("targetImageElement").src = file.getBlobUrl();
* readAsString()
	Parse the file contents as a UTF-8 string.
* readAsJSON()
	Parse the file contents as a JSON object.

If the .tar file was in the ustar format (which most are), the following properties are also defined:

* version
* uname
* gname
* devmajor
* devminor
* namePrefix

This kind of operations support a lot of amazing behaviors

**Comment by matthewp** [comment]
This issue is to create tar files from bundles? Why?

**Comment by frank-dspeed** [comment]
@matthewp we create tar files with the unmodifyed graph and then have path mappings 1:1 to real pathes and can set mappings to the files in that tar archive to the right vars in the right context

**Comment by matthewp** [comment]
Ok, so this is a web packaging format. You can try it, my guess is that it will be much slower than bundling though.  Going to move to the rfcs repo.

**Comment by matthewp** [comment]
Issue moved to [stealjs/rfcs #18](https://github.com/stealjs/rfcs/issues/18) via [**ZenHub**](https://www.zenhub.com/)
