### ISSUE TITLE
Track RFC's with a issue here

### ISSUE THREAD

**Issue by frank-dspeed** [stealjs/steal#1311]
i often find my self creating dub's to rfc because i always forget that they exist maybe tracking it here via a issue would be also a great idea :+1:

**Comment by matthewp** [comment]
Then there would be 2 places that no one checks.

**Comment by frank-dspeed** [comment]
@matthewp i always check the issues here :) i only use github issues

**Comment by matthewp** [comment]
Who's going to maintain this list? I don't want to be responsible for it.

**Comment by chasenlehara** [comment]
Agreed that it doesn't make sense to have a duplicate issue in this repo.
