### ISSUE TITLE
First function never runs

### ISSUE THREAD

**Issue by NorthDecoder** [stealjs/steal#1322]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__
The very first function in the first line is never called because it is missing ending parenthesis.
```
!function(e){
"object"==typeof exports?module.exports=e():"function"==typeof define&&define.amd?define(e):"undefined"!=typeof window?window.Promise=e():"undefined"!=typeof global?global.Promise=e():"undefined"!=typeof self&&( self.Promise=e() )
} //() adding parenthesis here will cause it to be called

// if it does run when parenthesis are added it will fail with error
//   TypeError: e is not a function

```

A simple test scenario looks like this:

```
function testTheCallback (cb) { console.log( cb() ); }

function e () {return "callback e";}
console.log("1. " + e() +" is a " + typeof(e) ); // callback e is a function

!function(e){console.log( "this function is NEVER called!"  )} // is never called
!function(e){
  console.log( "2. second function is called, argument `e` is " + typeof(e) )
  }() // parenthesis cause call, but callback e is undefined...

// here in a named function the callback works
console.log("3. testTheCallback(): ");
testTheCallback( e ); // logs the string that e returns `callback e`
```

__Steps to reproduce:__

1. Link to test [jsfiddle](https://jsfiddle.net/northdecoder42/xfoLmd61/1/); see the browser console for the logged results.
2. Detail the exact steps taken to produce the problem
   a. Cloned version 1.6.2
   b. Made a new git branch and checked it out.
   c. Wrote a separate Qunit test runner page
   d. In steal.js file added carriage return and newline between first and second function
   e. Added parenthesis, ran the test runner page and noted the failure in the browser console.

__Expected results:__
Would expect that the function would be needed by the script and run at some point.  My conclusion is that this function is unnecessary.

__Actual results:__
It failed as expected, `TypeError: e is not a function` apparently due to passing function `e` into an anonymous function.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              |  1.6.2
| Steal-tools version    |  none
| node -v                       |  none
| npm -v                        |  none
| Browser                      |  Firefox 57.0.4 (64-bit)
| Browser                      |  Version 63.0.3239.132 (Official Build) (64-bit)
| Operating system      |  Windows 10 (web page served by AWS c9.io workspace)

**Comment by pYr0x** [comment]
@NorthDecoder , this function is not wirtten by us.
the function comes from https://github.com/cujojs/when/blob/master/es6-shim/Promise.js
we build the `steal.js` with this [Gruntfile.js](https://github.com/stealjs/steal/blob/master/Gruntfile.js)
as u see in line 46. we took `when` and concat it with your code. you can try to
- clone steal
- update dependency `when` to 3.7.8
- run all tests
- run the gruntfile and build steal.js

see if this solve the problem

**Comment by NorthDecoder** [comment]
👍
