### ISSUE TITLE
v1.6.4 breaks some tests in IE

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#1327]
With v1.6.4, the [canjs/canjs](https://github.com/canjs/canjs/pull/3926) tests were failing in IE9, IE10, and IE11 because of this error:

![image](https://user-images.githubusercontent.com/5851984/36121392-9db2b0cc-100b-11e8-9b35-93b463adc201.png)

I'm not positive this is actually a bug in steal, just wanted to open the issue to get some help tracking it down. Going back to 1.6.3 causes the tests to pass again.

**Comment by phillipskevin** [comment]
@matthewp can you help me understand what this error means?

Does it indicate that `can-component` is throwing an error in IE which is causing it to fail to load?

**Comment by matthewp** [comment]
I don't get a lot from that error message either, unfortunately. Do you not see this in 1.6.3? Actually 1.6.4 did change to prevent modules from rerunning when they had already failed, so weird to see that error here. If it works in 1.6.3 there could be a steal bug here.

**Comment by phillipskevin** [comment]
Yes, it works in 1.6.3.

**Comment by matthewp** [comment]
Ok, I can take a look in that case.

**Comment by matthewp** [comment]
Looking into this today.

**Comment by matthewp** [comment]
So what's happening is that another module fails and we incorrectly report the wrong module. I can't remember why I wrote the code this way. I'm going to fix the underlying issue. Fixing this should cause it to pass.

**Comment by matthewp** [comment]
I'll PR canjs/canjs with the new steal version.

**Comment by matthewp** [comment]
Oh, looks like canjs/canjs is already on the latest. So I'll just verify that 3.x branch is working.

**Comment by phillipskevin** [comment]
https://github.com/canjs/canjs/tree/3.x-legacy has the steal version locked.

**Comment by matthewp** [comment]
I'll send a pr to that branch then.

**Comment by matthewp** [comment]
https://github.com/canjs/canjs/pull/3938
