### ISSUE TITLE
steal-remove tags don't remove when there is a space

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal#1329]
__How often can you reproduce it?__ 

- [x] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

When using steal remove tags like:
```javascript
  //! steal-remove-start
  route.bindings.pushstate.root = '/';
  //! steal-remove-end
```

The space is created by eslint, and there appears to be a test for steal-tools but doesn't work with newlines apparently.
https://github.com/stealjs/steal-tools/blob/68c010d3f59702b370de2b5b4fa74f72f9be14ab/test/clean_test.js#L6

As a workaround, we can do this:
```javascript
// eslint-disable-next-line
//!steal-remove-start
url = '';
// eslint-disable-next-line
//!steal-remove-end
```

__Expected results:__

The lines should be removed

__Actual results:__

the lines are not removed. 

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              |  1.6.4
| Steal-tools version    |  1.11.2
| node -v                       |  8.9.4
| npm -v                        | 5.4.2
| Operating system      | Windows 7 x64

**Comment by m-mujica** [comment]
@roemhildtg this is fixed in steal-tools@1.11.4, thanks again for reporting.
