### ISSUE TITLE
Cataloging common errors

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1330]
This issue is for designing improved error messaging in steal, as part of https://github.com/donejs/donejs/issues/1073.  I'm going to start by finding common errors and listing those here, then will discuss with others how these should look.

# Common errors

* Importing a module that doesn't exist.
  * Possibly different between a local module and an npm module.
* Syntax error within a module.

## Notes

| Scenario    | File missing                                   |
| ----------- | ---------------------------------------------- |
| Loading     | https://github.com/stealjs/steal/issues/1331 https://github.com/stealjs/steal/issues/1332 https://github.com/stealjs/steal/issues/1333 |
| SSR         |                                                |
| Live Reload |                                                |

**Comment by justinbmeyer** [comment]
Might want to includ how plugins can report similar problems.  Example, what if can-view-import gets a path wrong?

**Comment by matthewp** [comment]
@justinbmeyer I would expect those problems would be reported by Steal, since can-view-import is using steal to import the module.

**Comment by matthewp** [comment]
I'm going to close this issue and record these errors in https://github.com/donejs/donejs/issues/1073 instead since it makes sense to document each error and how it affects steal, done-ssr, live-reload, and other scenarios.
