### ISSUE TITLE
Typescript Definition File

### ISSUE THREAD

**Issue by daryllabar** [stealjs/steal#1367]
Would you consider [bundling a Typescript Definition](http://www.typescriptlang.org/docs/handbook/declaration-files/publishing.html) file for StealJS to allow it to be more easily consumed from TS?

**Comment by matthewp** [comment]
We would definitely take a contribution for this.

**Comment by daryllabar** [comment]
I'm so new to Steal, I don't think I'd be able to do much, but if it helps someone else, here is what I've created locally to be able to call steal.config and steal.import:

``` Javascript
declare module StealLib {
    interface Steal {
        import<T>(module:string): Promise<T>;
        config(config:Config):void;
    }
    interface Config{
        baseURL?: string,
        bundlesPath?: string,
        loadBundles?: boolean,
        paths?: any,
        map?: any,
        main: string
    }
}


declare var steal: StealLib.Steal;
declare var System: StealLib.Config;
```

**Comment by matthewp** [comment]
Closing as I don't think we need a tracking issue here, happy to have someone contribute this though.
