### ISSUE TITLE
babelOptions Inconsistencies

### ISSUE THREAD

**Issue by christopherjbaker** [stealjs/steal#1372]
My project has `babelOptions`, but so does one of my dependencies. The options in the dependency are precedence over the ones in my project.

__How often can you reproduce it?__

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Steps to reproduce:__

1. Use `babelOptions` in your project.
2. Require something from `node_modules` that also has a `babelOptions` specified.

__Expected results:__

Each module that specifies `babelOptions` is compiled using those, and others are compiled with the default.

__Actual results:__

Every module is compiled with the rules from the inner module. I did not test how it handles 2 different inner modules both using `babelOptions`.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.11.0
| Steal-tools version    | 1.11.7
| node -v                       | v8.10.0
| npm -v                        | 5.6.0
| Browser                      | N/A
| Operating system      | MacOS 10.13.3

**Comment by matthewp** [comment]
This was fixed in https://github.com/stealjs/steal/releases/tag/v1.11.4. Now each package uses its own babelOptions.

**Comment by imaustink** [comment]
@matthewp I seem to still be seeing this issue under `1.11.4`.

**Comment by matthewp** [comment]
@imaustink Do you know when this issue still exists? #1377 includes a test so that if a child package has its own babelOptions that will be used. But if not the main babelOptions is used. This is how I expect it to work.

**Comment by imaustink** [comment]
Not sure. I haven't tried this in a long time. I would guess it's safe to close again.
