### ISSUE TITLE
Tree shakeable modules

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1381]
A module which does not contain side-effects such as:

**framework**

```js
export {default as foo} from './foo';
export {default as bar} from './bar';
```

Could be tree shaken *during load* so that we never even load `'./bar'` if it goes unused. The way to achieve this is by examining which exports are used by the parent module.

The method this will be achieved is that the module, **framework** in this case, will be normalized to a different module for each parent that imports it. In this case the module name might be `framework@1.0.0#main/parent@1.0.0#main` (just an example, not sure what these should actually look like yet).

Since modules can have side effects this will be an opt-in behavior, through configuration.

**Comment by justinbmeyer** [comment]
@matthewp does this have to be through configuration?  My thought is that since babel is building the AST anyway, we could pretty quickly determine if a module only has these expressions.  Most modules would fail nearly immediately:

Example that would break:

```js
import foo from "bar"
```

Using the AST would avoid configuration.

**Comment by matthewp** [comment]
The biggest reason to do it through configuration is so that you can determine if it is this type of module during normalization, and normalize to a different moduleName for each parent. Having a single moduleName that represents something different to each parent might be possible... I'm struggling a little to think about how to achieve that though.

**Comment by matthewp** [comment]
The way I can see this as being possible is essentially we are going to have to update the module instance each time a new parent comes in using new exports. We'll have to delete the old module instance and set a new one, containing the new exports.

**Comment by matthewp** [comment]
This is in the major branch now.
