### ISSUE TITLE
Module Type Detection Error

### ISSUE THREAD

**Issue by christopherjbaker** [stealjs/steal#1390]
__How often can you reproduce it?__ 

- [X] Always
- [ ] Sometimes
- [ ] Rarely
- [ ] Unable
- [ ] I didn’t try

__Description:__

I am importing `react-redux` and it errors on a [particular file](https://unpkg.com/react-redux@5.0.7/lib/components/connectAdvanced.js). When viewed in the browser, it does not get the `(function(global, exports, module, require, __filename, __dirname){` treatment that these kinds of modules are supposed to get. I think this is because it contains the phrase `export default`, but this is inside a comment. Removing the word "export" from the comment causes it to load properly.

__Environment:__

| Software                     | Version
| --------------------- | -------
| Steal version              | 1.11.5
| Steal-tools version    | 1.11.8
| node -v                       | 10.0.0
| npm -v                        | 6.0.0
| Browser                      | chrome v66.0.3359.139
| Operating system      | macos 10.13.4

**Comment by matthewp** [comment]
Since this is a higher profile project we should try and fix it.
