### ISSUE TITLE
AMD CommonJS detection false positive

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1412]
In lodash there's some code like:

```js
var types = freeModule && freeModule.require && freeModule.require('util').types;
```

It picks up 'util' as a dependency when it should not.

**Comment by justinbmeyer** [comment]
@matthewp this is w/i lodash's CJS build?

**Comment by matthewp** [comment]
It's caused by the `lodash@4.17.10#_nodeUtil` module.
