### ISSUE TITLE
Envs mapping is not used by `npm-extension`

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1426]
_tldr;_ A map configuration in `envs` like the following does not work:

```js
  "steal": {
    "envs": {
      "test": {
        "map": { "@fixture-socket-hook": "bitcentive/models/fixtures/fixture-socket-server" }
      }
    },
    "map": {"@fixture-socket-hook": "@empty"},
```

If I load steal in the `test` environment as follows:

```
<script src="../node_modules/steal/steal-sans-promises.js" main="bitcentive/test/"  env="test"></script>
```

And then `bitcentive/test/` imports `"@fixture-socket-hook"`, `@empty` will be loaded instead of `bitcentive/models/fixtures/fixture-socket-server`.

## Example

```js
// main.js
import "@load-this-only-in-test";
```

```js
// load-me-only-in-a-test.js
console.log("I AM LOADED");
```

```html
<!-- test.html -->
<script>
steal = {
 "envs": {
      "test": {
        "map": { "@load-this-only-in-test": "load-me-only-in-a-test" }
      }
    },
    "map": {"@load-this-only-in-test": "@empty"}
}
</script>
<script src="../PATH/TO/steal/steal.js" main="main"  env="test"></script>
```

You should see `I AM LOADED`, but you won't.

**Comment by matthewp** [comment]
Thanks, I'm pretty sure there's an existing test for this map behavior, should be easy to create one for envs as well. 

I don't recall why it was necessary to do map config within the npm extension, perhaps it's not needed any more and can just be removed. Worse case is checking for envs here should be fine.
