### ISSUE TITLE
Unable to load steal builtins

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#1428]
```js
var util = require('util');

console.log(util);
```

Generates:

<img width="387" alt="screen shot 2018-06-19 at 9 41 45 am" src="https://user-images.githubusercontent.com/361671/41600893-09ee5258-73a5-11e8-912c-c73181b18211.png">

The problem code is here: https://github.com/stealjs/steal/blob/fd4ae2539ec7eff5284d06d3f6234c931e5d1d3b/ext/npm-crawl.js#L194

`deps` here is an object.

**Comment by janat08** [comment]
how to upgrade to this?

**Comment by matthewp** [comment]
1.12.2
