### ISSUE TITLE
Conditional Loading docs broken

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1464]
https://stealjs.com/docs/StealJS.conditionals.html

![image](https://user-images.githubusercontent.com/78602/46239303-8fb1c580-c35c-11e8-9359-d9ea74ad7505.png)

**Comment by leoj3n** [comment]
Looks like these are just placeholders and such guides don't exist:

https://github.com/stealjs/stealjs/tree/master/doc/steal-topics/guides

So can probably just delete these two guide references.

**Comment by leoj3n** [comment]
Alternatively, might want to link to these sections:

- https://stealjs.com/docs/steal-conditional.html#string-substitution-syntax
- https://stealjs.com/docs/steal-conditional.html#boolean-conditionals

**Comment by matthewp** [comment]
They exist (or at least used to). Probably in the steal-conditional repo.
