### ISSUE TITLE
steal 1.6.5 meta config `less` files

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#1473]
A configuration like:

```
    "meta": {
      "egowall/app.less!$less": {
        "deps": [
          "dist/css/theme.css"
        ]
      },
```

Used to work in steal `<1.0`.

It seems only configuration like the following works:

```
    "meta": {
      "egowall@0.0.0#pages/people/people.less!steal-less@1.3.4#less": {
        "deps": [
          "dist/css/theme.css"
        ]
      },
```

If I have configuration like:

```
    "meta": {
      "egowall/pages/people/people.less": {
        "deps": [
          "dist/css/theme.css"
        ]
      },
```

Those keys get converted to: `egowall@0.0.0#pages/hub/hub.less` in `loader.meta`.

- `egowall/pages/people/people.less!steal-less` => `egowall@0.0.0#pages/people/people.less!steal-less`
- `egowall/pages/people/people.less!steal-less@1.3.4#less` => `egowall@0.0.0#pages/people/people.less!steal-less@1.3.4#less` works

**Comment by matthewp** [comment]
Does `egowall/pages/people/people.less!steal-less/less` work?
