### ISSUE TITLE
New Steal interrupting socket.io.js script load

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#208]
@justinbmeyer posted this steal-can-example: https://github.com/bitovi/steal-can-example

I'm trying to put together a project boilerplate that uses @daffl's feathers project for the server.  While trying to get canjs-feathers to work with steal I keep encountering the following errors:
>Uncaught Multiple defines for anonymous module steal.js:3860
>Uncaught ReferenceError: io is not defined feathers.js:145

After some troubleshooting I've determined that the canjs-feathers module, itself, is imported properly.  However, when trying to initiate the module with can.Feathers.connect(), it attempts to append the socket.io client library to the page here: https://github.com/feathersjs/canjs-feathers/blob/master/lib/feathers.js#L161

Steal stops the request and throws the *Multiple defines* error when the browser downloads the script.

Here are the defines from socket.io.js that are causing the problem: https://github.com/Automattic/socket.io-client/blob/master/socket.io.js#L1

Here is a repository I created using the steal-can-example repository on top of a feathersjs server: https://github.com/marshallswain/feathers-canjs-steal

As a workaround, I'm loading socket.io.js in a script tag before steal.js, and I've modified canjs-feathers to check for the global io object before trying to load the script.

Is there anything I should be doing in Steal to prevent the issue?

**Comment by matthewp** [comment]
We no longer have a `define` on the window, instead there is `System.amdDefine`.
