### ISSUE TITLE
Dev mode does not work with node-webkit

### ISSUE THREAD

**Issue by stevenvachon** [stealjs/steal#232]
Because of things like this:

``` js
typeof global == 'undefined' ? this : global
```

which should instead be:

``` js
typeof window == 'undefined' ? global : this
```

as node-webkit has _both_. This issue extends to both Traceur ([#1340](https://github.com/google/traceur-compiler/issues/1340)) and ~~SystemJS ([#196](https://github.com/systemjs/systemjs/issues/196))~~.

**I was able to get my app working by making the above mentioned changes to local copies of the Bower-distributed traceur.js and steal.js**

---

This issue goes beyond the scope of simply renaming `window.require` to something else. If I were to have done only that, I'd have seen this error:

```
Uncaught node.js Error
ReferenceError: System is not defined
    at file:///project/src/vendors/steal/steal.js:5300:28
    at file:///project/src/vendors/steal/steal.js:5316:3
```

**Comment by matthewp** [comment]
We build to nw.js now, but I don't think I've ever tried in dev. Is this still a desirable feature?
