### ISSUE TITLE
Need documentation explaining plugins

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#238]
I'm not sure if this should be a guide or perhaps a "type", but plugins should be fully explained. We need to explain how to load plugins -- moduleName you are loading, `!` and then the plugin's moduleName.

**Comment by justinbmeyer** [comment]
@matthewp @cklanac @alexisabril 

I think we need an improvement for the moduleName page: http://stealjs.com/docs/moduleName.html which many things will link to.

With that in mind, @matthewp what would the Guide talk about? Here's a proposed outline:

# Plugins

- Overview - plugins allow special behaviors, normally this to load special types.
- First Party Plugins (css, less, etc) ... where to find other plugins (search system on npm).
- difference and similarities between a plugin and an extension

## Use

- the syntax ! and the implicit !
- using map and System.ext to shorten plugin names / make them disappear 

## Authoring plugins

- basic transform
- includeInBuild option

**Comment by matthewp** [comment]
There is a plugin guide here: https://stealjs.com/docs/StealJS.writing-plugins.html
