### ISSUE TITLE
Steal shouldn't catch errors during module evaluation

### ISSUE THREAD

**Issue by asavoy** [stealjs/steal#243]
When a module raises an error during the evaluation phase, StealJS currently catches the error and writes it to the console.log. Here's an example module:

    steal(function() {
        throw Error('something broke');
    });

I find this frustrating for a few reasons:

1. Prevents invoking the JS debugger on uncaught errors. This just adds an unnecessary extra step to development. And when migrating a legacy-steal project, this comes up a lot.
2. Prevents error loggers from working, e.g. RavenJS which relies on errors being uncaught to trigger `window.onerror`.
3. In addition, when using `steal.production.js`, the console message gets completely suppressed and there is no indication that an error occurred.
4. It logs stack traces that are harder to use in browsers other than Chrome, because the point of the error is obscured - the filename is obscured and sometimes line number is too. (IIUC line numbers are incorrect because StealJS/SystemJS transform the source) It's not possible to click it, to jump to the error. For example, in IE11 it looks like this:

        error Error: something broke Error: something broke
        at Anonymous function (eval code:27:5)
        at stealInstantiateResult.execute (http://ironhide.local:8000/static/jsmvc/steal/steal.js:5228:11)
        at linkDynamicModule (http://ironhide.local:8000/static/jsmvc/steal/steal.js:3061:5)
        at link (http://ironhide.local:8000/static/jsmvc/steal/steal.js:2943:11)
        ...

  And in Safari, it looks like this:

        [Log] error  (steal.js, line 5169)
        Error
        execute@http://localhost:8000/static/jsmvc/steal/steal.js:5228:37
        linkDynamicModule@http://localhost:8000/static/jsmvc/steal/steal.js:3061:36
        link@http://localhost:8000/static/jsmvc/steal/steal.js:2943:28
        execute@http://localhost:8000/static/jsmvc/steal/steal.js:3234:15
        ...

I could be missing something as to why StealJS does this, so please enlighten me.

**EDIT:** window.onload => window.onerror
**EDIT 2:** Added point 3 on steal.production.js

**Comment by matthewp** [comment]
Going to add a test that throws to verify, but I think most of these issues have been worked out either upstream or in steal.

**Comment by cedricalfonsi** [comment]
What the status of this bug ?

It looks like some enhancements have been done on the es6-module-loader (https://github.com/ModuleLoader/es6-module-loader/issues/217) following this discussion and the bug reported by @justinbmeyer, to improve the report of the errors.

**Comment by matthewp** [comment]
I think this is mostly addressed.  I still get reports of some errors being caught so I'm not ready to call this fixed. If you have any issues with them being swallowed please submit tests and we can look further into fixing the specific issues.

**Comment by cedricalfonsi** [comment]
Thx for your quick answer @matthewp,

I'm wondering if the errors line number could be addressed too, as the code is evaluated I have some doubts.

By instance on firefox, if I try to call a function which doesn't exist, I get the following stack trace.
```
error
TypeError: bar is not a function
	

mad = $__m.default;

.execute/mad.Control<.init@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js line 2868 > eval:11:11
.newInstance@http://192.168.56.102/mad/js/lib/can/construct/construct.js:201:5
init@http://192.168.56.102/mad/js/lib/can/construct/construct.js:504:6
Constructor@http://192.168.56.102/mad/demo.html#control line 477 > eval:1:47
.execute@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js line 2868 > eval:17:17
doExecute@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:2129:7
ensureEvaluated@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:2176:11
doEnsureEvaluated@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:2139:15
evaluateLoadedModule@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:2114:5
Loader.prototype.import/</<@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:2304:20
tryCatchReject@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:1183:28
runContinuation1@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:1142:4
makePromise/Fulfilled.prototype.when@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:930:4
makePromise/Pending.prototype.run@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:821:5
[3]</</</Scheduler.prototype._drain@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:97:4
Scheduler/this.drain@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:62:4
run@http://192.168.56.102/mad/js/lib/steal/steal.js?app/control.js:268:4
```

I'm preparing the migration of an app to the latest Steal and Can, and we will have to spend some times debugging. I'd like this phase to be as smooth as possible (you imagine), but without clear reports, it will be pain. Maybe we should abandon ES6 and use more classic Steal, CommonJs or AMD styles.

**Comment by matthewp** [comment]
I would expect your error to be on line line 11 but yeah I know what you mean.  Eval code is definitely harder to debug. Using a syntax that doesn't require it like AMD or Steal would be the way to go.  But we do need a CSP build for that, see https://github.com/stealjs/steal/issues/254

**Comment by matthewp** [comment]
Closing in favor of #254
