### ISSUE TITLE
Steal can't find LESS @imports while build process

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#259]
While build steal-tools can not find modules to import if import paths looks like:

```less
@import '/styles/imports/variables';
```

the same result for:

```less
@import 'styles/imports/variables';
```
so styles folder is located in steal root folder. 

The problem is that lessParser needs some correct path options. Adding there baseURL would solve some problme, but maybe also there is need in ability to supply some additional paths for lessParser.

**Comment by matthewp** [comment]
Superceded by https://github.com/stealjs/steal/issues/277
