### ISSUE TITLE
Loading css before executing js in production

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#261]
Well I'll open this issue here as it is responsibility of steal, not steal tools.

For correct behaviour it is needed that css be completely loaded and put on the page before JS (if it not done this way it may result in not just flaw visual experience but event in breaking some kind of the apps dependent on css styles).

```System.instantiated``` for css trick would not work for progressively loaded apps as it will for single module app.

For this css styles should be added as in development version now using ```<style>``` tag. So first we load css and then execute JS, not to get flaw visual experience. 

I propose to configure this via optional parameter (that would be checked in ```css.js``` plugin )something like ```useStyleTag``` or ```cssFirst``` ) What do you think?

**Comment by whitecolor** [comment]
So, when are you going to support this out of the box? It seems that standard systemjs css plugin do this. https://github.com/systemjs/plugin-css/blob/master/css.js

**Comment by matthewp** [comment]
I'm not sure, it's not a high priority of mine but PRs are welcome as always.

**Comment by pYr0x** [comment]
steals dependency on steal-css have to be updated

**Comment by matthewp** [comment]
This is in major and part of 1.0-rc
