### ISSUE TITLE
Support traceur options

### ISSUE THREAD

**Issue by zkat** [stealjs/steal#267]
`traceur` hides some features (most notably its full `blockScoping`, I think, even though `let` seems to still work for the most part) behind flag options, and it expects users to enable them by setting the appropriate `traceur.options.foo` flag.

I looked into how this would work when using `System.js`, and it looks like you're basically expected to load `traceur` manually before loading whatever modules (probably before loading `es6-module-loader` or `System.js` itself), and then slapping the flags in there -- the module loader will then use the global traceur.

The following example code works fine and dandy, and I think it means we can very easily just add an option to steal that takes care of this:
```html
<script src="traceur.js"></script>
<script src="steal.js"></script>
<script>traceur.options.asyncFunctions = true; System.import("some/fancy/asyncFunc/module.js")</script>
```

**Comment by matthewp** [comment]
We have this now in dev, but opened https://github.com/stealjs/steal-tools/issues/179 to track making sure the options get passed through the build.
