### ISSUE TITLE
Sometimes forgets baseURL when loading main module?

### ISSUE THREAD

**Issue by asavoy** [stealjs/steal#271]
I'm using StealJS circa https://github.com/bitovi/steal/commit/a6e7eda6cd99b96eb9e18ae4f6ccf6c80156dfea and on a production site. It works for many browsers I have tested against, but reviewing our 404 logs, I'm seeing strange 404s coming from some users, which look as though StealJS thinks `System.baseURL == ""`. These users are on recent versions of Firefox and Chrome. I haven't reproduced this myself, but there are a substantial number of cases.

Take our login page, which I have chosen because it uses barely any JS:

http://example.com/accounts/login/
```
...
<script type='text/javascript'
        src='http://cdn.example.com/v123/steal/steal.production.js'
        data-main='public/login/login'
        data-config='http://cdn.example.com/v123/stealconfig.js'
        data-env='production'></script>
</body></html>
```

The 404s I am seeing are for:
 `http://example.com/accounts/login/login.js` 

when they should be (and this is what I get whenever I test):
`http://cdn.example.com/v123/dist/bundles/login.js`

IIUC the baseURL is determined within StealJS by the path to `steal.production.js` or `stealconfig.js`, so it should work everytime, but I cannot explain the behavior.

**Comment by matthewp** [comment]
Hey @asavoy did you ever make any progress on this? Were you able to consistently reproduce with any conditions?

**Comment by asavoy** [comment]
Sadly no, despite seeing thousands of these 404 logs across different main pages. There were even a handful of http://example.com/@dev.js and http://example.com/stealconfig.js, but not nearly as common. Might be a clue?

I would have thought someone else would have reproduced it by now... that could be a good sign.

**Comment by HydraOrc** [comment]
Also getting these errors in production mode for some reason, browser is Chrome 36.0.1985.97
GET http://site.com/stealconfig.js 404 (Not Found) steal.production.js:6
GET http://site.com/@dev.js 404 (Not Found)

**Comment by matthewp** [comment]
If this is still an issue, a reproducible case would be great.
