### ISSUE TITLE
Sometimes steal tries to load dev.js without baseURL

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#290]
I have the following configuration:

```index.html``` is loaded from ```host1.local```

```index.html``` contains:
```HTML
<scirpt>
  steal = {baseURL: 'http://host2.local'}
</script>
<script src="http://host2.local/bower_components/steal/steal.js" main="app"></script>
```
So steal and all scripts should be loaded from ```host2.local```, and dev should be loaded from ```steal.js``` folder. Most of the time while page load everything works fine. But sometimes ```dev.js``` is being tried to be loaded from ```http://host1.local/dev.js``` (```index.html``` domain at root path without respect to ```baseURL```)

**Comment by matthewp** [comment]
If this is still an issue, a reproducible case would be great.
