### ISSUE TITLE
WebKit console output a warning: webkitIndexedDB' is deprecated

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#293]
WebKit console output a warning:
```webkitIndexedDB' is deprecated. Please use 'indexedDB' instead.```
on this line:
https://github.com/bitovi/steal/blob/master/steal.js#L3554

not sure what this does mean.

**Comment by matthewp** [comment]
This doesn't happen any more.

**Comment by jasonzoladz** [comment]
This issue is back.

**Comment by matthewp** [comment]
Thanks, haven't noticed in myself but will take a look.

**Comment by jasonzoladz** [comment]
Sorry, please disregard for now.  This may be happening transitively from
my use of jspm.io.  I'll look into it.

**Comment by matthewp** [comment]
Ah, ok, well let me know.
