### ISSUE TITLE
Way to disable loading config and main

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#331]
I would like a way to disable the loading of configMain and main. This would be useful in places like demo pages where you just want to initialize your app in a script tag. You can do this today using `config-main="@empty" main="@empty"` but this is verbose.  I'm not sure what the option should be called, `nostartup` perhaps.

**Comment by justinbmeyer** [comment]
It should be an env setting.

**Comment by justinbmeyer** [comment]
Demo pages should almost always load the config. I'm not sure we need a non verbose way of doing something very rare?

**Comment by matthewp** [comment]
I would use it all the time personally.

**Comment by justinbmeyer** [comment]
Why?

**Comment by matthewp** [comment]
After thinking more about this I don't think this is the best way to achieve what I'm looking for. Probably some type of loader builder tool is the way to go. Will think about that more later.

**Comment by matthewp** [comment]
I think we should revisit this. In 1.0.0 we added `<script type="steal-module">`. This is useful for adding inline module scripts like so:

```html
<script type="steal-module">
  import _ from "lodash";

  ...
</script>
```

If we allowed adding a `src` attribute this could then be useful for the reasons outlined in this issue:

```html
<script src="./node_modules/steal/steal.js" config-main="@empty" main="@empty"></script>
<script type="steal-module" src="./path/to/app.js"></script>
```

Of course that's pretty gross looking 😁. Let's pretend there was a steal that didn't include startup, you could then more easily control loading your config and your main only when needed:

```html
<script src="./node_modules/steal/steal-base.js"></script>

<script type="steal-module" src="./path/to/app.js"></script>
```

The above loads ./path/to/app.js, but doesn't load System.main (we're saying that steal-base.js doesn't do any startup stuff). Let's say you did want to load the config though, you could do it this way:

```html
<script src="./node_modules/steal/steal-base.js"></script>

<script type="steal-module" src="./config.js"></script>
<script type="steal-module" src="./path/to/app.js"></script>
```

Where maybe config.js looks like this:

```js
import "package.json!npm";
```

What I think is better about this approach vs. how Steal currently works is that it's based on a *single primitive concept*. That is, `<script type="steal-module">` is the way that you load stuff. You can load your config, you can load a module (your main or anything else).

This way you don't need to know/understand a bunch of special configuration values like System.main, System.configMain, the concept of `@empty`, etc.

**Comment by matthewp** [comment]
2.0 no longer has autoloading of main. Closing.
