### ISSUE TITLE
IE8 Support with ES6

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#340]
Both Traceur and Babel output use `Object.defineProperty` or `Object.defineProperties` which means ES6 can't be supported if we continue to upgrade Traceur.  I don't know which version this happened in Traceur, it used to (at least in 0.58) not do this.  I wonder if it's fair to drop support for IE8 with ES6 syntax.

**Comment by matthewp** [comment]
I think the answer is definitely yes, we can't hold back Traceur/Babel updates for this, just need to document that ES6 requires IE9+.

**Comment by daffl** [comment]
Didn't Babel have a module exports loose mode that didn't use defineProperty (so it would work in IE8 as long as you include the ES5 shims)?

**Comment by matthewp** [comment]
That's true, we currently don't pass babeloptions into the transpile though.  Issue is here: https://github.com/bitovi/steal-tools/issues/179

**Comment by daffl** [comment]
With that issue solved it should work. I still think Babel should become the default transpiler but I'm not sure if that could be considered a breaking change?

**Comment by daffl** [comment]
Which might also solve https://github.com/stealjs/steal/issues/198 btw.

**Comment by matthewp** [comment]
We should do some testing to justify that change, some benchmarking perhaps.

**Comment by es6Test** [comment]
+1 for babel as the default.

**Comment by matthewp** [comment]
In 1.0 support will be changing to IE9.
