### ISSUE TITLE
Move less plugin into stealjs/system-less

### ISSUE THREAD

**Issue by zkat** [stealjs/steal#346]
I've moved this issue out to stealjs/system-less#1. We should discuss anything about this issue not related to actual core steal features over there. Gonna keep this ticket open for tracking purposes.

As part of this, we should actually move the steal plugin out of this repository and out into that one and make sure it's easily installable/accessible. Perhaps we might still want to include the file in `steal` releases, as well?

**Comment by matthewp** [comment]
Yes, I think we should keep it in the releases but moving it to this new repo is a good idea. That way people who want a more current version don't have to wait for a steal release.

**Comment by matthewp** [comment]
Also, there's a couple of less tests that can probably be moved. There's a test that checks for steal's integration with less... that one should *not* be moved, but any that just tests the functionality of the plugin can, I think.

**Comment by matthewp** [comment]
This one should be pretty easy for someone looking to contribute. What needs to be done is:

* [ ] - Move `ext/less.js` and `ext/less-*.js` to the system-less repo.
* [ ] - Move less tests there as well (note: not [this one](https://github.com/bitovi/steal/blob/master/test/test.js#L194) which tests that less is loaded by default)
* [ ] - Setup CI for that repo
* [ ] - Update steal Gruntfile to move less.js, less-*.js to the `ext` folder where it was before. We do the same sort of thing for system-npm so you can use that as an example.

This will make it easier to keep the less plugin up-to-date with Less releases.
