### ISSUE TITLE
if config isn't provided, can package.json be used by default?

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#352]
This will make the getting started a bit easier:

> ./node_modules/.bin/steal-tools build --main main --config package.json!npm

Becomes:

> ./node_modules/.bin/steal-tools build --main main

**Comment by matthewp** [comment]
Yes, I would get rid of the need for the --main flag as well so it's just `steal-tools build main`

**Comment by matthewp** [comment]
We might even be able to get rid of `build`.... don't you think building should be the default?  This would make it as easy as running browserify.

**Comment by justinbmeyer** [comment]
Agreed.
