### ISSUE TITLE
Upgrade traceur

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#358]
This bug made it not work in Safari: https://github.com/google/traceur-compiler/issues/1647

**Comment by marshallswain** [comment]
![screen shot 2015-03-22 at 10 45 38 pm](https://cloud.githubusercontent.com/assets/128857/6774420/6c5c8736-d0e5-11e4-8737-078534f8e951.png)
Is this the Safari error I should expect from that error?

And shouldn't switching to babel by putting this in package.json be a workaround for this?:
```json
"system": {
    "transpiler": "babel"
  }
```

**Comment by marshallswain** [comment]
Looks like it IS a workaround to use Babel.  I forgot to check `Disable caches` in the Safari `Develop` menu. Seems like that's default behavior in Chrome.

**Comment by moschel** [comment]
Yes to both questions. Just ran into this myself recently.

On Sunday, March 22, 2015, Marshall Thompson <notifications@github.com>
wrote:

> [image: screen shot 2015-03-22 at 10 45 38 pm]
> <https://cloud.githubusercontent.com/assets/128857/6774420/6c5c8736-d0e5-11e4-8737-078534f8e951.png>
> Is this the Safari error I should expect from that error?
>
> And shouldn't switching to babel by putting this in package.json be a
> workaround for this?:
>
> "system": {
>     "transpiler": "babel"
>   }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stealjs/steal/issues/358#issuecomment-84809893>.
>


-- 

*Brian Moschel*[image: Bitovi]
Development | Training | Support
Bitovi.com <http://www.bitovi.com/> | Twitter: @Bitovi
<http://twitter.com/bitovi>

**Comment by marshallswain** [comment]
@moschel thanks.

**Comment by matthewp** [comment]
Closed by #362
