### ISSUE TITLE
Docs - Quick Start refers to mysterious quick-start folder.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#360]
> # Run in the browser
>  If you installed http-server earlier, navigate to the `quick-start` directory and run the following command to start the server.

Should that be the `BASE` folder?  Or would you rather have it create a `quick-start` folder for the project to begin with?

**Comment by justinbmeyer** [comment]
This is a mistake. It should be the baseUrl folder @cklanak.

**Comment by matthewp** [comment]
Just pushed this out.
