### ISSUE TITLE
Website - Update chat link

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#361]
Since Steal's repo has moved to the StealJS organization on Github, the chat link is dead.
https://gitter.im/bitovi/steal - dead
https://gitter.im/stealjs/steal - ahh... that's better.

**Comment by matthewp** [comment]
Thanks, I fixed it on the homepage but apparently not on the API page.

**Comment by matthewp** [comment]
Whoops, I'll fix this tonight.

**Comment by matthewp** [comment]
This is fixed now.
