### ISSUE TITLE
Better document buildConfig

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#364]
This comes often when people get build errors because of templates. Maybe in the migration guide.

**Comment by marshallswain** [comment]
Isn't this something that a lot more people than those migrating to the new Steal will need?  Why not put it in a guide about working with templates, instead?

**Comment by marshallswain** [comment]
And show those working with other frameworks how to make their template system work.

**Comment by matthewp** [comment]
Actually it already is in the Migrating guide: http://stealjs.com/docs/StealJS.migrating.html

I'm leary about creating guides for CanJS features. Maybe that should be there.

**Comment by marshallswain** [comment]
Eventually there should probably be a "Working with your Framework" section.  Don't we anticipate there being specifics to working with each distinct framework?  I've read through the docs of most frameworks, but I've only built apps with CanJS, so I'm not really the fully-qualified expert on the topic.

**Comment by matthewp** [comment]
Fair point, what other frameworks would that include?

**Comment by marshallswain** [comment]
I'm just imagining Steal being the preferred build tool for the frameworks in this article: http://www.algoworks.com/blog/top-javascript-frameworks-for-app-development.  But I honestly have no idea what optimizations any of them would need.  It seems likely to me that they would each benefit from having a "Using Steal with {{myFramework}} page" at some point in the future.  So what I'm really trying to say is that I think that having a "Using Steal with CanJS" page is a great idea.

**Comment by matthewp** [comment]
@marshallswain I think that would make an excellent article. I'll add it to my list. We're planning to do some hangouts again and go over this sort of thing as well.
