### ISSUE TITLE
Cannot do basic install

### ISSUE THREAD

**Issue by mdrob001** [stealjs/steal#365]
npm install steal --save-dev, npm install steal and npm install steal-tools --save-dev all currently throw a dependency error: 

![image](https://cloud.githubusercontent.com/assets/5870947/6872924/85958ba4-d4a4-11e4-99b8-ad0db801dbab.png)

NPM and node have been updated, the cache has been cleared and the target installation is clean. Please advise if this is a recurring problem and what configuration steps are required to use StealJS.

**Comment by matthewp** [comment]
What is the error? Your screenshot is too small to see.

**Comment by mdrob001** [comment]
Apologies - try now.

**Comment by matthewp** [comment]
It may be because you are using MinGW, I haven't tested with that. Can you try with a normal Windows console?  It's working for me there on Windows 7.

**Comment by matthewp** [comment]
I bet the MinGW version of Git doesn't work with SSH git urls.

**Comment by mdrob001** [comment]
Basic windows command prompt + admin = same result, I'm afraid.

**Comment by matthewp** [comment]
Which version of Windows?  How did you install Git?  Have you tried the Windows version from http://git-scm.com/ ?

**Comment by matthewp** [comment]
@whitecolor have you ever encountered this issue?

**Comment by whitecolor** [comment]
No, I didn't try to clean npm cache:

> npm cache clean

**Comment by matthewp** [comment]
@mdrob001 can you try with 0.8.0, I changed back to `git://` references which is possibly the source if your problem.

**Comment by mdrob001** [comment]
I'll take a look later today - thank you.

On Wed, Apr 8, 2015 at 2:33 AM, Matthew Phillips <notifications@github.com>
wrote:

> @mdrob001 <https://github.com/mdrob001> can you try with 0.8.0, I changed
> back to git:// references which is possibly the source if your problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/stealjs/steal/issues/365#issuecomment-90775288>.
>



-- 
----------------
Daniel Robinson
Web Developer
----------------

**Comment by mdrob001** [comment]
Still no joy, I'm afraid:

[image: Inline image 1]

It's entirely possible from the error log it may be some form of local
environment problem.

I'm going to spin up a sample app on my laptop tonight when I get home to
see if I get the same error.


Thanks for looking at this, in any case.

On Wed, Apr 8, 2015 at 10:33 AM, Daniel R <mdrob001@gmail.com> wrote:

> I'll take a look later today - thank you.
>
> On Wed, Apr 8, 2015 at 2:33 AM, Matthew Phillips <notifications@github.com
> > wrote:
>
>> @mdrob001 <https://github.com/mdrob001> can you try with 0.8.0, I
>> changed back to git:// references which is possibly the source if your
>> problem.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/stealjs/steal/issues/365#issuecomment-90775288>.
>>
>
>
>
> --
> ----------------
> Daniel Robinson
> Web Developer
> ----------------
>
>


-- 
----------------
Daniel Robinson
Web Developer
----------------

**Comment by matthewp** [comment]
Really bums me out that you're having these issues and I can't replicate. Please do let me know how it goes on your own laptop.

**Comment by mdrob001** [comment]
Will do. My gut is telling me it's an environment problem, but I need to make sure it isn't a Windows one. 


Sent from myMail for iOS


Friday, 10 April 2015 14:24 +0100 from Matthew Phillips  <notifications@github.com>:

**Comment by matthewp** [comment]
We no longer have git dependencies.
