### ISSUE TITLE
Development Bundles

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#366]
For something like CanJS, it would be nice to provide a bundle that gets used instead of the individual files. 

It might be nice to support some sort of config that will toggle loading "all" of CanJS in development in a single file.  

Perhaps in CanJS:

```
{
  system: {
    bundle: "can-all.js"
  }
}
```

In a project using CanJS:

```
{
  system: {
    devBundles: ["can"]
  }
}
```

This will speed up load times considerably.

**Comment by matthewp** [comment]
This will be nice for the use-case of wanting to avoid eval as well, you could essentially use bundles of all of your dependencies in dev and if you're using Steal or AMD syntax you could use the CSP build to avoid eval.

**Comment by justinbmeyer** [comment]
Isn't eval avoided now anyways because script injection is used?

**Comment by matthewp** [comment]
Renaming to Development Bundles. Would be a good feature for 1.2 perhaps. I think this has evolved into wanting to create a bundle of all of your node_modules dependencies.

Might need some cooperation with the npm plugin, as likely you would want only the root package.json to be configured, and everything else is assumed to be included in the dev bundle.

**Comment by matthewp** [comment]
Throwing out an API:

```js
stealTools.bundle({}, {
  filter: "node_modules/**/*",
  dest: __dirname + "/dev-bundle.js" // the default maybe
});
```

```html
<script src="node_modules/steal/steal.js" dev-bundle></script>
```

**Comment by justinbmeyer** [comment]
```
steal-tools bundle --dev
```

**Comment by pYr0x** [comment]
i like justin's more.
i think we should more focus on comandline tools.
i like that much more then have another stealtools api that you have to call with node

**Comment by matthewp** [comment]
Usually a cli tool is backed by a Node API. The same way that you can do `steal-tools build` and that internally calls `stealTools.build({} ...`, the same would be true of a `bundle` command.

**Comment by pYr0x** [comment]
i know. but i think we should not make the `bundle` api public. we should provide a way to use steal. today we have many ways to do a build or a export or a transform. 
e.g. normal API, stream API, cli
i think for `bundle` we need no much configuration so we can hide the api and let users use the cli comand

**Comment by justinbmeyer** [comment]
@pYr0x I think we should make every reasonable APIs public.  We don't know how people might mash up various steal APIs to get their build working.

We can promote the `cli` tools if you think it will attract new users, but I think people are better served with these sorts of APIs documented.

**Comment by pYr0x** [comment]
i always get overwhelmed if i will learn new program and there are many different ways to reach the goal.
i didnt see a clear structure.
i think we should lead people to use the correct way (easiest way) to get the desired goal.

i think many APIs (for the same thing) will confuse people.

_maybe i will confuse only me...._

**Comment by matthewp** [comment]
Since we already have the convention of having a cli that is backed by a Node API (with build and export) let's continue this for now. If we want to discuss big changes like changing our API structure we should do that in the form of an RFC: https://github.com/stealjs/rfcs

**Comment by m-mujica** [comment]
@matthewp about the proposed api, my first rough version is using the same API as `stealTools.build` having the `config` option allows me to use it to build the graph (same way the multi build does)

Is there any reason why we don't want to do?

```
stealTools.bundle({
  config: path.join(__dirname, "package.json!npm")
}, {
  dest: path.join(__dirname, "dev-bundle.js")
});
```

without config, how do we build the graph? we'd only have "options.filter" to do that, am I right?

**Comment by matthewp** [comment]
```
var globPath = loader.baseURL + "node_modules/**/*";
if(isGlobMatch(globPath, load.address);
```

**Comment by m-mujica** [comment]
One thing I found out testing this with PMO is, steal-tools won't add plugins like `done-autorender` to the bundles.

Steal will fail to load [PMO's main](https://github.com/donejs/place-my-order/blob/master/package.json#L30) because of that; I think it makes sense for a dev bundle to include plugins? or maybe we only want to add `exports.includeInBuild = true` to some of them? 

thoughts @matthewp? 

I'll work on getting those plugins in the bundle only for this use case in the meantime.

**Comment by matthewp** [comment]
I think the write bundle stream is what removes them.  I think that should be configurable some how (maybe as part of the stream's api).

**Comment by m-mujica** [comment]
It happens in the [`concat stream`](https://github.com/stealjs/steal-tools/blob/ca6ad2104bd9074b4a8f1d8cc2c6c088c376f179/lib/bundle/concat_source.js#L28), I can probably just make sure the flag in `load.metadata` is set by the `dev_bundle` stream... Which I think it's just what you said..

I like to repeat stuff for myself (if you were wondering =P)

**Comment by m-mujica** [comment]
- [x] Make steal-tools create a JS/CSS dev bundle 
- [x] Add `steal-tools bundle` command to CLI
- [ ] Add option to make Steal load the dev-bundle automatically
- [ ] Prevent Steal to load package.json of dependencies when dev-bundle is loaded
- [ ] Add documentation

**Comment by matthewp** [comment]
To release:

* [ ] - Release steal 1.3
* [ ] - Update steal-tools to point to steal 1.3
* [ ] - Release steal-tools 1.2
* [ ] - Update each "releases"
* [ ] - Update the website

**Comment by matthewp** [comment]
This is available in https://github.com/stealjs/steal/releases/tag/v1.3.0
