### ISSUE TITLE
link to release article

### ISSUE THREAD

**Issue by moschel** [stealjs/steal#369]
Include a link to http://blog.bitovi.com/introducing-stealjs/ somewhere on the homepage or the nav. That article has a lot more "why stealJS" information than just the videos alone.

Maybe just make "Why StealJS" a link to that article.

**Comment by justinbmeyer** [comment]
Instead, just move the article's content to: http://stealjs.com/docs/StealJS.why.html.  This way, it can be updated as the tech changes.

**Comment by matthewp** [comment]
Thanks, I've made the article the Why guide, will update with references to Watch Mode and Live Reload and other future features.
