### ISSUE TITLE
Webworkers and StealJS

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#384]
I would like to be able to use StealJS in a webworker scenario. 

I'd like to have steal import a module in one step like:

```
var worker = new Worker(System.stealPath+"?main=webworkers/worker");
module.exports = worker;
```

This means making 2 changes:

1.  Provide a `System.stealPath` that represents where the `steal.js` file is located.  We already set this, but the value doesn't show up on `System`
2.  If steal.js is loaded in a webworker, it should parse the [location](https://developer.mozilla.org/en-US/docs/Web/API/Location)'s `search` for configuration options.

I think this is an easy change, but will make it possible to quickly load modules in a worker-thread.

**Comment by BigAB** [comment]
:+1:

**Comment by matthewp** [comment]
Closed by #386

**Comment by justinbmeyer** [comment]
@matthewp Should this be documented?  Maybe reopen until then?

**Comment by matthewp** [comment]
Sure, where would you document this?

**Comment by matthewp** [comment]
This just needs to be documented now, free for anyone who wants to do it.

**Comment by justinbmeyer** [comment]
open for docs, but un assigning myself

**Comment by matthewp** [comment]
I'm not a fan of this API and think we should hold off documenting until we can find a better one.  It will continue to work this way, of course.
