### ISSUE TITLE
meta.deps only works on global format

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#390]
This is probably something to take up with SystemJS.

Also, for some reason, CanJS is configuring jQuery as the global format.

**Comment by justinbmeyer** [comment]
I NEVER LEARED TO READ!!!!

**Comment by justinbmeyer** [comment]
closed the wrong issue.

**Comment by matthewp** [comment]
I know AMD used to work because this is how samsclub's template dependencies were added prior to can-import.  I'll fix this tomorrow.  If systemjs isn't interested in keeping this feature we can look into alternatives (maybe having a hook that pre-imports meta.deps for example).

**Comment by matthewp** [comment]
```js
var instantiate = System.instantiate;
System.instantiate = function(load){
  var promise = Promise.resolve(instantiate.call(this, load));

  if(load.metadata.format !== "es6" && load.metadata.format !== "global") {
    return promise.then(function(instantiateResult){
      instantiateResult.deps = instantiateResult.deps.concat(load.metadata.deps);
      return instantiateResult;
    });
  }
  return promise;
};
```

**Comment by matthewp** [comment]
This is probably not going to be fixed, modules should import their dependencies directly. Modules that don't are broken, I don't want to make Steal more complicated to workaround broken modules.
