### ISSUE TITLE
Document @loader module

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#391]
This is useful, especially in configuration.

**Comment by matthewp** [comment]
Documented here: http://stealjs.com/docs/@loader.html. Anything missing?

**Comment by justinbmeyer** [comment]
I NEVER LEARED TO READ!!!!

**Comment by stevenvachon** [comment]
![oscar-clip](https://cloud.githubusercontent.com/assets/170197/7128283/ed834554-e21d-11e4-8a25-1fb239a37ac8.gif)
