### ISSUE TITLE
configDependencies can overwrite package.json data

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#392]
Ideally, I would like to be able to do:

```js
// package.json
system: {
  configDependencies: ["system-config"]
}
```

```js
// system-config.js
var MySystem = require('@loader');
var toBeExported = {};
if(MySystem.env === "development" && typeof window === "undefined") {
    toBeExported = {
		meta: {
			'jquery': {
				"format": "global",
				"exports": "jQuery",
				"deps": ["can/util/vdom/vdom"]
			}
		}
	});
}
module.exports = toBeExported;
```

This would make "vdom" a dependency of "jquery" when there is no dom.

Also, I would like this to be run through the normal "converter" logic that changes "jquery" to 'jquery@1.11.2#dist/jquery'.

Eventually, conditional loading can do away with this for modules that we have control over, but this will still be needed for things like jQuery.

**Comment by matthewp** [comment]
> Eventually, conditional loading can do away with this for modules that we have control over, but this will still be needed for things like jQuery.

It could be part of config:

```json
{
  "name": "my-package",
  "main": "main",
  "system": {
    "meta": {
      "jquery": {
        deps: [ "document-#{runtime}" ]
      }
    }
  }
}
```

This might load `document-node` in Node and `document-browser` in the browser.

**Comment by matthewp** [comment]
This will be in 0.9.0.  Instead of `module.exports` use `exports.systemConfig`, this prevents locking us into having the default export for an extension be for configuration. Plus I think there are better long-term solutions to this problem.  But for now https://github.com/stealjs/system-npm/pull/56 allows you to do this.
