### ISSUE TITLE
Imported ES6 module does not have __esModule flag.

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#405]
In the following app:
https://github.com/ilyavf/bug-dep-load/releases/tag/bug-esmodule-flag

The imported module 'appstate' has the __esModule flag if its imported inside index.js.
But it lacks the flag if its imported inside another module:
https://github.com/ilyavf/bug-dep-load/blob/df5606de43acdfa2a7d3c632dcf31de1f5169745/dist/bundles/components/page1.js#L11

See line 11: _componentsAppstate does not have __esModule flag.

**Comment by ilyavf** [comment]
This issue happens in stealjs 0.8.4, but it does not happen in 0.7.1 where the flag is defined.

**Comment by matthewp** [comment]
This is an upstream bug, there is a current fix for it so I'm going to try pulling it down.

**Comment by matthewp** [comment]
I pulled it down and your demo app works with it. Thanks for finding this bug. This will go out with 0.10.0
