### ISSUE TITLE
How to debug StealJS with IE 11 and Firefox 36?

### ISSUE THREAD

**Issue by tschoening** [stealjs/steal#419]
Some weeks ago I've run into some problems debugging a web app using StealJS and asked for ideas on stackoverflow, without any results. Now it seems I'm not the only one running into my issue so I would like to ask here again. Thanks for any input...

http://stackoverflow.com/questions/28903864/how-to-debug-stealjs-with-ie-11-and-firefox-36

> I use the minor tag of StealJS to load my JS files and everything seems to work, but today I
> recognized that I'm simply unable to debug my code in IE 11 and Firefox 36. Until now I only used
> the new Opera based on Chrome/Blink, currently version 27, which works pretty well regarding
> debugging. But:

> Firefox's built in dev tools don't show my JS files at all. They only show steal.js and directly
> afterwards a greyed out line called "evals" with two additionals lines of two JS libs I use and export
> in stealconfig.js.

> Firefox's Firebug shows my files and I can set breakpoints, but there seems to be some errors,
> because if I set/unset the breakpoint there's a little animation shown which never finishes. If I
> reload the page the usual breakpoint icon, a red circle, is shown, so it looks like the breakpoint has
> been set successfully, but the code simply doesn't stop on the breakpoint. But it is run, because
> the functionality implemented at the break point is usable.

> In IE 11 my JS files are shown in the "dynamic scripts" tree and I can set breakpoints as well, but
> everytime I reload the current page the icon for the breakpoint changes and gets some defect
> triangle with a warning sign, just like the breakpoint won't work anymore or such. And of course IE
> doesn't stop the code as well after I reload the page and if I open my JS file the breakpoint is not
> shown anymore, which at least works in Firefox's Firebug.

> None of those problems happen in Opera/Chrome, I always see all my files, can set breakpoints
> and the code stops as expected. Additionally all browsers show individual requests for my JS file,
> nothing is bundled into one big one or such, it's all independent files during development.

> So is StealJS and how it loads files simply incompatible with the other browsers? Do they need to
> add support for how Steal handles file loading? I used a former version of Steal with
> JavaScriptMVC and none of these problems occured with that version.

**Comment by matthewp** [comment]
Hey, I feel your frustration. Firefox has issues with with content that has been evaled and doesn't treat it like it treats files that are added through the script tag. There are several open bugs about this on their bug tracker.  But the good news is that they have been fixing some of them lately so I think this will all get worked out with time.  If you want to help out grab es6-module-loader (a project Steal builds on) and create some demos of it not working and submit bugs to firefox.  I've been wanting to do this myself but haven't had time recently.  https://github.com/ModuleLoader/es6-module-loader

**Comment by tschoening** [comment]
Thanks for the info that those most likely are browser bugs and I'm not necessarily doing something wrong. I hope I find some time to report bugs to Mozilla...
