### ISSUE TITLE
Problem loading library through npm

### ISSUE THREAD

**Issue by dylanrtt** [stealjs/steal#425]
I am having trouble loading the jquery [datatables](https://github.com/DataTables/DataTables/blob/master/media/js/jquery.dataTables.js#L34) plugin into my app. Datatables uses amd and defines itself as "datatables", depending solely on "jquery".

Here is basically my app:

index.html:
```html
<script src="node_modules/steal/steal.js" main="main"></script>
```

main.js:
```js
import jquery from "jquery";
import datatables from "datatables";

// function undefined undefined
console.log(typeof jquery, typeof datatables, typeof jquery.fn.dataTable);
```

package.json:
```js
{
  "dependencies": {
    "datatables": "^1.10.7",
    "jquery": ">1.9.0",
    "steal": "^0.10.0"
  },
  "system": {
    "meta": {
        "datatables": {
            "format": "amd"
        }
    }
  }
}
```

The presence of that ```meta``` seems to have no effect.

**The problem** is seen when you breakpoint the datatables code; it defines the "datatables" module but the callback is never executed. I am unclear as to whether there is supposed to be some additional setup to get something like this working.

I did manage to get a successful workaround going with the ```steal("datatables")``` syntax, but I have to modify the ```system``` config as follows:

```js
"npmIgnore": {
    "datatables": true
},
"map": {
    "datatables/datatables": "datatables"
},
"paths": {
    "jquery": "node_modules/jquery/dist/jquery.js",
    "datatables": "node_modules/datatables/media/js/jquery.dataTables.js"
},
```

**Comment by matthewp** [comment]
Good news! This works now. Sorry for not responding before now. 

I created a test with steal@rc and it's working now, not sure what changed, but hooray! https://gist.github.com/matthewp/91000f55567b4512fb6db93c4d43f5a4
