### ISSUE TITLE
Cannot override an existing "ext" with package.json config

### ISSUE THREAD

**Issue by dylanrtt** [stealjs/steal#426]
Using the bower.json config, I am able to force the "mustache" file extension use the "stache" renderer, but this no longer works when I switch to package.json. Instead, it simply uses mustache renderer, or at least I'm assuming it's using mustache since mustache helpers work and stache helpers don't.

``` js
"ext": {
  "mustache": "can/view/stache/system"
}
```

I can only get it to work with file extensions that have not already been defined such as "foo.stache!bar"  if I define "bar". Since "mustache" is already defined in the canjs package.json, that may be why my config above has no effect.

Yes, I could just rename all of my *.mustache files and references to *.stache, but there are 356 of them and I would rather not deal with the conflicts of my coworkers and feature branches at this time.

**Comment by matthewp** [comment]
Thanks for reporting, probably the issue is that your configuration is applied first, then dependent package's configuration.  I'll look into what is needed to fix this.

**Comment by ccummings** [comment]
+1 I just encountered this myself while trying to specify a different handler for stache files.

I traced it to [L296](https://github.com/stealjs/steal/blob/master/ext/npm.js#L296) of the npm extension. There, any package with a system config will overwrite any previous system config.

My project's package.json is read first which sets `ext.stache` but then can's is read and my config is blown away.

**Comment by matthewp** [comment]
Yeah, I think we need to use unshift instead of push here: https://github.com/stealjs/steal/blob/master/ext/npm.js#L53

That would cause the packages to be translated in the correct order (i think).

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-npm #185](https://github.com/stealjs/steal-npm/issues/185) via [**ZenHub**](https://www.zenhub.com/)

**Comment by donkeybanana** [comment]
Following up my comment at https://github.com/stealjs/steal-npm/issues/185#issuecomment-326802040 here, as I noticed that project has been folded into this one.

Sorry to bump this issue, but I can currently reproduce the issue with `steal@1.5.13` using the following `package.json`:

```
{
  "name": "steal-ext-override",
  "version": "1.0.0",
  "description": "https://github.com/stealjs/steal-npm/issues/185",
  "main": "index.js",
  "steal": {
    "ext": {
      "ejs": "can-ejs"
    }
  },
  "devDependencies": {
    "can-ejs": "^3.1.5",
    "steal": "^1.5.13"
  }
}
```

In the browser:

```
> steal.config('ext')['ejs']
< "./src/system.js"
```

**Comment by pYr0x** [comment]
@donkeybanana 
so there are 2 or more problems, but steal works fine.

1. can-ejs is not steal 1.x ready. you can workaround this.
2. can-ejs need some changes that it would not throw an error on https://github.com/canjs/can-ejs/blob/master/system.js#L7
3. for a custom extension you two things. 
 - the `ext` config should be configured on the steal plugin like https://github.com/canjs/steal-stache/blob/master/package.json#L48 and 
- **you** should add a `plugin` to your app like https://stealjs.com/docs/npm.html#packagestealplugins

now to the workaround:
1. the steal config on `can-ejs` should be
```json
"steal": {
    "main": "can-ejs",
    "ext": {
      "ejs": "can-ejs/system.js"
    },
    "plugins": [
      "can-ejs"
    ],
    "configDependencies": [
      "live-reload"
    ],
    "npmIgnore": [
      "documentjs",
      "testee",
      "generator-donejs",
      "donejs-cli",
      "steal-tools"
    ]
  },
```
2.  the `can-ejs/system.js` should be
```js
import EJS from "./can-ejs";

function translate(load) {
	debugger;
	return "define(['can-ejs'],function(module){" +
		"var EJS = module.default || module;" +
		'return EJS(function(_CONTEXT,_VIEW) { ' + new EJS({
			text: load.source,
			name: load.name
		})
		.template.out + ' })' +
		"})";
}

export default {
	translate: translate
};
```
3. you should add the plugin config to your `package.json`
```json
"plugins": [
      "can-ejs"
    ]
```

**Comment by matthewp** [comment]
Thanks for taking this on @pYr0x !

**Comment by donkeybanana** [comment]
Thanks @pYr0x for the extensive example.
