### ISSUE TITLE
Document how to use JSX with babel

### ISSUE THREAD

**Issue by omerts** [stealjs/steal#428]
Hello,

I am using babel as my transpiler, but jsx is throwing an error.

**Comment by omerts** [comment]
Ok got the answer from @matthewp at gitter, in order to use jsx we need to add the following config to package.json:
```javascript
"system": {
    "transpiler": "babel",
    "babelOptions": {
      "blacklist": []
    }
```

**Comment by matthewp** [comment]
You could also optionally use a plugin like https://github.com/floatdrop/plugin-jsx

Let's keep this open because it needs to be documented.

**Comment by matthewp** [comment]
This is not needed in 1.0, so docs won't be added.
