### ISSUE TITLE
transpiler config in package.json has weird effect

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#433]
i am testing stealjs.
i have created a steal environment by doing step by step http://blog.bitovi.com/using-canjs-2-2-with-stealjs/ 

if the article says, "Steal will now automatically load its configuration from the package.json we initialized"
i want to change the transpiler to traceur. so my package.json look like this:
```
{
  "name": "steal-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "can": "^2.3.0-pre.1",
    "jquery": "^2.1.4",
    "steal": "^0.10.5"
  },
  "system": {
    "config": {
      "transpiler": "traceur"
    }
  }
}
```
now it loads traceur, but didnt find jquery anymore!

if i changed to babel, traceur is still loading...

**Comment by matthewp** [comment]
You don't need a config object in package.json. in fact we should disallow it as it will cause strange effects.

You can put all configuration directly in the system object. So tranpiler goes in system.tranpiler.

**Comment by matthewp** [comment]
Also, you probably want can 2.2.x, 2.3.0-per has some cool stuff but is experimental.

**Comment by pYr0x** [comment]
i tried also
```
{
  "name": "steal-test",
  "version": "1.0.0",
  "description": "",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "can": "^2.3.0-pre.1",
    "jquery": "^2.1.4",
    "steal": "^0.10.5"
  },
  "system": {
      "transpiler": "traceur"
  }
}
```

but with this config, traceur will not loaded as transpiler

**Comment by matthewp** [comment]
Traceur is the default... what is it you expect to happen? If you write es6 code it should be transpiled on the fly and load your code.

Maybe try out the example app: https://github.com/canjs/steal-can-example

**Comment by pYr0x** [comment]
if i do it the same way as daffl wrote ... babel is the default transpiler...
it seems the package.json has no effect for the transpiler, neither with system.config.transpiler or system.transpiler

**Comment by matthewp** [comment]
I think it is because you are using can 2.3.0-pre.1 which has a dependency that uses babel for its build.  If you use 2.x you shouldn't have this problem.  But this is a bug, your transpiler setting should override your dependencies.

**Comment by pYr0x** [comment]
ok... if you have fix this, you can close the issue

**Comment by matthewp** [comment]
Let's leave it open for now

**Comment by justinbmeyer** [comment]
@matthewp 

> can 2.3.0-pre.1 which has a dependency that uses babel for its build

What dependency?

**Comment by matthewp** [comment]
can-simple-dom

**Comment by matthewp** [comment]
I think this is the same bug as #426

**Comment by isadovskiy** [comment]
Same issue is here

**Comment by pYr0x** [comment]
close this.
with steal 1.0 babel will be the default transpiler.
