### ISSUE TITLE
A bundle with only 1 define causes factory to be called twice

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#437]
can be seen in test result for:
https://github.com/whitecolor/steal-pack-bundles

https://github.com/stealjs/steal-tools/issues/261

**Comment by pYr0x** [comment]
does this issue still exists? can you give us a feedback. pls test with steal 1.0 pre release

**Comment by matthewp** [comment]
It doesn't still exist, there's a test in steal-tools.
