### ISSUE TITLE
if missing a @config module in package, provide a warning.

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#439]
DocumentJS fails if you don't provide a data-config on a page like:

```
data-config="./static/config.js"
```

This seems to be a problem with the bundles plugin not being able to notice that the bundle that it is looking for has never resolved.

**Comment by justinbmeyer** [comment]
To reproduce this, you can run documentjs in can-connect's gh-pages branch.

**Comment by matthewp** [comment]
I'm going to close this as I don't think this is still an issue. There is a larger issue though, with what should happen when a module is not in a bundle in production.
