### ISSUE TITLE
MooTools-More draggable class broken with Steal >= 0.4

### ISSUE THREAD

**Issue by tracer99** [stealjs/steal#443]
As of steal 0.4, the draggable class for MooTools-More is broken.
The global event binding in mootools that handles click bindings never picks up the click release (any draggable object stays draggable even after click is released) This was not an issue with steal 0.3
I've just upgraded to 0.10.5 and it's still an issue.

I can create an example project showcasing this if needed.

**Comment by tracer99** [comment]
I cannot reproduce this now as a stand alone issue. Will try with CanJS installed, but am killing this as I don't think it's steal specific.

**Comment by matthewp** [comment]
Let me know i you can recreate it, IIRC Mootools uses globals in a way that most module loaders don't support but we should.
