### ISSUE TITLE
Root bowerIgnore should be persisted when parsing dependent bower.json

### ISSUE THREAD

**Issue by jcavanagh** [stealjs/steal#445]
When using the bowerIgnore feature, bad bower.json requests still occur if a bower dependency also references the ignored dependency in their own bower.json file.  

This seems to happen because the bower plugin reads each bower.json individually, and it's obviously not going to find a system.bowerIgnore section in a dependency's bower.json.  So, it seems the bower plugin should apply the root bowerIgnore all the way down the dependency chain as well.

**Comment by matthewp** [comment]
I think I understand what you are saying.  Let me know if this is correct:

### root bower.json
```json
{
  "dependencies": {
    "a": "0.0.1",
    "b": "0.0.1"
  },
  "system": {
     "bowerIgnore": ["b"]
  }
}
```

### a bower.json
```json
{
  "dependencies": {
    "b": "0.0.1"
  }
}
```

b's bower.json will still be fetched.  Is this the problem you are describing?

**Comment by jcavanagh** [comment]
Yes, indeed - that is correct.

**Comment by matthewp** [comment]
Issue moved to [stealjs/system-bower #25](https://github.com/stealjs/system-bower/issues/25) via [**ZenHub**](https://www.zenhub.com/)
