### ISSUE TITLE
Steal tries to load internal file`s dependencies if 'require' method is used within that file

### ISSUE THREAD

**Issue by gorokhovvs** [stealjs/steal#447]
I`m not sure if it is a bug or an expected Steal behavior but it occurs when I try to load https://github.com/mbraak/jqTree/blob/master/tree.jquery.js using steal. This plugin has its own internal require method to include dependencies. All the dependencies are within tree.jquery.js. StealJS looks for that dependecies according to defined paths like "node_module = require('./node')" and tries to load them as separate files. Do you have any suggestion how can I make steal to avoid that deps to be loaded?

**Comment by matthewp** [comment]
In your config:

```json
{
  "meta": {
    "tree.jquery": {
      "format": "global"
    }
  }
}
```

**Comment by gorokhovvs** [comment]
Yeah, that works, thanks a lot!!!
