### ISSUE TITLE
process doesn not have a member 'platform'

### ISSUE THREAD

**Issue by andrecgn** [stealjs/steal#448]
https://github.com/stealjs/steal/blob/master/steal.js#L2528

The regex-match fails since the process object does not necessarily have a platform member. That however is not made sure of before calling a method on that member.

**Comment by matthewp** [comment]
Thanks, what scenario would there be a process without a platform?  Just curious.

**Comment by andrecgn** [comment]
Matthew, I'm getting an exception in the browser, using steal.production.js to load the distribution bundles. In dev everything is fine, but in production I get an exception (TypeError: Cannot read property 'match' of undefined)

**Comment by matthewp** [comment]
I've seen people have this issue, but I don't think it's a steal bug. It's caused when they have configuration that causes Steal to load twice. If you can provide more info I can look into improving the docs on this.
