### ISSUE TITLE
Visual Studio 2015 Integration

### ISSUE THREAD

**Issue by varghesep** [stealjs/steal#449]
I'm very interested to see an example that explains how to integrate **stealjs** with **ASP.NET MVC6, gulp, bower, babel and react** and run the app on **IIS Express** like it exists on a production server.

An ASP.NET MVC6 application can be created with [Visual Studio 2015 Community Edition](https://www.visualstudio.com/downloads/download-visual-studio-vs). Using a gulpfile.js, the compilation can be done. This is important because, in production it is better to use the compiled JS files rather than using JSX to compile every time.

**Comment by matthewp** [comment]
Thanks, if you would like to write something up like this I could guide you.  I don't use Visual Studio but understand there is a big crowd that does, so more than happy to help guide you with this.  Steal works well with all of the technologies listed.  The only tricky bit might be about the IIS server integration, as you'll need to switch your <script> tag to run in production and I'm not sure how that's usually done in the .NET world.

**Comment by varghesep** [comment]
Just like the **public** folder in node.js, there is a **wwwroot** created by Visual Studio where all the static files lives. I think it is needed only to compile all the JSX files and drop in the **wwwroot** folder. There is nothing else we have to do in IIS to run the app except setup the virtual directory which is normal, or do anything for the **script** tag. When I said **IIS Express**, I meant there should not be any dependency on node server. The challenge I had with a test project I tried was to put all the different frameworks together in gulp.js.

After a project is compiled successfully, it can be published directly from Visual Studio to Azure. This can work from the local machine. The other ways are (1) push to github of Azure which would then compile and deploy (2) check-in to Visual Studio online and it compiles and deploy it.

I will create a repo in github and work with you to integrate steal.js.

**Comment by matthewp** [comment]
I would use NPM rather than Bower.  There's really no good reason to choose Bower.  NPM has a better contract so you run into fewer issues.  Anyways, glad to help guide you with this.

**Comment by varghesep** [comment]
I created a git repo called https://github.com/varghesep/azure-aspnet5-react-stealjs . I will create an asp.net application and make sure it works on windows before you clone and making changes.

**Comment by matthewp** [comment]
Issue moved to [stealjs/rfcs #2](https://github.com/stealjs/rfcs/issues/2) via [**ZenHub**](https://www.zenhub.com/)
