### ISSUE TITLE
Can not make partials included with {{>}} helper to be loaded from JS bundle.

### ISSUE THREAD

**Issue by gorokhovvs** [stealjs/steal#453]
I` ve included several partials using {{>}} helper and I expected that the partials will be bundled into minified JS file and will be loaded from there. Also I tried to load them with steal as a dependency and I see that partials exist within bundle, but in any cases in production mode steal looks for those partials outside the bundle. Is that expected behavior and how can I make steal to look for {{>}} partials within a bundle?

**Comment by matthewp** [comment]
the `{{> }}` syntax doesn't work with the new Steal, only the legacy version.  In CanJS 2.3 you'll be able to use can-import with partials which works with new Steal, it will be something like:

```handlebars
<can-import from="some/partial" #partial={value} />

{{> partial}}
```

For now you can import the partial in your javascript and give it a name so it can be used:

```js
steal('some/partial.stache!", function(partial){
  can.view.preload("my-partial", partial);
});
```

```handlebars
{{> my-partial}}
```

**Comment by gorokhovvs** [comment]
Thanks!
