### ISSUE TITLE
Support wilcard for npmIgnore

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#456]
It would be nice if one could just do for example `npmIgnore: ['gulp*', 'grunt*']` so it would exclude all gulp and grunt plugins.

**Comment by whitecolor** [comment]
What about it, it should be very simple.

**Comment by matthewp** [comment]
I'm all for it but don't have the bandwidth to work on it right now.  PR welcome though. Just need to detect the * and turn it into a regex.

**Comment by whitecolor** [comment]
@matthewp why is steal crawling all the pagckages in package.json regardles of requires met while loading? Why not check particular if package `module` in package.json when `require('module')` (`import from 'module/...'`) is met, and the resolve it as npm module?

**Comment by matthewp** [comment]
That's a known issue https://github.com/stealjs/system-npm/issues/41

**Comment by whitecolor** [comment]
+1

**Comment by matthewp** [comment]
Planned for 1.1.0 as part of the plugin stuff (adding glob support there).

**Comment by matthewp** [comment]
We progressively fetch package.jsons now.
