### ISSUE TITLE
Callback's arguments of steal.import() with multiple dependencies 

### ISSUE THREAD

**Issue by isadovskiy** [stealjs/steal#457]
steal.import() with multiple dependencies got resolved with the single argument, contained the array of dependencies: http://take.ms/9OOB9

steal.import('dep1', 'dep2').then(function (deps) {
   console.log(dep[0]);
   console.log(dep[1]);
});

As I understand, this comes from deferred API. However it's not convenient. Is there a way to unwrap it somehow to have several separate arguments inside callback handler (one per each dependency)? promise.done() works in such way in jQuery.

Desired:

steal.import('dep1', 'dep2').then(function (dep1, dep2) {
   console.log(dep1);
   console.log(dep2);
});

**Comment by matthewp** [comment]
There's not, the Promise api specifies only a single return value, that's why it's an array (this is how Promise.all works as well).

jQuery is updating their promise implementation to conform to the spec so it too with have a single argument in 3.0 I believe.

**Comment by matthewp** [comment]
However this becomes a bit easier with ES6 syntax (array destructuring), you could do:

```js
steal.import('dep1', 'dep2').then(function ([ dep1, dep2 ]) {

});
```

Which to me is about as nice.

**Comment by matthewp** [comment]
This is a bit of a hidden feature but you can put code inside of the steal script tag like so:

```html
<script src="steal.js">

  import dep1 from "dep1";
  import dep2 from "dep2";

</script>
```

This will wait until after your app is loaded and then run.  Might be the use case for you.  Works with steal, amd, commonjs, and es6 syntax.

**Comment by isadovskiy** [comment]
Thanks for the update, @matthewp! I think you can close the ticket.
