### ISSUE TITLE
Web site: rename API menu to Doc or Guides

### ISSUE THREAD

**Issue by PhiLhoSoft** [stealjs/steal#461]
The first time I went to the (nice) StealJS site, I saw base instructions, links to videos (I don't look at them in general) and some GitHub status display. I looked for documentation, only saw "API", thought "another tool / library exposing an API without showing how to use it".

I finally went to this link, and saw there are some nicely looking tutorials (haven't read them yet!).
Hence this suggestion: rename this menu to be less confusing / misleading. :smile: 

Thanks. Looks like an interesting project.

**Comment by PhiLhoSoft** [comment]
Moreover, the links in the second bullet point section are broken. Apparently, you have added the `section_` prefix to these names. And the _Easy workflows_ section has nothing to read, only a video. I cannot "read" them on my phone.

**Comment by matthewp** [comment]
We're going to stay with API.
