### ISSUE TITLE
Put compatible plugin logos on the home page

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#468]
In a presentation today, some plugins were shown that I was unaware of.  We should get some logos on the home page similar to how feathersjs.com does it.  See the section on their website under "Feathers Plays Nicely With Your Favorite Stack"

- [x] React: https://github.com/stealjs/react-example
- [ ] Angular https://github.com/Hypercubed/angular-stealjs
- [x] Angular2: https://github.com/stealjs/steal-angular2-example.
- [x] DoneJS: https://donejs.com/Apis.html#section=section_StealJS
- [x] VueJS: https://github.com/stealjs/vuejs-example
- [x] CanJS standalone?
- [ ] Backbone: 
- [x] CoffeeScript: https://www.npmjs.com/package/steal-coffee
- [x] Less: https://www.npmjs.com/package/steal-less
- [x] Sass: https://www.npmjs.com/package/steal-sass
- [x] npm: https://github.com/stealjs/system-npm
- [x] Cordova: https://www.npmjs.com/package/steal-cordova
- [ ] Stylus: https://github.com/maael/steal-stylus (WIP)
- [ ] [Update CanJS example to not use done-autorender](https://github.com/stealjs/steal-canjs-example/issues/2)

**Comment by marshallswain** [comment]
Do we have an Angular example somewhere?

**Comment by justinbmeyer** [comment]
Really good idea!

**Comment by marshallswain** [comment]
Here's what I was thinking for the stealjs.com home page:

![steal com update](https://cloud.githubusercontent.com/assets/128857/15310930/6f36381c-1bb2-11e6-9ba2-e6592714a13a.jpg)

**Comment by marshallswain** [comment]
Here's the [animation for the plugins section](https://dl.dropboxusercontent.com/spa/ydjvegh41zzxi0k/Exports/StealJS%20Plugins%20Animation/StealJS%20Plugins%20Animation.html)

**Comment by matthewp** [comment]
Wow this looks really sharp! How ready is this?

**Comment by marshallswain** [comment]
We don't have a Vue.js example or an Angular example, yet.  The Angular link in the 1st comment is a WIP.  The logos and animation are ready.  I just need to put them into the html.

**Comment by matthewp** [comment]
An Angular 2 example might be hard, I'm not sure if it loads in Steal yet, it didn't last I tried.

**Comment by marshallswain** [comment]
I made a VueJS example here: https://github.com/stealjs/vuejs-example

**Comment by moschel** [comment]
+1 love the mockup

**Comment by pYr0x** [comment]
i would remove the "sass" icon. the steal-sass plugin is really out-of-date.
much parts you can do with your less plugin doesnt work with the sass plugin. e.g. livereload, import with "locate://" and so one...

**Comment by marshallswain** [comment]
@pYr0x Oh good to know.  I'll remove that.

**Comment by marshallswain** [comment]
I just created a standalone example for CanJS.  I'm adding CanJS to the frameworks between DoneJS and React.

https://github.com/stealjs/steal-canjs-example

**Comment by marshallswain** [comment]
Actually, I'm inclined to leave Sass in there if it even works for the basics.  We can update the steal-sass README.md to be clear on what works and what doesn't.  We might be more likely to get somebody to champion it.

**Comment by matthewp** [comment]
Yeah I agree, include it.

**Comment by marshallswain** [comment]
I got an Angular2 example working: https://github.com/stealjs/steal-angular2-example.

**Comment by pYr0x** [comment]
@marshallswain very nice.

should we use in the canjs app `done-autorender` or should we use a npm-way like here: https://github.com/pYr0x/testapp/blob/master/dev.html#L7
and add the template to a given `div`
https://github.com/pYr0x/testapp/blob/master/src/app.js#L25

**Comment by matthewp** [comment]
Awesome @marshallswain, I'm slightly surprised it's working, but very happy about it.

@pYr0x I think using done-autorender is a little overkill. There's still a lot of people that use canjs but not all of DoneJS so it might be confusing to them.

**Comment by pYr0x** [comment]
@matthewp i agree

**Comment by marshallswain** [comment]
I used done-autorender for the live-reload setup.   @matthewp maybe you can help me do the same as here: https://github.com/donejs/autorender/blob/master/src/autorender.js#L30

**Comment by matthewp** [comment]
@marshallswain That complexity is not needed in this case, it's needed there because that's a plugin.  In your case it's as simple as:

```js
import reload from "live-reload";

reload(render);

var state = new AppState( ..);

function render(){
  $("body").html(renderer(state));
}

render();
```

ping me if you want to pair on it.

**Comment by matthewp** [comment]
There's a typical example at the bottom of the docs: http://stealjs.com/docs/steal.live-reload.html

**Comment by pYr0x** [comment]
@matthewp i did that in https://github.com/pYr0x/testapp/blob/master/src/app.js#L24-L27
but correct my if i am wrong. this does not HMR?

**Comment by matthewp** [comment]
@pYr0x you still have to run the live-reload server `steal-tools live-reload`, but if you uncomment out the parts that are currently commented out it should work.

**Comment by matthewp** [comment]
I'm thinking we should remove the videos from the homepage. They are already on http://stealjs.com/docs/StealJS.why.html, I wonder how often they are played from the homepage.

**Comment by marshallswain** [comment]
This is ready for review in the gh-pages-1.0 branch.  I've left the videos in place, for now.  Maybe I can make some icons or animations to replace them, later.

**Comment by matthewp** [comment]
Looks really good!  I'm going to make the image paths not absolute, otherwise will leave it in the branch until 1.0 is released.

**Comment by moschel** [comment]
Ping! @matthewp is there anything preventing this from landing? Seems like most of the work is done.

**Comment by matthewp** [comment]
No reason to wait, went ahead and deployed it. Thanks @marshallswain !

**Comment by boustanihani** [comment]
Does steal support for the **VUE Single File Components** format (*.vue) ?

Check: http://vuejs.org/guide/application.html#Single-File-Components) ?

An example would be great :)

**Comment by matthewp** [comment]
No one has built a plug in for that yet, to my knowledge.
