### ISSUE TITLE
Unable to debug in Firefox

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#470]
<img width="361" alt="_can-connect_canjs_tests" src="https://cloud.githubusercontent.com/assets/78602/9535584/78641ac4-4ce8-11e5-9e28-af2188b1fd76.png">

I always have to clear my history after every change.  I'm not sure if there's anything StealJS is doing, or anything that we can do besides turn on cache-busting, but this is really annoying.

Serving files with http-server.

**Comment by justinbmeyer** [comment]
Also, firefox's inspector does not how the code.  This is an even more serious bug.

**Comment by justinbmeyer** [comment]
https://developer.mozilla.org/en-US/docs/Tools/Debugger/How_to/Debug_eval_sources is what it's supposed to look like for FF.  I bet this is because we use `<script>` injection instead of eval.

**Comment by justinbmeyer** [comment]
changing `doEval` to the eval version fixes FF:

```
doEval = function(source) {
      try {
        eval(source);
      } catch(e) {
        throw e;
      }
    };
```

We should probably submit a FF bug.  And maybe a flag that people can toggle which eval.

**Comment by matthewp** [comment]
Not sure how I missed this, there are several FF bugs surrounding this problem.  I didn't know that using <script> injection was the cause though, and I spent many hours trying to figure it out.  I'll look and see if there's a bug on this specific issue.

**Comment by justinbmeyer** [comment]
I'm having some real trouble debugging FF.  Maybe we could have an option that would change `doEval`.  Something like: "no-global-vars".

**Comment by matthewp** [comment]
Why don't we just always use the eval() version? What is the benefit to script injection?  Looking at systemjs it looks like he's using new Function: https://github.com/systemjs/systemjs/blob/master/dist/system.src.js#L138

**Comment by justinbmeyer** [comment]
We don't use eval because something like Mootools, with code like:

```
var Mootools = {}
```

Wont work.

**Comment by matthewp** [comment]
Ah, ok now I get the config suggestion now. We could make it default to eval() (or new Function) and use meta config for legacy libraries.

**Comment by justinbmeyer** [comment]
yep.  That's what I'm thinking.

**Comment by matthewp** [comment]
This should be working on `steal@1.0.0-pre.2` now.

<img width="1223" alt="screen shot 2016-06-08 at 12 04 37 pm" src="https://cloud.githubusercontent.com/assets/361671/15901428/3a880a48-2d71-11e6-9080-176ebad3f760.png">
