### ISSUE TITLE
For Windows compatibility filenames should add file: protocol

### ISSUE THREAD

**Issue by daffl** [stealjs/steal#471]
To get server-side rendering working I had to add the `file:` protocol to any filename in Windows (see https://github.com/canjs/can-ssr/pull/39) because drive names like `C:` are being recognized as a protocol.

This might be a non-issue for anything that loads from relative URLs but we should make sure that server-side rendered apps work with the server on Windows.

**Comment by justinbmeyer** [comment]
@matthewp there's not a better way?  I thought SystemJS did something like this already.  How are we handling this with baseUrl?  We should probably do something similar.

**Comment by matthewp** [comment]
@justinbmeyer We are doing this for baseURL and a few other properties, I think in this case it is specifically paths, so could probably add that to the paths config setter.

**Comment by matthewp** [comment]
I don't think this bug is still happening.
