### ISSUE TITLE
Development Mode Not Working in Chrome

### ISSUE THREAD

**Issue by blink1073** [stealjs/steal#501]
I followed the [Quick Start](http://stealjs.com/docs/StealJS.quick-start.html).   It loads fine in Firefox and Safari (OSX 10.10.5), but I get this error in Chrome Version 46.0.2490.71 (64-bit):

<img width="535" alt="screen shot 2015-10-14 at 4 38 43 pm" src="https://cloud.githubusercontent.com/assets/2096628/10497099/1a8e7564-7292-11e5-889b-fa993a177326.png">

The Quick Start [Repo](https://github.com/stealjs/quick-start) works fine in Chrome when in `production` mode,  but not when changed to the dev script.

**Comment by matthewp** [comment]
You have jquery listed under your dependencies in the package.json?

**Comment by blink1073** [comment]
`"jquery": "^2.1.3",`

**Comment by matthewp** [comment]
I'm not able to reproduce. Try using a newer version of Steal (^0.11.0 maybe) and let me know, but the quickstart should be working.

**Comment by blink1073** [comment]
It was a weird cache problem.  When I forced Chrome to empty its cache, all works as expected.  Cheers!

**Comment by matthewp** [comment]
Ah, yeah I never trust caching so just turn it off when developing.

**Comment by blink1073** [comment]
Yep, a fellow dev just showed me the setting, will use from now on :wink:
