### ISSUE TITLE
Manually Trigger a NPM Traversal

### ISSUE THREAD

**Issue by blink1073** [stealjs/steal#506]
This is a recap of a conversation on gitter today.  I wanted to be able to trigger a re-fetch and traversal of the node packages without using a separate `live-reload` server.  The solution is as follows:

```javascript
System.delete('package.json!npm');
System.import('package.json!npm').then(function () { console.log('ready for action'); );
```

**Comment by blink1073** [comment]
Thanks for the help @justinbmeyer, @matthewp

**Comment by justinbmeyer** [comment]
Start of the conversation: https://gitter.im/stealjs/steal?at=562a4e21eec098f92cc27378

Link to much better solution which requires changes in system-npm: https://github.com/stealjs/system-npm/issues/41
