### ISSUE TITLE
Comparison Matrix on stealjs.com

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#515]
It would be nice to have a comparison matrix on the website.  It would basically be like this one: http://webpack.github.io/docs/comparison.html.  I'm not certain, how much would be different compared to jspm?

**Comment by matthewp** [comment]
It's a good idea, one that @brianmoschel has brought up before. I'm down for doing it but need some time to work on stuff like that.

**Comment by matthewp** [comment]
I'm putting this on the 1.0 epic, not sure I'll actually do it, but maybe.

**Comment by marshallswain** [comment]
I started this a while back: https://github.com/bitovi/brain/wiki/Steal-Comparison

**Comment by marshallswain** [comment]
Once it's finished, let me know and I'll make a PR to the webpack docs.

**Comment by matthewp** [comment]
Closing in favor of https://github.com/stealjs/stealjs/issues/72
