### ISSUE TITLE
Cache Busting - suffix not working

### ISSUE THREAD

**Issue by ivan-nikitovic** [stealjs/steal#517]
Referring to http://www.javascriptmvc.com/docs/stealjs.building.html#section_CacheBusting, I can say that *suffix* param is not used at all in latest version. Everything was working fine in version 0.4.0-pre.

**Comment by matthewp** [comment]
That's right, that document is referring to the legacy Steal: https://github.com/bitovi/legacy-steal

Now we have a 3rd party extension we use:  https://github.com/stealjs/cache-bust

**Comment by ivan-nikitovic** [comment]
@matthewp, thank you for you response. 

I have found that, and integrated it into project. Everything works fine now. 

I had one other issue with __baseURL__. I had it in configuration, and everything worked fine with older version, but now it's not working. I have to manually set System.baseURL to make my production files load from CDN. 

Is there any other way for doing that, through steal configuration?

**Comment by matthewp** [comment]
You can do it through config, usually you would set the baseUrl in the script tag like:

```html
<script src="path/to/steal.js" base-url="./foo"></script>
```
