### ISSUE TITLE
Contextual Module Extension

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#518]
We use this in live-reload, but it would be nice to have a generic API for defining a contextual module.

A contextual module is one that knows about it's parent, so a different module is registered for each parent.  As an example:

### chat/main
```js
import foo from "foo";
```

If **foo** were a contextual module, then the registry would contain a module called **foo/chat/main** and another for each module that imports foo.

Here's a possible API, the example is a contextual module that does normalization.

```js
System.setContextual("normalize", function(parentName){
  return {
    __useDefault: true,
    "default": function(moduleName){
      return System.normalize(moduleName, parentName);
    }
  }
});
```

Then this module could be used like:

### chat/main
```js
var normalize = require("normalize");

// normalize correctly passes in this module's name
normalize("child").then(function(name) { ... });
```

**Comment by justinbmeyer** [comment]
@matthewp I'm not super clear about the example.  The heading implies that _chat/main_ module does:

```
import foo from "foo";
```

And somehow this maps to `foo/chat/main`?   I don't understand how that would work.  I would assume it would map to something more like `chat/main/foo`.

**Comment by matthewp** [comment]
> And somehow this maps to foo/chat/main?

That would be the fully normalized module name, yes.

>  I don't understand how that would work. I would assume it would map to something more like chat/main/foo.

I suppose either would work ok. How I laid it out in this issue is how live-reload currently does it.  The module name can be whatever we want it to be, as long as it doesn't conflict with a module name that might exist in the user's project (which I don't think either of these could).  I think I prefer `foo/chat/main` because I see this as like a submodule of `foo` not a submodule of `chat/main` (it's a context-aware version of foo).

**Comment by justinbmeyer** [comment]
This originated out of `.component` right?

If I had a component module name like: `pmo/restaurants/list.component!`, I don't think the `viewModel` should be `viewModel/pmo/restaurants/list.component!`.  

We might be agreeing, but I have what is the "parent" in your example wrong.  It comes across that the parent is `chat/main` because it is importing `foo`.  Parents import their children.

**Comment by matthewp** [comment]
No, this has nothing to do with .component. This originated from live-reload. I can see what you're saying about .component's child modules.  This is not like that, `foo` is not a child of `chat/main`. It's a dependency of `chat/main` that knows `chat/main` is importing it.

We needed it for this:

```js
var reload = require("live-reload");

// The callback is called whenever THIS module is reloaded
reload(function(){

});
```

This `reload` function is different for each module that imports it. You can see how this is [defined here](https://github.com/stealjs/live-reload/blob/master/live.js#L84).  That code is essentially what this extension would be doing.

**Comment by justinbmeyer** [comment]
Ah, maybe contextual is the wrong word?  

> The definition of contextual is depending on the context, or surrounding words, phrases, and paragraphs, of the writing. An example of contextual is how the word "read" can have two different meanings depending upon what words are around it.

Does the meaning or behavior of "foo" change when "chat/main" imports it?  

It sorta fits, but was not at all my first thought when I heard "contextual".

**Comment by matthewp** [comment]
The behavior of the module is different depending on who imports it. The *context* is the parent module, I think it fits very well. 

Consider a real use case, this is a normalize that normalizes according to the parent module (without needing to pass the parent module name):

```js
var normalize = require("normalize");

normalize("./module_test").then(function(name){
  // name === my-app@1.0.0#module/module_test
});
```

**normalize** would be implemented with:

```js
System.setContextual("normalize", function(parentName){
  return {
    "default": function(name){
      return System.normalize(name, parentName);
    },
    __useDefault: true
  };
});
```

**Comment by justinbmeyer** [comment]
Just context is such an overloaded term in programming.  Does stache's contexts relate to this?  

I'm fine with naming it whatever you want to name it.  But as a mental exercise, try to come up with something else that describes it.

For example:

```
System.defineModuleBasedOnWhoIsImportingIt()
```

**Comment by matthewp** [comment]
Yeah sure, I'm open to other names that encapsulate the functionality better. The term `contextual` is used a bit in the module loader space. Module identifiers like `./module` are often called contextual.  WebPack has something called require.context that I believe is used to parse things like `require("/folder/" + name)`.

The only other word I can think of is **sandbox**.

**Comment by matthewp** [comment]
In minor.
