### ISSUE TITLE
NPM3 prerelease

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#521]
This is to track what is needed to make a pre-release that works with npm3.

* [x] - Run tests against https://github.com/stealjs/system-npm/pull/85
* [x] - Merge and release system-npm
* [x] - Documentation
* [x] - Run steal-tools tests

**Comment by skolade** [comment]
Thanks!!!!

**Comment by matthewp** [comment]
There's one known bug with nested packages that are different versions: https://github.com/stealjs/system-npm/issues/86

I'll likely have that fixed tomorrow.

**Comment by matthewp** [comment]
Released a 0.13.0-pre.1 with that latest fix.
