### ISSUE TITLE
Client-side 404 errors when loading from a `deduped` hierarchy.

### ISSUE THREAD

**Issue by sccolbert** [stealjs/steal#525]
If an application runs `npm dedupe` as part of install, the resulting `node_modules` hierarchy will have all common dependencies hoisted to the root level. When loading from this hierarchy, steal will log 404 errors for the `package.json` of the hoisted dependencies when it tries to read from the nested path. 
The module will eventually be found in the root, so the application will still work, but the 404 errors are unnecessary.

**Comment by justinbmeyer** [comment]
I'm thinking we could add a:

```
"npmAlgorithim": "dedupe"
```

**Comment by matthewp** [comment]
Thanks, if you happen to know an example deduped file structure it would make it easier to add this.

**Comment by sccolbert** [comment]
This repo would be a good example:
https://github.com/phosphorjs/phosphor-dockpanel

You should be able to clone it and run `npm install`. It will dedupe automatically on post install. Several of its direct dependencies will all share several common sub-dependencies.

**Comment by matthewp** [comment]
Great, that helps a lot, thanks.

**Comment by sccolbert** [comment]
And in case thats not what you mean, here's a screencap of a different example, with 404, along with the deduped structure:

`example` is the server root. The hierarchy is expanded to show all nested node modules in final deduped form:

![capture](https://cloud.githubusercontent.com/assets/137289/11546276/478bed04-991a-11e5-8f1d-ce31c390f418.PNG)

These are resulting 404s:

![capture](https://cloud.githubusercontent.com/assets/137289/11546287/5743f714-991a-11e5-87b6-4147667ec6e2.PNG)

**Comment by matthewp** [comment]
@sccolbert if I create an index.html in the phosphor-dockpanel project and have it do it's crawl I should see 404 errors there, right?

**Comment by sccolbert** [comment]
@matthewp yep, I just tried that got these 404s:

![capture](https://cloud.githubusercontent.com/assets/137289/11547307/eead4c3a-9920-11e5-80e3-d89acff8dd7c.PNG)

**Comment by matthewp** [comment]
Is this feature still desired? Now that we live in an npm3 world which is already flattened I don't think this feature is worth the effort.  Going to close, but will reopen if anyone objects.
