### ISSUE TITLE
Supports "globals" config

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#527]
i have 3 files:

**index.js**
_located: javascript/web/index/index.js_

```
System.import('javascript/globals/myglobaljs/foobar.js');

//respectively in stealjs
System.import('javascript/globals/myglobaljs/foobar');
```

**foobar.js**
_located: javascript/globals/myglobaljs/foobar.js_

```
;(function(global) {
    "use strict";
    console.log("it's "+moment().format());
})(window);
```

**moment.js**
_located: javascript/globals/moment.js_
-> source from homepage

Example with the newest SystemJS and Traceur

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src="system.js"></script>
    <script>
        System.config({
            baseURL: '/systemjs',
            transpiler: 'traceur',
            map: {
                traceur: 'https://google.github.io/traceur-compiler/bin/traceur.js'
            }
        });

        System.config({
            meta: {
                'javascript/globals/myglobaljs/foobar.js': {
                    "format": "global",
                    globals: {
                        moment: 'javascript/globals/moment.js'
                    }
                }
            }
        });
        System.import('javascript/web/index/index.js');
    </script>
</head>
<body>

</body>
</html>
```

the output is: `it's 2015-12-06T23:40:23+01:00`

the same example with stealJS (SystemJS version 0.16.6-bitovi.13):

```
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title></title>
    <script src='/node_modules/steal/steal.js' main="javascript/web/index/index"></script>
</head>
<body>
</body>
</html>
```

and the package.json file

```
{
  "name": "mycanjsapp",
  "version": "1.0.0",
  "description": "my test app",

  "main": "javascript/dist/foo",
  "files": [
    "javscript"
  ],
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [
    "test"
  ],
  "author": "Julian Kern",
  "license": "ISC",
  "dependencies": {
    "can": "^2.3.4",
    "done-autorender": "^0.5.0",
    "done-component": "^0.3.1",
    "jquery": "^2.1.4",
    "steal": "^0.13.0-pre.2"
  },
  "devDependencies": {
    "generator-donejs": "^0.4.0",
    "steal-qunit": "^0.1.1"
  },
  "system": {
    "main": "foolala",
    "npmIgnore": [
    ],
    "directories": {
      "lib": "javascript"
    },
    "map": {
      "can-autorender": "can/view/autorender/autorender",
      "components": "javascript/components",
      "modules": "javascript/modules",
      "models": "javascript/models",
      "globals": "javascript/globals"
    },
    "meta": {
      "javascript/globals/myglobaljs/foobar": {
        "format": "global",
        "globals": {
          "moment": "javascript/globals/moment"
        }
      }
    },
    "transpiler": "babel"
  }
}
```

output is:

```
Uncaught ReferenceError: moment is not defined(anonymous function) @ foobar.js:13(anonymous function) @ foobar.js:14
```

**Comment by justinbmeyer** [comment]
You shouldn't import a module by path like:

javascript/globals/myglobaljs/foobar.js

You should import it by name. Names should not have .js. 

I had a convo about this on gitter a few days ago (Thursday). Please look there for an explanation.

**Comment by justinbmeyer** [comment]
Btw, globals work fine with our systemjs. So that's not the issue.

**Comment by matthewp** [comment]
We don't use the current version of SystemJS, so that's why.  I do like the `globals` config though, we should add it.

We really need to distance ourselves from SystemJS as people repeatedly expect Steal to support everything SystemJS does.  I think we should get rid of the System global and use `steal` instead.

**Comment by matthewp** [comment]
@pYr0x using `deps` instead probably will give you what you want.  `deps: [ "javascript/globals/moment" ]`

**Comment by pYr0x** [comment]
> You shouldn't import a module by path like:
i didn't with steal... for the systemjs example i didn't add a suffix. the examples should only show the problem... and the problem is not to leave a .js at the end

> Btw, globals work fine with our systemjs. So that's not the issue.
the examples shows... it's a issue...
what do you think the problem is?

> using deps instead probably will give you what you want. deps: ["javascript/globals/moment"]
@matthewp yes, but with globals i can export the module to a different name
for example: 
```
"meta": {
      "javascript/globals/myglobaljs/foobar": {
        "format": "global",
        "globals": {
          "bar": "javascript/globals/moment"
        }
      }
    }
```
i can call moment in the ```foobar.js``` with ```bar()```

**Comment by matthewp** [comment]
The `globals` config is not supported by us, I'll change the title and make this be a feature request.

**Comment by pYr0x** [comment]
@matthewp ok, thanks

**Comment by justinbmeyer** [comment]
The System global is a spec thing. I don't think we should change it. Extensions couldn't work both places.

**Comment by pYr0x** [comment]
sorry, do not understand what you are trying to say..?

matthew said, that globals definiftion in the meta config is not supported in steal yet.

define globals is the best way for using legacy code in the application

**Comment by matthewp** [comment]
> The System global is a spec thing. I don't think we should change it. Extensions couldn't work both places.

The old global `System` is now going to be on `System.loader` and SystemJS is (at least this is what they are saying in an issue) not going to overwrite `System.loader` but instead create their own loader as `SystemJS`.

**Comment by pYr0x** [comment]
@matthewp we should remove the paragraph 

>
# Implementation
Implemented by SystemJS.

in http://stealjs.com/docs/System.meta.html 

or describe better what is possible with **your** SystemJS version

**Comment by matthewp** [comment]
Agreed, we should start removing those as we diverge more from current systemjs.
