### ISSUE TITLE
 reference to "production" where it should be "window-production"

### ISSUE THREAD

**Issue by patrickclancy** [stealjs/steal#530]
The script steal/ext/css.js has a reference to "production" where it should be "window-production".
```
if(loader.env === 'production') {
```

**Comment by matthewp** [comment]
I'll fix this.  Note that there is [done-css](https://github.com/donejs/css) now which does everything that the default css plugin does and more and doesn't have this bug. I'm debating whether it should be brought in and become the default css plugin replacing what we have here.
