### ISSUE TITLE
Specify babel version for steal to use

### ISSUE THREAD

**Issue by mickmcgrath13** [stealjs/steal#535]
This issue came from here: https://github.com/bitovi/jobcosttracker/issues/6

Two possibilities:
* specify a different version of babel
* (worst case) point steal to a different babel config

**Comment by matthewp** [comment]
You can specify the babel that's used with paths config, here are the defaults: https://github.com/stealjs/steal/blob/master/src/config.js#L297

So you can just use paths config to point to your own babel.js.  This is the browser version, which for babel 6 doesn't exist yet.

**Comment by matthewp** [comment]
Going to document how to do this since a lot of people use their own babel version.

**Comment by matthewp** [comment]
This is fixed in 1.0
