### ISSUE TITLE
Illegal module name "/my/component/component"

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#543]
creating a component with ```yo donejs:component my/component``` throw an error.

my ```.yo-rc.json``` looks like:
```
{
  "generator-donejs": {
    "folder": "src"
  }
}
```

my ```package.json``` have this system configuration:
```
"system": {
    "npmIgnore": [
      "devDependencies"
    ],
    "directories" : {
      "lib" : "src"
    }
  },
```

if i open the component directly like: http://localhost:8080/src/my/component/component.html
the error pops up.

the component.html is the default one, which is created with yoman.
```
<script type="text/stache" can-autorender>
  <can-import from="/my/component/" />
  <my-component></my-component>
</script>
<script src="../../../node_modules/steal/steal.js"
        main="can/view/autorender/"></script>
```

one thing i find out, is that steal uses the ```autorender```as main and does not load the ```System.directories``` 

how can i solve this problem? 
i want to open the ```component.html``` file itself.

**Comment by justinbmeyer** [comment]
> one thing i find out, is that steal uses the autorenderas main and does not load the System.directories

How do you know this?  Are you seeing a 404 error?

I think the problem is: `<can-import from="/my/component/" />`

The `/` at the start of this seems wrong. What is your project name? `my`?

This doesn't seem like a problem with steal, or with `can-autorender`.  My guess is that the generator isn't writing out this file correctly.  

If that's the case, this issue should be moved to the generators.

**Comment by pYr0x** [comment]
> How do you know this? Are you seeing a 404 error?

if the ```main``` attribute in the ```<script>``` tag is used. how can steal load the package.json file? 
the ```main``` attribute is used for can-autorender

if i open the console and display the ```System``` variable i see:
![image](http://i.imgur.com/y0sOnXE.png)

if i removed the slash at the beginning. i get an error

![image](https://cloud.githubusercontent.com/assets/1126711/12076762/2f9c5432-b1ba-11e5-874a-35a4a3c8f8f5.png)

**Comment by justinbmeyer** [comment]
> if the main attribute in the <script> tag is used. how can steal load the package.json file? 
the main attribute is used for can-autorender

I'm not sure what this means.  Can you elaborate?  Steal knows where the package.json file is because it's going to be relative to `steal.js`.

**Comment by justinbmeyer** [comment]
`<can-import from="/my/component/" />` should probably be `<can-import from="wecanjs/my/component/" />`

**Comment by justinbmeyer** [comment]
Can you move this issue here: https://github.com/donejs/generator-donejs .  This isn't related to stealjs.
