### ISSUE TITLE
Use another JSX transformer (not React)

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#545]
To use JSX transformer with for example for `cycle.js` (http://cycle.js.org/getting-started.html), they have internal `hJSX` transformer that should be used.

They advice to add `pragma` option to `babelOptions` (I believe)

```
// in package.json
{
  "plugins": [
    ["transform-react-jsx", { "pragma": "hJSX" }]
  ]
}
```

But this doesn work with `steal`. The workaround is such hack:

```javascript
import {hJSX} from '@cycle/dom'

const React = {createElement: hJSX}

jsx = <div></div>

```

Is there something do do about it?

**Comment by matthewp** [comment]
I think that's for babel 6, we're still on babel 5. I think it's "jsxPragma": "hJSX" in babel 5.

**Comment by whitecolor** [comment]
There is an error:
```
Potentially unhandled rejection [2] TypeError: Error loading "undefined" at <unknown>
The plugin ["transform-react-jsx",{"jsxPragma":"hJSX"}] didn't export a Plugin instance
```

**Comment by matthewp** [comment]
I don't think plugins are a babel 5 thing. I don't know how to help you further though. I would search for how to set the jsx pragma in babel 5.

**Comment by whitecolor** [comment]
Well it seems it should be supported:
https://github.com/babel/babel.github.io/search?utf8=%E2%9C%93&q=pragma

**Comment by whitecolor** [comment]
When are you going to support babel 6?

**Comment by matthewp** [comment]
Not sure, babel 6 doesn't have a browser build yet. Which that exists we'll support it.

**Comment by whitecolor** [comment]
Perpase related issue https://github.com/sapegin/react-styleguidist/issues/65
There is some workaround for server side, maybe you have thoughts how it can be "fixed" for steal based on comments to the issue?

**Comment by whitecolor** [comment]
I think this can be closed in favor of https://github.com/stealjs/steal/issues/546 as this is a matter of ability to use plugins.
