### ISSUE TITLE
Use Babel 6 by default

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#546]
There are a few issues that have indirectly requested using babel 6 (https://github.com/stealjs/steal/issues/545, https://github.com/stealjs/steal/issues/535). It looks like Babel is no longer going to have a browser version, so using `babel-core` might be the way to go. Otherwise, it may be necessary to bundle Babel before using it - if that's possible.

**Comment by matthewp** [comment]
We would need a browser build for sure. How I think it should eventually work is that if you are using steal-tools watch mode it uses the node version of babel.

**Comment by whitecolor** [comment]
@matthewp
https://babeljs.io/docs/usage/browser/
Is there a way to use babel 6 for steal build currently?

**Comment by matthewp** [comment]
No, we could allow you to provide your own babel so you can use whatever version you want.  Maybe something like:

```js
stealTools.build({
  config: __dirname + "/package.json"
}, {
  transpile: function(source) {
    return require('babel-core').compile(source);
  }
});
```

This way it would use your own babel-core module, however this would mean it would be your responsibility for passing in source maps and what not.

**Comment by whitecolor** [comment]
Yes that would be fine. And thoug this `transiple` function should pass any kind of files (for example styles or what ever to be able to apply custom transformers - this would be alternative to systemjs plugins). What do you think?

**Comment by justinbmeyer** [comment]
Someone is maintaining https://github.com/Daniel15/babel-standalone ... we should reach out to that guy and support that project.

**Comment by whitecolor** [comment]
Well I think allowing usage of custom traspiler for build is needed anyway (and not only for JS files).

**Comment by justinbmeyer** [comment]
A not super enlightening discussion I had with babel about this: https://babeljs.slack.com/archives/discussion/p1452048781013621

**Comment by whitecolor** [comment]
@justinbmeyer can not login to to this discussion, what is it?

**Comment by whitecolor** [comment]
@justinbmeyer well it seems you can quite easy bundle it (babel-core with needed presets) into steal - you do it any way), plugin API should  be supported either.

**Comment by matthewp** [comment]
When we get babel6 support I think we should keep babel5 in the project so users can use it for backwards compatibility. They could just add a map of `map: { babel: "@babel5" }` or something like that.

**Comment by whitecolor** [comment]
@matthewp 
Is it currently possible to create a plugin that will handle (translate) default *.js sorces?

**Comment by matthewp** [comment]
Related: https://github.com/stealjs/steal/issues/554

**Comment by whitecolor** [comment]
@matthewp Actually I was asking about how to use *babel 6* for build today. Is it possible somehow?

**Comment by matthewp** [comment]
@whitecolor No, it's not, created https://github.com/stealjs/steal-tools/issues/354 to track that request.

**Comment by matthewp** [comment]
@phillipskevin @whitecolor I'm thinking about just adding steal-standalone as our new babel dependency. It seems to include the most common plugins. Not sure what the plan would be for other plugins, but we can discuss this later.  Sound reasonable?

**Comment by whitecolor** [comment]
@matthewp I think steal should give more freedom and not be "packed" and opinionated, just thought.

**Comment by whitecolor** [comment]
@matthewp I think steal have to me more modular. Should have some `core` (maybe `system, crawler, graph` inside) and other separate modules: `builder, assets bundler, watcher, reload, babel, traceur, less/sass`, etc... And it should be presented that way. Good programmers love modulariy - they love freedom (to experiment either) - packing everying in one bundle may be not the best solution and there sould be an option . Steal is quite good now (though have some caveats, bugs, and lacks), but I see absence of modularity as well a s one of the problems, well just my thought, food for the mind)

**Comment by matthewp** [comment]
@whitecolor Babel is not packed into the Steal bundle, it's an external module that only gets included when you use es6. You can use a different (or your own) version of Babel with paths config:

```js
"system": {
  "paths": {
    "babel": "path/to/my/babel.js"
  }
}
```

We do include our own babel.js to be the default though. I think it makes sense that users shouldn't have to build their own babel.js to get es6 support.  Perhaps some better docs on using your own Babel would be helpful though?

**Comment by whitecolor** [comment]
@matthewp Yes, thats it a good idea to stres on customizations, and don't stress on such opinionated thing like `less/css` compiling outof the box (any way sass is more popular why not include it too? But better is to have both in external modules). 

So thats mean that it is currenlty possible to use other babel verson on the client and on server, or not?

**Comment by matthewp** [comment]
Have a pull request in to support Babel 6. It will go into the **major** branch which will become 1.0.0.  Going to test in a couple of apps first.

**Comment by whitecolor** [comment]
@matthewp what presets do you include in bundle? do you inlclude state-0?

**Comment by matthewp** [comment]
We use babel-standalone so all presets it includes are included, you can see them here: https://github.com/Daniel15/babel-standalone/blob/master/src/index.js#L132

By default (if you do not include presets/plugins in your babelOptions) we use the presets `['es2015-no-commonjs', 'react', 'stage-0']`

**Comment by matthewp** [comment]
I'll note in the PR that all of this needs to be documented.

**Comment by whitecolor** [comment]
why `es2015-no-commonjs`?

**Comment by matthewp** [comment]
Because it transpiles to the "system" format in the browser.

**Comment by whitecolor** [comment]
Yeah  but I believe it refers to this: https://github.com/stealjs/steal/issues/551

**Comment by matthewp** [comment]
We can't use commonjs because transpiling happens after the `translate` stage; it's too late to change formats at this point.

**Comment by matthewp** [comment]
Currently blocked by https://phabricator.babeljs.io/T7015

**Comment by matthewp** [comment]
Another blocking bug: https://phabricator.babeljs.io/T6766

**Comment by matthewp** [comment]
@pYr0x those bugs might have been fixed in a newer version of babel 6 (I last tried in January). If not, we can work around it during the transpile of steal-tools.  Can discuss that with you if you want.

**Comment by matthewp** [comment]
@pYr0x Here's the branch with the upgrade: https://github.com/stealjs/steal/blob/babel6

**Comment by matthewp** [comment]
And here's the one of transpile: https://github.com/stealjs/transpile/tree/babel6

**Comment by isadovskiy** [comment]
@matthewp so how to upgrade StealJS to use Babel 6 in dev mode? I'm still interested in due to https://github.com/stealjs/steal/issues/566 in order to have more robust solution.

**Comment by matthewp** [comment]
This is in major now, released as 1.0.0-pre.1.  Note that steal-tools also has to be upgraded and hasn't yet (in progress).

**Comment by whitecolor** [comment]
will it be possible to use additional plugins? (in `window` env)

**Comment by matthewp** [comment]
See the [comment here](https://github.com/stealjs/steal/issues/566#issuecomment-220075092) about how I want to handle plugins.  To summarize; the Babel that comes with Steal will do ES201x support and be updated less regularly. When the new plugin API lands I'm going to create a new Babel plugin that will transpile to CommonJS and do things like:

* Allow babel plugins to be used.
* Allow you to transpile any JavaScript (including CommonJS/AMD).
* Allow you to selectively transpile only your apps code (exclude node_modules).
