### ISSUE TITLE
Hot-module swapping bug

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#547]
When I get to the [Create Routes](http://donejs.com/place-my-order.html#section=section_CreateRoutes) section of the guide, the `message` default value is being removed.  This should have the effect of making the page blank.  

After a refresh the page is blank, and then live binding seems to respond, but not the first time.

**Comment by justinbmeyer** [comment]
Also, we might want to check out the test page of: http://localhost:8080/src/restaurant/list/test.html as the user is changing it.  When I looked at it, the QUnit results were different after I refreshed.

**Comment by justinbmeyer** [comment]
Once I add the unit tests, I see:

![_place-my-order_restaurant_list](https://cloud.githubusercontent.com/assets/78602/12162637/58a185ba-b4ca-11e5-9eb6-70becc96eaab.png)

I'm not sure if that's expected.

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-qunit #15](https://github.com/stealjs/steal-qunit/issues/15) via [**ZenHub**](https://www.zenhub.com/)
