### ISSUE TITLE
Mapped non-npm packages

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#548]
I have a module installed from github:

```json
"dependencies": {
  "super-module": "username/super-module",
}
```
so, lets say it's a steal plugin and I want to use it as `sm` like:
```javascript
import 'something!sm'
```
So I map it
```json
"map": {
  "./sm": "super-module"
}
```

But it doesn't work (steal/ext/npm.js) gives an error.

If to map to map it as non-npm:
```json
"map": {
  "./sm": "./node_modules/super-module/index"
}
```

It works.

It is by design behavior? Why package from git repo can not be treated as other npm packages when mapped?

**Comment by matthewp** [comment]
Might be a bug, if there's an error it's definitely a bug.

**Comment by whitecolor** [comment]
If to just replace version:
```json
"dependencies": {
  "super-module": "0.0.1",
}
```
it will work

**Comment by matthewp** [comment]
Is an error thrown?

**Comment by whitecolor** [comment]
Error when version is set to `username/super-module`
```
Potentially unhandled rejection [4] TypeError: Error loading "package.json!npm" at .../package.json
Cannot read property 'system' of undefined
    at convertName (.../node_modules/steal/ext/npm.js:189:14)
```

**Comment by whitecolor** [comment]
BTW it works if to set to full url
```
"dependencies": {
  "super-module": "http://github.com/username/super-module",
}
```

**Comment by whitecolor** [comment]
*Summary*

mapping works:
```
"dependencies": {
  "super-module": "http://github.com/username/super-module",
}
```
mapping doesn't work:
```
"dependencies": {
  "super-module": "http://github.com/username/super-module",
}
```

**Comment by matthewp** [comment]
Issue moved to [stealjs/system-npm #179](https://github.com/stealjs/system-npm/issues/179) via [**ZenHub**](https://www.zenhub.com/)
