### ISSUE TITLE
package.json parse browser field

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#549]
works
```
"browser": "engine.io.js",
```
What do you think, should this work too?
```
"browser": {
  "main": "engine.io.js",
}
```
The problem with this module:
https://github.com/socketio/engine.io-client/blob/master/package.json#L57

**Comment by matthewp** [comment]
We do support the browser field. What specifically is not working?  By the way, we created steal-socket.io to make it easier to use with steal: https://github.com/stealjs/steal-socket.io

**Comment by whitecolor** [comment]
Do you parse it? "main"? or just handle string value?
```
"browser": "engine.io.js",
```
But comlex object is not like in OP.

**Comment by whitecolor** [comment]
Socket.io client is working with map:
```
"map": {
      "socket.io-client": "socket.io-client/socket.io"
    },
```

**Comment by matthewp** [comment]
We do parse the browser object: https://github.com/stealjs/system-npm/blob/master/npm.js#L202

It's possible we are missing some scenarios though, would need more info to figure out what those are.

**Comment by whitecolor** [comment]
if to add "main" to "browser" in https://github.com/socketio/engine.io-client/blob/master/package.json#L57
"browser": {
  "main": "engine.io.js",
}

Steal doesn't see it.

**Comment by matthewp** [comment]
What does "main" refer to here? Is this supposed to be the project main?

**Comment by whitecolor** [comment]
I think yes it should be, a pretty standard convention, no?

**Comment by justinbmeyer** [comment]
I don't think that's a supported property of browserify's "browser" option.

**Comment by matthewp** [comment]
I wasn't sure if it was or not. If not what you want to do instead is:

```js
{
  "main": "main.js",
  "browser": {
    "./main.js": "./other.js"
  }
}
```

**Comment by whitecolor** [comment]
Ok then there is no info about `main`
https://github.com/defunctzombie/package-browser-field-spec#replace-specific-files---advanced

but `jspm` field should be considered I believe https://github.com/stealjs/steal/issues/550

**Comment by whitecolor** [comment]
if "browser" field is an object I beleve in contains a `paths` map:
https://github.com/visionmedia/superagent/blob/master/package.json#L52
```
"./lib/node/index.js": "./lib/client.js"
````
So that if main was parsed as `./lib/node/index.js`from package.json then `./lib/client.js` should be taken instead.

**Comment by matthewp** [comment]
Yes, we should be supporting this. There is definitely code for it.  It's possible it's not working when the mapping is for the main.

**Comment by whitecolor** [comment]
Yes if the is no `main` it seem to handle it.

**Comment by pYr0x** [comment]
is this PR handle this issue? https://github.com/stealjs/system-npm/pull/67
should i resolve the conflicts on this PR?

**Comment by matthewp** [comment]
@pYr0x if you're going to look into this would you mind adding a test to that pr?

**Comment by matthewp** [comment]
Issue moved to [stealjs/system-npm #178](https://github.com/stealjs/system-npm/issues/178) via [**ZenHub**](https://www.zenhub.com/)
