### ISSUE TITLE
package.json parse jspm field

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#550]
Also this could be parsed:
```
"jspm": {
  "main": "socket.io.js",
}
```
https://github.com/socketio/socket.io-client/blob/master/package.json#L14

**Comment by matthewp** [comment]
There's an issue in system-npm: https://github.com/stealjs/system-npm/issues/34

**Comment by whitecolor** [comment]
You could currently add support for steal, as some people use this, like in `soket.io-client` case

**Comment by matthewp** [comment]
Not sure what you mean. That issue is to add it to Steal. Should be easier to do.

**Comment by whitecolor** [comment]
I mean maybe to parse this field if it in package.json and take its `main` instead of package.json `main`.

**Comment by matthewp** [comment]
Yes, that is how it would work. This the same thing with system.main in the package.json.

**Comment by whitecolor** [comment]
So this doesn't wok now. Steal does not consider it.

**Comment by matthewp** [comment]
I know, that's why https://github.com/stealjs/system-npm/issues/34 exists.

**Comment by whitecolor** [comment]
Why is this responsiblity of SystemJs?

**Comment by matthewp** [comment]
It's not, system-npm is the plugin we use to load dependencies from node_modules, it's Steal's plugin, we control it. We just develop it in a separate project.

**Comment by whitecolor** [comment]
Ah sorry I din't notice that it it system-npm)
