### ISSUE TITLE
support `import {some} from 'module'` for CJS

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#551]
Following https://github.com/stealjs/steal-tools/issues/352.

I think steal should support 
```javascript
import {x} from 'module'
``` 
for CJS `module` like this:
```javascript
module.export = {
  x: 1,
  y: 2
}
```
Currenlty `x` will be `undefined` on import

Justification? Babel 6 transpiler currently support this. 
If `steal` doen't support it - some apps may not load correctly with steal without modification  (while they load with node babel transpiler ) - I faced the cases.

If steal supports this it loses/breaks nothing for future as well.

**Comment by justinbmeyer** [comment]
Originally systemJs supported this. But it dropped it for what I assume were good reasons. I'm doubtful we can support this.

**Comment by matthewp** [comment]
Guy changes his mind every other week so I wouldn't be surprised if he switched it back again by now.  I don't mind "getting this right", but right is going to be whatever Node does when they land their es6 loader.

As of now Steal is stable and should be at 1.0 (going to make a roadmap soon on how to get there) so if we were to make this change it would have to be then. Going to need to discuss the benefits and downsides a little more though :)

**Comment by whitecolor** [comment]
What can be wrong with support of this actually?

**Comment by justinbmeyer** [comment]
Symmetry. I think the problem was related to making sure importing and exporting in every format worked in a similar and predictable way. 

I'm traveling today, but I'm sure you can find the discussion of this in systemjs's issues. I might have even been the one to create the issue when this changed.

**Comment by whitecolor** [comment]
Doesn't this
https://github.com/systemjs/systemjs/blob/9ed38dd94f52eefa1b623d8c2b8623a92b480b2a/test/tests/es-named-import-cjs.js

mean that this:
```javascript
exports.x = 1
exports.y = 2
```
Should work? But It doesn't with steal.

**Comment by whitecolor** [comment]
@justinbmeyer @matthewp 
Well I checked and this actually works in SystemJS (v0.19.9), so its a steal issue. And again: steal's inability of doing this breaks loading of some modules.

**Comment by matthewp** [comment]
@whitecolor does it support importing the default as well? What happens when you do:

```js
import { default as foo } from 'module'
```

do you get the module.exported thing?

**Comment by whitecolor** [comment]
@matthewp
Yes it does.
`import { default as foo } from 'module'` works the same way as `import foo from 'module'`

**Comment by matthewp** [comment]
Yeah, I know, I'm asking if you're importing a commonjs module does it get `exports.default` or `module.exports`?

**Comment by whitecolor** [comment]
It get `module.exports`, from my understanding: CJS exports only one value which is treated as default, if it is an object its props also are treated as named exports.

**Comment by whitecolor** [comment]
so you probabbly don't want to use `default` prop in `exports` object, it won't be treated as named export.

**Comment by matthewp** [comment]
Did you test this with your new version of systemjs?

### foo.js
```js
module.exports = 'foo';
```

### main.js
```
import foo from 'foo.js';
```

This gets the string foo?

**Comment by whitecolor** [comment]
As I've mentioned it's quite new SystemJS (v0.19.9) last available is 0.19.16.
Yes it gets 'foo' as well as `import {default as foo} from 'foo.js'`

**Comment by whitecolor** [comment]
I would marked as bug)

**Comment by matthewp** [comment]
https://github.com/stealjs/steal/issues/554 is another possible solution, because Babel would transpile to CommonJS in a Service Worker, so Steal would only ever be loading CommonJS modules.

**Comment by matthewp** [comment]
Someone provided a minimal example of this not working: https://github.com/stealjs/steal/issues/566#issuecomment-178504525

**Comment by whitecolor** [comment]
So I would make this consistent with current node/babel loader

**Comment by matthewp** [comment]
This is working in pre.
