### ISSUE TITLE
Run Babel inside a Service Worker

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#554]
See https://github.com/bahmutov/babel-service as an example that does this. This could be a good thing to have in development mode as it gives you transpiling with caching for free.

**Comment by whitecolor** [comment]
That is not bad.

**Comment by matthewp** [comment]
Issue moved to [stealjs/rfcs #12](https://github.com/stealjs/rfcs/issues/12) via [**ZenHub**](https://www.zenhub.com/)
