### ISSUE TITLE
Fallback to node syntax-compatible imports.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#556]
Consider the following folder/file structure:
```
hooks/index.js
index.js
```

Would it be possible to make it so that when I do `import hooks from './hooks'`, Steal falls back to `hooks/index.js` when it can't find `hooks/hooks.js`?

I'm assuming there's a major hurdle to making this happen, or it would likely be in place, already.  But, this would be really convenient when trying to take a module that currently works in Node and making it also work in the browser.

**Comment by matthewp** [comment]
Yeah, this is a known issue. Steal should really be able to load anything that browserify/webpack can bundle. @akagomez put some work and got it to work in dev: https://github.com/stealjs/system-npm/pull/66 but this solution won't work for production.  I'd like to fix this issue soon.
