### ISSUE TITLE
Allow npmAlgorithm to be set per-machine

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#563]
We should allow it to be override so that members of a team don't all have to use the same version of NPM. This will only be an issue for a while, because eventually everyone will be on NPM >= 3, but in the meantime we could support something like `localStorage.npmAlgorithm = 'flat' / 'nested';` as a way to override.

**Comment by justinbmeyer** [comment]
I don't think this should be high priority.  In general, for a development effort, it's pretty important that everyone is on the same version of npm/node.

**Comment by whitecolor** [comment]
We had this issue. I think need to:

1) allow to set via the npm-algaritm tag
2) allow to set alg via javasascript prior `<script` steal tag like it was before, so make possible something like that:
```
steal = {
  npmAlgriithm: localStorage.getItem('npmAlgriithm')
}
```
I checked it seem not to work.

**Comment by matthewp** [comment]
Yes, that doesn't work, but you're right, that's a better way to do it rather than localStorage, so people can use localStorage themselves like in your example.

**Comment by matthewp** [comment]
Not sure this is a good option any more, now that we live in a npm3+ world.
