### ISSUE TITLE
404 (not found)  on all of the stache.js files  when running the production.js

### ISSUE THREAD

**Issue by bgraves21** [stealjs/steal#567]
![image](https://cloud.githubusercontent.com/assets/15893414/12655232/9f95dc4c-c5bd-11e5-9a86-0c20bf40fc48.png)

**Comment by matthewp** [comment]
how are you importing your stache files?

**Comment by bgraves21** [comment]
stealing them in     steal('can',
	'./views/headerInit.stache', 
	'checker/common/resources.js',
	'checker/models/fixtures',
		
	function(can, initView,  ResourceManager){

**Comment by justinbmeyer** [comment]
Can you remove every import except for one `.stache` template from your app.  Your app should look like:

```
steal("./some/template.stache", function(template){
  console.log("WORKS")
})
```

Does this work?  

If not, can you paste your build output with debugging turned on?

You can pass `debug: true` to `stealTools.build`:

```
var stealTools = require("steal-tools");

var promise = stealTools.build({
  main: "my-app",
  config: __dirname+"/package.json!npm"
},{
  // the following are the default values, so you don't need
  // to write them.
  minify: true,
  debug: true
});
```

**Comment by bgraves21** [comment]
I have removed all imports except for the .stache.  Build successful, running in development mode successfull   but  in production mode   still getting http://localhost:9001/checker/components/header/views/headerInit.stache.js Failed to load resource: the server responded with a status of 404 (Not Found)   
 I am attaching the zipped up output from the build  with debug turned on 

[checker.zip](https://github.com/stealjs/steal/files/110419/checker.zip)

**Comment by justinbmeyer** [comment]
Ah, I think you're forgetting the `!` after `.stache!`.  Make sure you have that.

cc @matthewp is the `!` necessary for builds?  

@bgraves21 make sure you have latest steal-tools.

**Comment by matthewp** [comment]
The bang shouldn't be necessary at all. However that's a new feature.  Most important thing is to make sure your steal and steal-tools are matching versions.

**Comment by bgraves21** [comment]
How do I make sure that  steal and steal-tools  are the same version?    I am getting errors when I try to do an npm install  steal steal-tools --save-dev  (no issues with other projects/code bases).   I downloaded the  steal-master.zip from the stealjs.com  but could not find where to download the latest steal-tools.     Can you put what the latest version is somewhere out on the web site  similar to how canjs>

**Comment by bgraves21** [comment]
npm install steal-tools works   but  npm install steal    fails    

PS C:\responsive_training\AddressCheckerSampleProjectStealCanUpgrade> npm install steal --save-dev
npm WARN package.json app@0.0.0 No description
npm WARN package.json app@0.0.0 No repository field.
npm WARN package.json app@0.0.0 No README data
npm WARN package.json app@0.0.0 No license field.
npm WARN addRemoteGit Error: Command failed: git -c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit
npm WARN addRemoteGit     at ChildProcess.exithandler (child_process.js:203:12)
npm WARN addRemoteGit     at emitTwo (events.js:87:13)
npm WARN addRemoteGit     at ChildProcess.emit (events.js:172:7)
npm WARN addRemoteGit     at maybeClose (internal/child_process.js:818:16)
npm WARN addRemoteGit     at Socket.<anonymous> (internal/child_process.js:319:11)
npm WARN addRemoteGit     at emitOne (events.js:77:13)
npm WARN addRemoteGit     at Socket.emit (events.js:169:7)
npm WARN addRemoteGit     at Pipe._onclose (net.js:469:12)
npm WARN addRemoteGit  git://github.com/bitovi/systemjs.git#0.16.6-bitovi.8 resetting remote C:\Users\373927\AppData\Ro
ming\npm-cache\_git-remotes\git-github-com-bitovi-systemjs-git-9174bfc6 because of error: { [Error: Command failed: git
-c core.longpaths=true config --get remote.origin.url
npm WARN addRemoteGit ]
npm WARN addRemoteGit   killed: false,
npm WARN addRemoteGit   code: 1,
npm WARN addRemoteGit   signal: null,
npm WARN addRemoteGit   cmd: 'git -c core.longpaths=true config --get remote.origin.url' }
npm ERR! git clone --template=C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.c
m/bitovi/systemjs.git C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bitovi-systemjs-git-9174bfc
: Cloning into bare repository 'C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bitovi-systemjs-g
t-9174bfc6'...
npm ERR! git clone --template=C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.c
m/bitovi/systemjs.git C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bitovi-systemjs-git-9174bfc
: fatal: unable to connect to github.com:
npm ERR! git clone --template=C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\_templates --mirror git://github.c
m/bitovi/systemjs.git C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bitovi-systemjs-git-9174bfc
: github.com[0: 192.30.252.130]: errno=No error
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "in
tall" "steal" "--save-dev"
npm ERR! node v4.2.2
npm ERR! npm  v2.14.7
npm ERR! code 128

npm ERR! Command failed: git -c core.longpaths=true clone --template=C:\Users\373927\AppData\Roaming\npm-cache\_git-rem
tes\_templates --mirror git://github.com/bitovi/systemjs.git C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git
github-com-bitovi-systemjs-git-9174bfc6
npm ERR! Cloning into bare repository 'C:\Users\373927\AppData\Roaming\npm-cache\_git-remotes\git-github-com-bitovi-sys
emjs-git-9174bfc6'...
npm ERR! fatal: unable to connect to github.com:
npm ERR! github.com[0: 192.30.252.130]: errno=No error
npm ERR!
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\responsive_training\AddressCheckerSampleProjectStealCanUpgrade\npm-debug.log

**Comment by matthewp** [comment]
@bgraves21 you might have a caching issue. Do `npm cache clean` and then retry your install.

**Comment by bgraves21** [comment]
same error

**Comment by matthewp** [comment]
git://github.com/bitovi/systemjs.git#0.16.6-bitovi.8  <--- that's an old version that we don't depend on any more. You do have a caching issue, I don't know how to clear it out though other than npm cache clean.

**Comment by bgraves21** [comment]
I now have  steal 0.13.2  and steal tools 0.13.2,   canjs2.3.11.  I have removed all imports except for stache still have the same issue  GET http://localhost:9001/checker/components/header/views/headerInit.stache.js 404 (Not Found)

The output from the build is attached, 

[checker.zip](https://github.com/stealjs/steal/files/112880/checker.zip)

**Comment by matthewp** [comment]
Thanks, i'll take a look at your build.

**Comment by matthewp** [comment]
Hey @bgraves21, I'm betting you are missing the config field in your script tag, this is needed for production. Should look like this:

```html
<script src="steal.production.js" config="stealconfig.js" main="checker/checker"></script>
```

**Comment by bgraves21** [comment]
I thought that the production build included the stealconfig.js within the build  similar to the old steal  and therefore we did not need it in the script tag.    This did resolve the 404 not found for statche  but  now I have to figure out why nothing is showing up with the production js    just a blank page with no console errors.

**Comment by matthewp** [comment]
The config is used to establish your base url. you could have also done `base-url="../path/to/base"` instead.
