### ISSUE TITLE
Hot module swapping doesn't recover from incorrect import error

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#568]
Working through the donejs-chat guide, if you have a typo in a `<can-import />` like misspelling "bootstrap" like: `<can-import from="bootstra/less/bootstrap.less!" />` you get an error:

![image](https://cloud.githubusercontent.com/assets/5851984/12659356/001a1ee6-c5d4-11e5-9c7b-f3d2561155fc.png)

Once you fix the typo, the server has to be restarted in order to see the change.

**Comment by whitecolor** [comment]
@phillipskevin you may also try this https://github.com/whitecolor/can-hot

**Comment by pYr0x** [comment]
@whitecolor this is great!!! 
whats the benefit of can-hot to http://stealjs.com/docs/steal.live-reload.html ?

**Comment by phillipskevin** [comment]
This is a duplicate of https://github.com/donejs/donejs/issues/470.
