### ISSUE TITLE
Handle optionalDependencies

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#570]
it seems that steal doen't handle optionaldependencies in package.json
https://docs.npmjs.com/files/package.json#optionaldependencies

**Comment by whitecolor** [comment]
Well this probably should be handled when progressive parsing is ready, as this deps not present.

**Comment by matthewp** [comment]
Are optionalDependencies used for client-side code? I thought the purpose was for native modules that may fail to compile.

**Comment by whitecolor** [comment]
Well scenarios may vary. They also can be used for storing sensetive data (for example deployment credentilas and keys), that not all developers have access to. Or something like that.
