### ISSUE TITLE
Allow to load steal without main

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#573]
```
<script src="/node_modules/steal/steal.js">
```
Takes default `package.json` and if there `main` (or `browser`, etc) fields it load them. I think there should be option not to load main. Setting `main=""` causes error. So it could be "manually" imported. in script body.

**Comment by matthewp** [comment]
You can do `main="@empty"`

**Comment by whitecolor** [comment]
Great.

**Comment by matthewp** [comment]
Same for configMain (or any module you don't want loaded)
