### ISSUE TITLE
Steal 0.13 NPM plugin preferring dependency's depencency over local path

### ISSUE THREAD

**Issue by kylegifford** [stealjs/steal#577]
We are using Steal 0.13.2, and the NPM plugin. Our root directory structure looks like:

```
/controls
/components
/pages
/utils
```

and `/utils` contains modules such as `/analtyics/analytics.js`.

We also are including a dependency, Sinon, which has the following in its package.json:

```
  "dependencies": {
    "util": ">=0.10.3 <1",
  },
```

On our app page, we are `steal()`ing in several modules from `controls`, `components`, etc without issue. However, when you try to include `utils/analtyics/`, we get the following error:

```
error Error loading "util@0.10.3#analytics/analytics" at http://localhost:8125/node_modules/sinon/node_modules/util/analytics/analytics.js
Error loading "util@0.10.3#analytics/analytics" from "pages/index" at http://localhost:8125/pages/index.js
Not Found: http://localhost:8125/node_modules/sinon/node_modules/util/analytics/analytics.js undefined
```

So what is happening is that Steal is preferring to use Sinon's util dependency instead of our root `/util` folder. To work around this, we have temporarily switched to relative paths (`../util/analytics/`) which works fine, but we would prefer to not have to rename utils nor keep relative pathing.

Ideal outcome here would be that we could tell Steal to use our `/util` path, except in the Sinon module.

**Comment by matthewp** [comment]
This is fixed in 0.14.0
