### ISSUE TITLE
NPM meta information needs to be removed in production

### ISSUE THREAD

**Issue by alexisabril** [stealjs/steal#586]
Running `npm install` on a project, will add meta information about the system which ran the command to the dependencies' `package.json`. In a production build, this information is included into the compressed js file.

For example,

`npm install can` will add a `can` folder within `./node_modules`. Inside `./node_modules/can/package.json`, you will find a set of '_' prefixed parameters such as:

```
  "_args": [
    [
      "can@^2.3.16",
      "/absolute/path/on/system/that/ran/install"
    ]
  ],
```

**Comment by matthewp** [comment]
Is this the thing where you had a package requiring package.json?

**Comment by alexisabril** [comment]
Yeah, this is that one

**Comment by matthewp** [comment]
Ah, ok, so this only happens when a package requires a json file, it doesn't happen to the package.jsons that we load to configure Steal. Just want to clarify that.

**Comment by alexisabril** [comment]
I believe so, however that is just my observation not a concrete point

**Comment by matthewp** [comment]
Like we talked about, I think we can provide config that lets you control json parsing.  Something like:

```js
stealTools.build({
  config: __dirname + "/package.json!npm",
  jsonOptions: {
    transform: function(load, json){
      delete json._args;
      return json;
    }
  }
})
```

How does this sound?

**Comment by alexisabril** [comment]
That sounds great! That'd be an easy implementation fix for this project
