### ISSUE TITLE
configDependencies issue in 0.14.x

### ISSUE THREAD

**Issue by alexisabril** [stealjs/steal#588]
Adding a `System.config` mapping via `configDependencies` has a bug in 0.14 when in production mode. 

Calling `System.import` for the new mapping returns a 404 as the mapping may have not yet been defined. This works in dev mode and 0.13.x.

**Comment by matthewp** [comment]
I think the bug is that your configDependency code is not running in prod. Will look into it.

**Comment by matthewp** [comment]
This is caused by this line: https://github.com/stealjs/system-npm/blob/master/npm-load.js#L166

We need to not do that for the root configDependencies.
