### ISSUE TITLE
can not require dynamic module

### ISSUE THREAD

**Issue by enginespot** [stealjs/steal#598]
when I tried to load module by the follow way , it does not work 
```
var module= "jquery";
require(module);
```

but  it works by the follow way

```
require("jquery");
```

**Comment by matthewp** [comment]
That's right, unlike in Node we have to load modules asynchronously in the browser. This means we have to parse `require` calls to know what should be loaded.  If you would like to dynamically load modules you can use `System.import`:

```js
var module = "jquery";

System.import(module).then(function($){
  // Got jquery
});
```
