### ISSUE TITLE
how to require a module with multiple files

### ISSUE THREAD

**Issue by enginespot** [stealjs/steal#599]
I install bower module , which main file maybe 
```
{
    main:[
        "main.less",
        "main.js"
    ]
}
```
then what is the best practice for using the module

I can use the module by the way:

bower.json
```
{
    "bowerIgnore":[
        "module"
    ]
}
```
and then 

var module = require("bower_components/module/module");
var module_css = require("bower_components/module/module.css");

a bit ugly, so is there any better way?

**Comment by matthewp** [comment]
This was answered [in gitter](https://gitter.im/stealjs/steal?at=56cf14ba12b251b950ee1854)

Can you post questions in the forums?  Makes it easier for other users to find answers to common questions: http://forums.donejs.com/c/stealjs
