### ISSUE TITLE
Feature Request, add stylus support

### ISSUE THREAD

**Issue by es6Test** [stealjs/steal#603]
I love stylus more than less, can we support it out of the box too?

**Comment by justinbmeyer** [comment]
@es6Test we are probably going to remove the "out of the box" support for less and instead require people use npm to install their favorite style engine.

Would you be interested in helping us create a `system-stylus`?

**Comment by es6Test** [comment]
sorry I'm pretty busy with work and stuff

**Comment by justinbmeyer** [comment]
@es6Test it's pretty easy.  Here's the sass one: https://github.com/stealjs/steal-sass/blob/master/main.js

You basically need to implement a translate hook.

**Comment by pYr0x** [comment]
@es6Test do you know a library for compiling stylus in the browser? Because that is needed for the development mode in steal.

**Comment by es6Test** [comment]
I'm not aware of any.

**Comment by justinbmeyer** [comment]
Never been to stylus's website before, but within a few seconds I found: http://stylus-lang.com/try.html.  This means that there's some build that works in the browser.

**Comment by justinbmeyer** [comment]
A quick google search turned up: http://stackoverflow.com/questions/11353296/client-side-usage-of-stylus-css .  One of the responses has instructions on how to build stylus for the browser.

**Comment by QuantumInformation** [comment]
Can the bulk of the sass code be modified to fit stylus? I have a client that uses stylus and would be nice to drop in steal.

**Comment by pYr0x** [comment]
there are 2 things we have to consider.
1. stylus should work on the browser so that we can load the file via XHR and transpile with stylus (browserversion)
2. we need to transpile the stylus code in node for bundling things together.

i dont think the steal-sass is actual a good module to copy.

**Comment by matthewp** [comment]
Issue moved to [stealjs/rfcs #11](https://github.com/stealjs/rfcs/issues/11) via [**ZenHub**](https://www.zenhub.com/)
