### ISSUE TITLE
NPM Module normalize.css not loaded correctly

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#604]
Reported here: https://gitter.im/stealjs/steal?at=56d0de584e6a6c1c18ecf881. There is an npm module called [normalize.css](https://www.npmjs.com/package/normalize.css) that does not get loaded correctly.

`Error Potentially unhandled rejection [5] Error: Error loading "normalize.css!$css"`

**Comment by es6Test** [comment]
normalize.css  has a main: entry point that returns a css file.

**Comment by pYr0x** [comment]
@phillipskevin @es6Test can you confirm that this issue still exits?

i tried a test with normalize.css and it works... 

your statement?

**Comment by phillipskevin** [comment]
normalize.css loads fine for me also. @es6Test can you try it out?

**Comment by pYr0x** [comment]
@es6Test @QuantumInformation i updated the fork of the vanilla cookbook.
https://github.com/pYr0x/vanillajs-cookbook/commit/4cb63f44e70a75d16923e75196f46c3241688ef4

i have 
- node 5.4.0
- npm 3.3.12
installed. still can load normalize.css without adding the `node_modules` folder in the import statement.

close this for now.
if you have still trouble please reopen or connect us on gitter.
