### ISSUE TITLE
require a .js file do not load the file correctly

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#606]
if you would require a .js file
```
var MySalute = require("./salute.js");
```

steal technically speaking stealjs/es6-module-loader does not load correctly the file.
because in the `path` object there is a 
```
this.paths = { '*': '*.js' };
```
https://github.com/pYr0x/es6-module-loader/blob/js-file-bug/src/system.js#L154

**Comment by matthewp** [comment]
Is this true if using the npm plugin?

**Comment by pYr0x** [comment]
what do you mean by "using the npm plugin"?

**Comment by matthewp** [comment]
If you're config is `package.json!npm` you are using the npm plugin and it's extension is added. I believe it's extension already allows you to include .js, but I could be wrong.

**Comment by pYr0x** [comment]
@matthewp with the usage of the NPM plugin the module file is loaded correctly by importing like
```
var MySalute = require("./salute.js");
```

but if i using not the NPM plugin like this:
```
<script src="node_modules/steal/steal.js" main="@empty" config-main="@empty">
        var MySalute = require("./salute.js");
        console.log(MySalute);
    </script>
```
steal throws an error 
`steal.js:2648 GET http://localhost:8080/salute.js.js 404 (Not Found)`

should we provide the same behavior with and without the NPM plugin?
if yes, how can i solve this problem? where do i have to look into?

**Comment by matthewp** [comment]
We could add that support, it would be a normalize hook that looks for .js and removes it (I suppose). Honestly, given how much we are pushing people to using npm, I don't know if it's worth the effort.

**Comment by pYr0x** [comment]
hello @matthewp 
i wrote a normalizer hook for this bug.
but i have one question.

first my hook:
```
/*
 SystemJS JS-File
 Load a .js file Node-like
 */
function addJS(loader) {
    if (loader._extensions) {
        loader._extensions.push(addJS);
    }
    var normalize = loader.normalize;
    loader.normalize = function(name, parentName, parentAddress, pluginNormalize){
        var extension = ext(name);
        if(extension === "js" && !this.hasOwnProperty('npmContext')) {
            name = name.substr(0, name.lastIndexOf("."));
        }
        return normalize.call(this, name, parentName, parentAddress, pluginNormalize);
    };

    return loader;
}
if (typeof System !== "undefined") {
    addJS(System);
}
```
very simple.

but the problem is, that `mapping` with `System.map` is not covered.
 ```
steal.config({
	map: {
		"hello.js": "./salute.js"
	}
});
```
with `import hello from "hello.js";` will not work.

i we will support mapping i have to copy the mapping algorithm from steal/systemjs map-extension
https://github.com/stealjs/systemjs/blob/master/lib/extension-map.js#L29-L122

this is bad, because it is duplicated code.

what do you think.. should we support mapping ?

**Comment by matthewp** [comment]
No, we don't support unnormalized names in map, the only exception is npm packages, so let's not add that code.

Can you put it inside here: https://github.com/stealjs/steal/blob/master/src/system-extension-ext.js

That will save us from adding another hook (another function call) for such a small thing, and that seems like an appropriate place anyways.

**Comment by matthewp** [comment]
Also, let's put this in 1.0.0, so PR against major.
