### ISSUE TITLE
Having to use full path when importing from node_modules.

### ISSUE THREAD

**Issue by QuantumInformation** [stealjs/steal#608]
I have a codebase using es6 imports and was previously built with webpack. However when stuff like this used to work with webpack/browserify, steal js tries to load it from the current directory, instead of the path ../../node_modules.

`import moment from 'moment'`

Will I have to specify the full relative paths? I tried import moment from `'../../node_modules/moment/moment'` but that doesn't work.

**Comment by pYr0x** [comment]
do you have `moment` in your package.json file as depencency?

**Comment by QuantumInformation** [comment]
Yes, I've now changed my file structure so that node_modules is a sibling of my entry point.

**Comment by marshallswain** [comment]
I think steal expects `node_modules` and `package.json` to be siblings.

**Comment by xtycz** [comment]
What if you are in a large project and you want to load stuff that is several folders above your current directory?

**Comment by matthewp** [comment]
As far as I am aware, package.json and node_modules are always siblings, I've never seen it not be the case.  You can do:

```js
<script src="../../node_modules/steal/steal.js"></script>
```

And it should load your packages defined in `../../package.json`, does it not do this?

**Comment by QuantumInformation** [comment]
So the current situation is that I am trying to do

 `import moment from 'moment'` in my project and it tries to load it from 

`http://localhost:63342/project-root/moment.js` 
instead of
'http://localhost:63342/project-root/node_modules/moment/moment.js'

**Comment by matthewp** [comment]
Do you have `moment` listed in your package.json?

**Comment by QuantumInformation** [comment]
Yes:

`  "dependencies": {
    "babel-polyfill": "^6.1.19",
    "moment": "^2.11.2",
    "normalize.css": "^3.0.3"
  },`

**Comment by QuantumInformation** [comment]
Separately I am also trying to introduce stealjs into a much larger codebase (although small area) and am trying this:

  `<script type="text/javascript" src="../node_modules/stealjs/steal.js"></script>`

but I am getting this failed request to  dev.js

```GET http://localhost:63342/fo-site-ui/src/components/native/node_modules/stealjs/steal/dev/dev.js ConfigManager.defaults.types.js @ steal.js:1349require @ steal.js:1266ConfigManager.require @ steal.js:1247h.extend.execute @ steal.js:1888(anonymous function) @ steal.js:1836h.each @ steal.js:40h.extend.loadDependencies @ steal.js:1835h.extend.executed @ steal.js:1718before_args @ steal.js:128before_args @ steal.js:128go @ steal.js:3153(anonymous function) @ steal.js:3164```

**Comment by matthewp** [comment]
@QuantumInformation I think you have installed `stealjs` which was deprecated. You should be installing `steal`.

**Comment by QuantumInformation** [comment]
@matthewp ah yes your right, still using steal for the original issue

**Comment by QuantumInformation** [comment]
By changing my import to 
`import moment from 'node_modules/moment/'` I got it to load.

I guess there would have to be a server step to get  it to load directly from

`import moment from 'moment'`

**Comment by matthewp** [comment]
That shouldn't be the case. I don't know what's going on in your setup that it's not loading moment from node_modules already.  Can you paste in your script tag?

**Comment by QuantumInformation** [comment]
Sure its:

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>Title</title>
  <script src="node_modules/steal/steal.js"
          data-main="app"
          data-config="./config.js"
  ></script>
</head>
<body>
<nav>
  <h1>Bookings calender</h1>
  <ul>
    <li><a href='#homepage'>home page</a></li>
    <li><a href='#bookings'>bookings</a></li> <!--todo after auth-->
    <li><a href='#signup'>sign up</a></li>
    <li><a href='#login'>log in</a></li>
  </ul>
</nav>
<div id="main"></div>
<footer></footer>
</body>
</html>
```

**Comment by matthewp** [comment]
Ah, ok, you are not using the npm plugin then. What does your config.js look like?

**Comment by QuantumInformation** [comment]
`System.bundle = ["homepage","signup","login"];`

**Comment by matthewp** [comment]
@QuantumInformation You can move that into your package.json:

```json
"system": {
  "bundle": ["homepage","signup","login"]
}
```

And then remove your config.js from your script tag, you don't need it.

**Comment by matthewp** [comment]
Closing for now, let me know if you still are having issues.

**Comment by QuantumInformation** [comment]
Thanks for your help.

Why do we need to put the bundle names in the system property in package.json? Wouldn't it be obvious that we want them in the import statement?

**Comment by matthewp** [comment]
If you are doing `import 'foo'` you don't have to add the bundles. The bundles are for progressive loading: `System.import('foo')`

**Comment by QuantumInformation** [comment]
thx, how do I load the npm plugin, not sure from reading http://stealjs.com/docs/npm.html

**Comment by matthewp** [comment]
If you do `<script src="node_modules/steal/steal.js"></script>` it will use the npm plugin and your package.json will be used.

**Comment by QuantumInformation** [comment]
I have a site at location ./root 

I am doing so in root/index.html : `<script src="node_modules/steal/steal.js"></script>`  and have a root/index.js which loads files with dependencies like 'moment'

I tried steal in a new project today and it loads loads everything from the root of the index page loading steal.

I guess it can't read package json's that are higher up the source tree than the immediate package.json(package.json1) (sibling to my index.html file loading steal).

Eg I have another package json that is ../../package.json (package.json2).

Only (package.json2) has the 'moment' dependency, do I also now need to add it to (package.json1).

Furthermore my index.js trying to `import import mockApi from '../mocks/mockApi';` but in the browser is its trying to load `root/mocks/mockApi'`` instead of /mocks/mockApi';`

hope that makes sense

**Comment by QuantumInformation** [comment]
Would probably help if a more big real word example in github so I can get a better grip on how to wire it all up.

**Comment by matthewp** [comment]
@QuantumInformation There are several, here's a good one: https://github.com/donejs/chat/blob/master/package.json

The dependencies need to be the package.json located at (relative to steal.js) `../../package.json` if that makes sense.

**Comment by QuantumInformation** [comment]
So npm the dependencies are now loading from node_modules now I added them to the steal relative package (thanks). Still having issues with trying to load upper level paths
eg
`var Component = require('../../component');`
always loads in browser like 
`var Component = require('./component');`
Will try some other things today and will report back.

**Comment by QuantumInformation** [comment]
The reason I'm pointing upwards is because I'm introducing steal as part of a much larger project so it can't be at the top level. Maybe its cause I'm testing locally in webstorm and it can't figure out how to resolve paths like `../`

**Comment by justinbmeyer** [comment]
You can't load modules above the base package.json's folder.

**Comment by QuantumInformation** [comment]
Ah I see, I'm afraid I can't really use in in this use case then.

**Comment by marshallswain** [comment]
Maybe you can symlink the upper level packages?

**Comment by justinbmeyer** [comment]
@QuantumInformation why do you need to do this?  Even in larger projects, you should be able to move the dependencies within your baseUrl.

You could use a path config to load those modules from anywhere.
