### ISSUE TITLE
possible bug with progressively fetch package.json

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#616]
this demo breaks with steal 0.14.1
but works with steal 0.13.2

simple demo:

**package.json**
```
{
  "name": "test",
  "version": "1.0.0",
  "description": "",
  "main": "main.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "steal": "^0.14.1",
    "steal-sass": "^1.0.2"
  },
  "system": {
    "directories": {
      "lib": "src"
    },
    "npmAlgorithm": "flat"
  }
}
```

**src/main.js**
```
import "./style.scss!";
````

**src/style.scss**
```
body {
  background-color: blue;
}
```

**the error with steal 0.14.1**
![image](https://cloud.githubusercontent.com/assets/1126711/13543269/e00f7e22-e269-11e5-9fee-1d28e81bc2fc.png)
the package.json from steal-sass is loaded successfully

**Comment by matthewp** [comment]
Do you remember what this was about? Was this related to some steal-sass configuration?

**Comment by pYr0x** [comment]
closing this, i think it is a steal-sass issue
