### ISSUE TITLE
[QUESTION] Is typescript a valid option for integration to stealjs?

### ISSUE THREAD

**Issue by QuantumInformation** [stealjs/steal#617]
I am an avid typescript user. Is there any way to integrate typescript to stealjs?

**Comment by justinbmeyer** [comment]
If there's a way to load typescript in the browser, then yes, there are easy ways of integrating typescript into stealjs.  Please checkout other language adaptors like https://github.com/ilyavf/steal-coffee

**Comment by matthewp** [comment]
Let me know if you find anything, I'd like to add logos of supported technologies to stealjs.com

For general questions http://forums.donejs.com/ is a good place to ask them.
