### ISSUE TITLE
Issue with import of bablified __esModule

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#619]
Module made with `babel5` contains such code:
```js
'use strict';
Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.x = 1
```

if then import this module with Steal
```js
var m = require('module')
// or import m from 'module'
```
`m` is `undefined`

if to import this `module` in `node` `m` contains `x` (`m.x === 1`)

As workaround this works:
```js
import * as m from 'module'
```

This this article explains how this work in babel
http://www.2ality.com/2015/12/babel-commonjs.html

**Comment by pYr0x** [comment]
so this isn't really a steal issue?

**Comment by whitecolor** [comment]
I think yes @matthewp

**Comment by matthewp** [comment]
The interop situation is clearly not right, let's move all of that discussion into https://github.com/stealjs/steal/issues/551
