### ISSUE TITLE
Can not load `snabbdom-to-html` module

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#623]
```
npm i snabbdom-to-html -save
```

```HTML
<script src="../node_modules/steal/steal.js" main="@empty">
  import 'snabbdom-to-html'
</script>
```

App does not loads with error in console:
```
GET http://localhost:7000/node_modules/snabbdom-to-html/lib/lib.js 404 (Not Found)fetchTextFromURL @ steal.js:2648(anonymous function) @ steal.js:2823init @ steal.js:377Promise @ steal.js:365$__Object$defineProperty.value @ steal.js:2822loader.fetch @ steal.js:3637loader.fetch @ steal.js:4687loader.fetch @ steal.js:4787System.fetch @ npm-extension.js:274(anonymous function) @ steal.js:1525tryCatchReject @ steal.js:1183runContinuation1 @ steal.js:1142Fulfilled.when @ steal.js:930Pending.run @ steal.js:821Scheduler._drain @ steal.js:97Scheduler.drain @ steal.js:62run @ steal.js:268
steal.js:2648 GET http://localhost:7000/node_modules/snabbdom-to-html/lib/lib/index.js 404 (Not Found)fetchTextFromURL @ steal.js:2648(anonymous function) @ steal.js:2823init @ steal.js:377Promise @ steal.js:365$__Object$defineProperty.value @ steal.js:2822loader.fetch @ steal.js:3637loader.fetch @ steal.js:4687loader.fetch @ steal.js:4787System.fetch @ npm-extension.js:270(anonymous function) @ npm-extension.js:293tryCatchReject @ steal.js:1183runContinuation1 @ steal.js:1142Fulfilled.when @ steal.js:930Pending.run @ steal.js:821Scheduler._drain @ steal.js:97Scheduler.drain @ steal.js:62run @ steal.js:268
steal.js:140 Potentially unhandled rejection [4] Error loading "snabbdom-to-html@2.1.3#lib/lib" at http://localhost:7000/node_modules/snabbdom-to-html/lib/lib.js
Error loading "snabbdom-to-html@2.1.3#lib/lib" from "undefined" at <Anonymous Module 1>
Not Found: http://localhost:7000/node_modules/snabbdom-to-html/lib/lib/index.js (WARNING: non-Error used)
```
![image](https://cloud.githubusercontent.com/assets/736697/13765132/210e56c6-ea78-11e5-83c8-8bcdea63f5c8.png)

**Comment by pYr0x** [comment]
sorry, don't get it...
the package.json from `snabbdom-to-html` is loaded? 
is the ´main` in this package right? which js file should be loaded?

**Comment by whitecolor** [comment]
The problem that `browser` field was changed from `lib` --> `lib/`
https://github.com/acstll/snabbdom-to-html/commit/02f65cbf4e2077547dcbad9bc48dc972a19e0a0e#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L6

**Comment by whitecolor** [comment]
so steal tries to load `lib/lib.js` but should load `lib/index.js` (like nodejs does)

**Comment by matthewp** [comment]
Thanks, we can probably detect this and load lib/index.js.

**Comment by pYr0x** [comment]
@matthewp i will write a test, can you give me a short brief, where i have to look into, to fix this?

**Comment by matthewp** [comment]
@pYr0x I'm not 100%, but i  think it's happening here: https://github.com/stealjs/system-npm/blob/master/npm-utils.js#L258  If pkg.browser ends with `/` we can make that be `/index`

**Comment by matthewp** [comment]
I think before you worked on the npm stuff and were editing `steal/ext` but we develop the npm plugin in the system-npm repo, what's in steal/ext is just copied over.

**Comment by pYr0x** [comment]
@matthewp why do we not use sytem-npm as a submodule?

**Comment by matthewp** [comment]
Bad experiences with submodules mainly :)  The process is:

1. Make test / fix in system-npm
2. Merge to master and cut a release of system-npm
3. Send PR to stealjs/steal with the new version of system-npm

Maybe in some distant future version of steal we'll only support npm as the config in which case it might make sense to move the code to core... but for now this is how we've been doing it.

**Comment by whitecolor** [comment]
Should work for steal now?

**Comment by matthewp** [comment]
Yep, in 0.15.1

**Comment by whitecolor** [comment]
cool, thanks)
