### ISSUE TITLE
[QUESTION] How to have good debugging experience?

### ISSUE THREAD

**Issue by QuantumInformation** [stealjs/steal#626]
One of the reasons I came to steal was my awful time with files in chrome created by webpack. But I am also having real bad issues with the traceur output that is steal hands to me. Hardly any of my breakpoints get hit in my project running in chrome and firefox and the behavior is erratic.

Any tips how to have good debugging experience?

**Comment by marshallswain** [comment]
Are you hoping to better debug a build of your project, or the browser-loaded version?

**Comment by QuantumInformation** [comment]
browser-loaded, I'm trying switching to babel right now to see if it helps.

**Comment by QuantumInformation** [comment]
Hmm.. no luck with babel either. Sometimes all this es6 debugging stuff makes me just want to go back to pure concatenated js.

**Comment by justinbmeyer** [comment]
I use steal and debug every day. I've never really had this problem with the source maps. 

Can you provide an example of source that is not working?

**Comment by justinbmeyer** [comment]
Imo, going back to concatenation JS ignores the fact that module loaders provide a lot of value on top of just being able to transpile ES6. 

Use AMD format if inaccurate maps are the problem.

**Comment by marshallswain** [comment]
@QuantumInformation I have some time today if you want to pair to get it figured out.  Send me an email if you want to.

**Comment by QuantumInformation** [comment]
I'm not using source maps, all my files are loaded on the fly. 
@marshallswain thanks I'll be in touch!

**Comment by justinbmeyer** [comment]
We still generate source maps when files are loaded by the browser.

**Comment by QuantumInformation** [comment]
Well after about 30 seconds, Marshall managed to help me find the issue. I had a rouge config file that was causing some weird side effects, I think it stopped the npm plugin loading or something.

**Comment by QuantumInformation** [comment]
@justinbmeyer is there w way to force the babel sourcemaps to be inline, having some issues with chrome caching them like crazy!

**Comment by QuantumInformation** [comment]
Reopened as still having issues. Will keep playing.
