### ISSUE TITLE
requires/imports in modules mapped using `paths`

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#629]
I have a module that is located in `../node_modules/shared-module/module.js` relative to baseURL.
and inside this 
`module.js`:
```js
require('can/')
require('jquery')
```

before 0.14 I use this `map` in `package.json system`:
```
"./shared": "../node_modules/shared-module",
```
and I could do, inside my app:
```js
require('shared/module')
```
And it worked. After update to 0.14 this mapping stoped to work, adviced to change in favor of `paths`:
```
"./shared/*": "../node_modules/shared-module/*.js",
```
it loads `module.js` but it can't load `can` and `jquery` it tries to load it not from `base/node_modules/can/canjs` but from `base/can.js` and `base/jquery.js` 

is it correct behaviour?

**Comment by pYr0x** [comment]
not really, can you please post the  `System.path` and `System.map`

**Comment by whitecolor** [comment]
I have only system paths now
`/client/package.json.json`
```
"./shared/*": "../node_modules/shared-module/*.js",
```
this is where module is located:
`/node_modules/shared-module/module.js`:
```js
require('can/')
require('jquery')
```

Iside my I app I do
```
require('shared/module') /// it loads `/node_modules/shared-module/module.js
```

and error can tries to be loaded from `client/can.js` and jquery `client/jquery.js`

**Comment by pYr0x** [comment]
i meant  `System.path` and `System.map` from the browser console

**Comment by matthewp** [comment]
If you still need this, will need some more info. Closing as I don't think you're a Steal user any more :(
