### ISSUE TITLE
baseURL is set wrong if using bundleSteal in production

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#630]
when using `bundleSteal=true` on the build. we set things like this:
```
steal.loadBundles = true;
steal.baseURL = './';
steal.configMain = "package.json!npm";
```
but the `baseURL` is overwritten by `stealURL` setter function.
https://github.com/stealjs/steal/blob/22c4ee67285d0d5a3c4a47d4673757c64b415fbf/src/config.js#L230
https://github.com/stealjs/steal/blob/22c4ee67285d0d5a3c4a47d4673757c64b415fbf/src/config.js#L331

it also sets unneccesary paths when we using steal production
https://github.com/stealjs/steal/blob/22c4ee67285d0d5a3c4a47d4673757c64b415fbf/src/config.js#L270

**Comment by matthewp** [comment]
We should probably be checking if baseURL already exists, and only set it if not.

**Comment by pYr0x** [comment]
@matthewp what do you thinking about
``` 
		if(typeof config === 'object'){
			// the url options are the source of truth
			config = extend(config, urlOptions);
		}else{
			config = urlOptions;
		}

		// set the config
		System.config(config);
```
instead of
https://github.com/stealjs/steal/blob/master/src/startup.js#L47-L53

**Comment by matthewp** [comment]
Let me know if that works. It might be ok, scares me just a little bit. Would like to see if the tests all pass (and if the steal-tools tests all pass with it).

**Comment by pYr0x** [comment]
steal 0.15.2 and steal-tools 0.15.5 now setting env to production if steal is bundled
https://github.com/stealjs/steal/pull/635
https://github.com/stealjs/steal-tools/pull/425
