### ISSUE TITLE
Setting configPath via steal var fails since 0.14

### ISSUE THREAD

**Issue by robertheessels** [stealjs/steal#631]
In my project use this code to set the configPah:

```
var steal = {

"configPath":"http:\/\/rhwp.bullpool.com\/wp-content\/themes\/swifty-site-designer\/ssd\/js\/stealconfig.js",

"main":"..\/preview.js?swcv=ssd_\/*@echo RELEASE_TAG*\/",

"bundlesPath":"http:\/\/rhwp.bullpool.com\/wp-content\/themes\/swifty-site-designer\/ssd\/js"

};
```

This used to work (0.13.2 and older), but fails since 0.14.

**Comment by matthewp** [comment]
Thanks, this is production, right? You said you get an error that it can't find stealconfig.js? What does your script tag look like?

**Comment by robertheessels** [comment]
It is in dev. Not sure if it would work in production.

My stealconfig.js file is (and needs to be) located 1 level lower than steal expects it to be.

Script tag:
`
< script type="text/javascript" src="http://rhwp.bullpool.com/wp-content/themes/swifty-site-designer/ssd/js/libs/steal/steal.js?swcv=ssd_%2F%2A%40echo+RELEASE_TAG%2A%2F&amp;ver=1.0"></script>
`

Both this script tag and the var steal= code above is generated by WordPress code in PHP, that's why it looks a bit weird.

**Comment by pYr0x** [comment]
@robertheessels can you post the URL steal would like to load ?

**Comment by robertheessels** [comment]
steal - error loading @config. Error loading "stealconfig.js" at http://rhwp.bullpool.com/wp-content/themes/swifty-site-designer/ssd/js/libs/stealconfig.js
Not Found: http://rhwp.bullpool.com/wp-content/themes/swifty-site-designer/ssd/js/libs/stealconfig.js

So the /libs is here incorrect.

(steal itself is in http://rhwp.bullpool.com/wp-content/themes/swifty-site-designer/ssd/js/libs/steal)

**Comment by pYr0x** [comment]
@matthewp i am a little bit confused.
lets say we have this folder structure
![image](https://cloud.githubusercontent.com/assets/1126711/14032327/49f9166a-f212-11e5-8120-0a0cb15e8ff4.png)
and **bar.html** looks like

**Comment by robertheessels** [comment]
Sorry, I do not fully understand what you mean.

The inclusion is inside a CMS so there is no static path to the html page containing steal include. So the base url can be any url. So steal and main must be loaded from a static path; not relative to the html file path.

**Comment by pYr0x** [comment]
can we close this?

**Comment by matthewp** [comment]
This will be released on Monday, let's close then.

**Comment by robertheessels** [comment]
So, it's fixed? You guys rock!

**Comment by pYr0x** [comment]
close #653

**Comment by matthewp** [comment]
Re-opening since we are going to have to revert the change for now.

**Comment by pYr0x** [comment]
There is a test for that issue https://github.com/stealjs/steal/tree/major/test/stealconfig
The test pass with the new startup config
So close this
