### ISSUE TITLE
[QUESTION] how to load custom file extension like .es6

### ISSUE THREAD

**Issue by QuantumInformation** [stealjs/steal#638]
I am trying to use steal in a large codebase where some of the js files have a .es6 file extension. If I try import such a file from steal:

`import Calendar from './calendar.es6';`

However it tries to load `calendar.es6.js` in the browser and failing.

**Comment by pYr0x** [comment]
http://stealjs.com/docs/System.ext.html

**Comment by QuantumInformation** [comment]
Thanks, although it can be useful to have common questions addressed in the repo for search indexing, as saves us having to go search in an external forum.

**Comment by QuantumInformation** [comment]
I'm not sure how to set this up in package.json, I tried
```js
  "System": {
    "transpiler": "babel",
    "ext": {
      "js": "$es6"
    }
  }```
and ` "es6": "$js"`
