### ISSUE TITLE
main attribute requested even with bundleSteal

### ISSUE THREAD

**Issue by cherifGsoul** [stealjs/steal#641]
for production I use ```bundleSteal:true``` but in the console I have a warning: ```Attribute 'main' is required in production environment. Please add it to the script tag.``` Im using ```steal 0.15.2``` and ```steal-tools 0.15.11```, if steal is bundled no need for ```main``` attribute with the script tag.

**Comment by pYr0x** [comment]
i dont think you have to skip the `main`... as i mean, you have to add a `main` attribute also if you bundle steal

**Comment by cherifGsoul** [comment]
@pYr0x that was quick :+1:
