### ISSUE TITLE
use jsonOptions also for package.json

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#643]
this PR (https://github.com/stealjs/steal/pull/591) addes a nice feature for adding a `jsonOptions` method to the build.
but it seems, that this system-json module is missed in the `main.js´ so the build will not work that way...

is there a test in steal-tools that covers that feature?

also if i added 
```
var system = {
		config: __dirname + "/package.json!npm",
		jsonOptions: {
			transform: function(load, data) {
				delete data.foo;
				return data;
			}
		}
	};
```
this wont work in a steal-tools build

**Comment by matthewp** [comment]
Does this problem still exist @pYr0x ? I thought I remembered us talking about it, but can't recall if we resolved this or not.

**Comment by pYr0x** [comment]
so i review that issue and found out the main problem:
the docs http://stealjs.com/docs/System.jsonOptions.html#section_Use are saying:

> jsonOptions is useful when your app (or one of your dependencies is importing a JSON file that isn't meant to be exposed in production. For example many packages do:

var pkg = require("./package.json");

so i was thinking the application package.json file that is used for build will run though that `transform` method:
```
var stealTools = require("steal-tools");

var buildPromise = stealTools.build({
	config: __dirname + "/package.json!npm",
	main: "stealt/main",
	jsonOptions: {
		transform: function(load, json){
			delete json.name;
			return json;
		}
	}
}, {
	minify: false
});
```
but is was not. so the docs are a little bit confusing me. so the `jsonOptions` config will never use a package.json file from a module dependency.

jsonOptions will only work if i have in my app something like this:
```
var content = require("./a-json-file.json");
console.log(content);
```
with steal-tools only this json-file goes though the `jsonOptions`. 

but i think it would be nice to run that `jsonOptions` also though the package.json file that will be bundled into the build-file. because that package.json file can be very long and can have infomation that we dont need in production mode. are you with me @matthewp ?

otherwise we can document that feature better and close this issue

**Comment by matthewp** [comment]
> because that package.json file can be very long and can have infomation that we dont need in production mode. are you with me @matthewp ?

Yeah, I know what you mean. You have to be careful though, a lot of that information *is needed* in production. In your example, the `browser` config isn't needed, but the `envs.server-production` config *is*, so you'd have to be careful that you don't accidently exclude parts that are needed.  However, if you want to update system-npm to check for jsonOptions.transform that's ok. I believe [here](https://github.com/stealjs/system-npm/blob/38f2403300ffd323e90e6beecf3447beaff06301/npm-load.js#L50), `context.pkgInfo` is what gets saved out, so that's probably the place to do it.

**Comment by pYr0x** [comment]
done in steal-systemjs
have to be updated and maybe documented

**Comment by pYr0x** [comment]
closed https://github.com/stealjs/steal-tools/pull/511
