### ISSUE TITLE
Exception thrown in Chrome when Sidekick extension is installed

### ISSUE THREAD

**Issue by ericcarino** [stealjs/steal#644]
On Chrome, when users enable the "Sidekick by Hubspot" extension, Steal throws an uncaught exception.  This causes our app to fail loading.  Only happens when Steal is bundled with the application.
http://www.getsidekick.com/

```
steal.production.js:6 
Potentially unhandled rejection [37] Error loading ...

steal.production.js:6 
Potentially unhandled rejection [41] Error loading ...

```
Steal: 0.13.0
Steal-Tools: 0.13.2
_but also reproducible in latest versions_

You can easily reproduce by creating the Hello World app instructed here: http://stealjs.com/docs/StealJS.quick-start.html  The only one change you need to make is to set the bundleSteal option to true.

The problem appears to be due to the extension injecting a script tag.  It's breaking this part of the code (sorry that it's the minified version).

`        var O = function() {
            var a = {}
              , b = document.getElementsByTagName("script")
              , e = b[b.length - 1];
            if (e) {
                a.stealURL = e.src,
                d(e.attributes, function(b) {
                    var d = c(0 === b.nodeName.indexOf("data-") ? b.nodeName.replace("data-", "") : b.nodeName);
                    a[d] = "" === b.value ? !0 : b.value
                });
                var f = e.innerHTML.substr(1);
                /\S/.test(f) && (a.mainSource = f)
            }
            return a
        }
`

In the 'b' array, the "steal script tag" is not at the end, the extensions injected script tag is.

**Comment by pYr0x** [comment]
will be fixed in steal 1.0
