### ISSUE TITLE
Problem using steal >= 0.13 with bit-c3

### ISSUE THREAD

**Issue by ccummings** [stealjs/steal#658]
while using bit-c3 with steal >= 0.13, I get a ton of errors:
- steal attempts to load `browser-request` from `jsdom` because it has a `browser` mapping for it.
- It also starts trying to load native node packages `fs`, `path`, etc

Example repo: https://github.com/ccummings/c3-steal-error

## To Reproduce:
- `npm i` in root folder
- Spin up local server in root directory (http-server or whatever)

**Error happens with npm2.x and npm3.x**

**Comment by matthewp** [comment]
So probably because of progressively fetching package.jsons.  Will take a look at your repo, thanks.

**Comment by matthewp** [comment]
https://github.com/stealjs/system-npm/issues/121
