### ISSUE TITLE
Incorrect fetch addresses in NWJS and Electron

### ISSUE THREAD

**Issue by ab335** [stealjs/steal#668]
Using the getting started example with a JQuery import:

With a local http server, StealJS fetches correctly the following file:
`http://localhost:8080/node_modules/jquery/dist/jquery.js`

However, in NWJS it tries to fetch JQuery at an incorrect location:
`chrome-extension://pdkibmafgbmokolcamibpckmfdgikhka/jquery@2.2.3%23dist/jquery.js`
It should be:
`chrome-extension://pdkibmafgbmokolcamibpckmfdgikhka/node_modules/jquery/dist/jquery.js`:

As well as in Electron, with the following incorrect location:
`file:///C:/Users/ab335/Desktop/Project/jquery@2.2.3%23dist/jquery.js`
It should be:
`file:///C:/Users/ab335/Desktop/Project/node_modules/jquery/dist/jquery.js`

**Comment by pYr0x** [comment]
use used steal-tools to make a build?

**Comment by ab335** [comment]
No, it only uses _steal_ to serve the different modules, exactly as in the documentation, and without any build process.
 
SystemJS can import modules without any issue within nwjs and electron, so I was also expecting _steal_ to fetch correctly the modules there, but apparently the addresses are not being translated correctly somewhere in _steal_ when it runs into those environements.

I think a fix could make it work both in nwjs and electron, as the issue seems to be the same in both environments, but am not sure where it really takes place.

**Comment by ab335** [comment]
With the http server, the return location of [SystemLoader.prototype.locate](https://github.com/stealjs/steal/blob/master/steal.js#L2812) is:

`http://localhost:8080/jquery@2.2.3%23dist/jquery.js`

But then it gets somehow translated into:
`http://localhost:8080/node_modules/jquery/dist/jquery.js`

That should be the place to look at, in order to make it work within nwjs and electron, but am not finding the exact location in the code where it happens.

**Comment by ab335** [comment]
I do not know how to do a pull request, so I'm putting here the fix proposal for [npm-extension.js](https://github.com/stealjs/steal/blob/master/ext%2Fnpm-extension.js#L210) 
```
// If locate didn't do the expected thing then we're going
// to guess that we shouldn't perform NPM lookup on this
// module as there might be a wildcard path.
if(address !== expectedAddress + ".js" &&
   address !== expectedAddress &&
   address.indexOf("*")!==-1) {
	return address;
}
```
