### ISSUE TITLE
Plugins configuration

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#671]
This is meant to replace #414 I have this partially implemented in the [modules branch](https://github.com/stealjs/steal/tree/modules).  Here's a sample of how it works:

``` json
{
  "system": {
    "plugins": {
      "*.js": [
        "foo-plugin"
      ]
    }
  }
}
```

Where `foo-plugin` looks like:

``` js
var dep = require("some-npm-dep");

exports.locate = function(locate, load){
  return 'foo://' + load.name;
};
```

The idea is that you can use wildcard matches to have the plugin be applied to only certain types of modules.
## Goal

The primary goal of this feature is to provide a way to write extensions to Steal that can have NPM dependencies. Currently we have 2 classes of extensions:
1. **Extension** that can override loader hooks by wrapping these hooks. These either have to be built into Steal (and therefore be a blessed plugin) or added as `configDependencies`.  The disadvantage there is that configDependencies cannot have have npm dependencies because they are loaded by NPM is configured.
2. **Plugins** are those that are used by the bang syntax or `ext` config. These are good for translating to JavaScript but cannot be used against JavaScript modules. 
## Use case

Any community idea could be implemented using this plugin config. An example is steal-conditional which is not (yet) part of Steal core and is awkward to use because of that.

Another example is transpilers. Upgrading our versions of traceur/babel is a real pain right now because you have to update steal-systemjs which uses them, steal which has the transpiler source, and transpile which use them for the build.  If it were an external plugin it would be much easier to maintain as you'd only have to update that project and would have the same export type in the browser and during the build.
## Plan

I would like to get this out in a prerelease so people can try it out. There needs to be tests added and there's one action point I'm unsure about:
- Should plugins config apply only to the top-level project or should a dependency be able to load plugins. If a dependency is able to load plugins do those plugins run against all modules or just the modules within its package?

**Comment by matthewp** [comment]
cc @pYr0x @justinbmeyer

**Comment by matthewp** [comment]
> Should plugins config apply only to the top-level project or should a dependency be able to load plugins.

My instinct is to make them only be set by top-level packages. There might be use cases for dependencies to load plugins but I cannot think of any right now.  My worry is, what if a dependency uses a transpiler plugin, would we want that plugin to be loaded *on top of* the plugin the root project is already using? I don't think we would.

**Comment by justinbmeyer** [comment]
A dependency should be able to load a plugin.  Why wouldn't it?  Say I wanted to use bootstrap, which uses the less plugin, I shouldn't have to load less myself.

**Comment by matthewp** [comment]
My concern is that we'll wind up loading 5 javascript transpilers because 1 dep uses traceur, another uses the babel plugin version 0.1.0, another version 0.2.0, etc.  Maybe we could have something like a `devPlugins` config that works like the `plugins` config but only applies when you are the root package.

**Comment by pYr0x** [comment]
@matthewp as i can see. there a only a few hooks that can be used by a plugin.
can you explain (in short) what are the hooks for
https://github.com/stealjs/steal/blob/8394a50f919041cf01c44c5673edbf01678de257/src/system-extension-plugins.js#L36-L42

**Comment by matthewp** [comment]
Those are all of the normal loader hooks that our extensions use today.  Will need to document them but in short:

* normalize: takes the import string like `'./foo'` and translate it to a full module name like `app@1.0.0#foo`
* locate: specifies where the module is located like `http://example.com/foo.js`
* fetch: fetches the module using XHR, script inject, fs.readFile in Node, or whatever else
* instantiate: This is a slightly weird one, but you specify the module's dependencies and a function that when executed will get the module's value. See [system-json](https://github.com/stealjs/system-json/blob/master/json.js#L61) for an example usage.

**Comment by justinbmeyer** [comment]
> Loading 5 javascript transpilers because 1 dep uses traceur, another uses the babel plugin version 0.1.0, another version 0.2.0, etc.

Better than not being able to load at all.

**Comment by pYr0x** [comment]
@matthewp is this plugin feature reasonably ready? can i try to refactor steal/sass with this new plugin api?

**Comment by matthewp** [comment]
The API is ready, it's not ready in terms of will be released any time soon.  But if you want to experiment and see if there are issues, I think that would be valuable.

I created one example plugin here that you can use as reference: https://github.com/stealjs/steal-buble

**Comment by matthewp** [comment]
This particular API of the "plugins" idea is being dropped. Below is a summary of the issues with this API and a proposed way forward.

# Problems

## Performance

The plugins idea worked by blocking loading so that plugins are loaded after the `steal.loader.configMain` but before `steal.loader.main`. This adds a 3rd layer of loading, causing the main to be loaded more slowly. Due to poor performance of loading steal in development mode, I don't think it's wise to add an API based on slowing it down even more.

## Plugin Inception

A major technical challenge is getting around the fact that plugins block JavaScript from loading. By blocking JavaScript from loading plugins block *themselves* from loading.

Steal has the ability to clone it's loaders. This way you can configure different loaders for different purposes. Classic `!` style plugins are loaded through a `pluginLoader`, for example. The way to fix the issue would be to use a plugin loader to load the plugins, that way they are not blocked by plugins config.

However, when you clone the loader you don't get all of the npm configuration with it. The `steal-clone` module provides that capability. To do this we'd need to pull steal-clone into core, which I guess isn't *too* bad. But steal-clone is currently a bit buggy.

# Future

Meanwhile, well after this feature was worked on, we added a `plugins` configuration to provide a way to pre-load plugins (regular bang plugins) like `steal-css`. All this does is fetch the package.json.

I think the future of a plugins sort of idea would be to extend this behavior and provide a way to actually run code, probably by making that module part of the `configDependencies`. For example, let's say you had:

```json
"steal": {
  "plugins": ["steal-babel"]
}
```

And then steal-babel had 

```json
{
  "steal": {
    "isPlugin" true
  }
}
```

Or something to that effect (almost definitely not that name 😅). Then the plugin would effectively be loaded as a configDependency.

This gets around the performance issue because we are not adding a new layer of preloading, but rather using configDependencies which already exists.

This would mean that plugins can't have npm dependencies. I think it's worth that tradeoff, just bundle your dependencies if needed.

-----

I'm closing this issue as we are not going to pursue this API any further. Since this is a rather large change I would prefer that future APIs go through the [Steal RFCs](https://github.com/stealjs/rfcs) process so that it can be discussed more in depth.

**Comment by pYr0x** [comment]
> This would mean that plugins can't have npm dependencies
what do you mean by this? steal-react cant depend on react-dom?

**Comment by matthewp** [comment]
No, I don't mean that. steal-react, steal-css, any of those types of plugins can continue to work exactly like they do today. This is about the other sort of "super dependency" plugins. These are plugins that have to run before your `main` runs. Anything that operates on `.js` files would need to be a super plugin.
