### ISSUE TITLE
Logging error when the config doesn't load.

### ISSUE THREAD

**Issue by mjstahl** [stealjs/steal#675]
https://github.com/stealjs/steal/blob/master/src/startup.js#L95

Should we doing this? I would think not.

I think the bigger question is... if we can't load the config is this an error case that the programmer definitely needs to fix. If so, we shouldn't allow steal to continue on.

If not being able to load the stealconfig is not that big of deal, we may not want output anything to the console.

**Comment by matthewp** [comment]
Yeah, I agree, handling that error doesn't make sense. If the app fails to load a config it shouldn't continue on.

**Comment by pYr0x** [comment]
fixed in major branch
