### ISSUE TITLE
Bug with loading can-fixture and can-define/map

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#682]
My file:

```
var fixture = require("can-fixture");
var DefineMap = require("can-define/map/map");
```

This loads `can-util/package.json` over and over and over again:

![localhost_8080_can-todomvc_index_html](https://cloud.githubusercontent.com/assets/78602/15050969/0711d2f4-12bc-11e6-991a-f532d2b570ca.png)

I thought it might be because Promise is overwritten, or that fixture's XHR is involved.  Removing both still breaks things.  

Investigating.

**Comment by justinbmeyer** [comment]
The problem seems to be an issue when there are two `can-util`'s being loaded.  One is nested within another package.

**Comment by justinbmeyer** [comment]
a clean install fixed the problem. Closing, but maybe something to take a look at eventually.  We should make it work or error better.

**Comment by matthewp** [comment]
If you provide steps to reproduce I can see about making the error better, or why it is doing infinite recursion (shouldn't).

**Comment by justinbmeyer** [comment]
Yeah, unfortunately, I cleared my environment.  I'll keep an eye out if it ever happens again.
