### ISSUE TITLE
Make jsx enabled by default

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#686]
It's not currently.

http://stealjs.com/docs/System.babelOptions.html

**Comment by pYr0x** [comment]
but the default transpiler is tracer?
and we have steal-jsx? that provide a transpiling for jsx?

**Comment by matthewp** [comment]
The default will be Babel in 1.0 since it's far more popular.  steal-jsx is for `.jsx` files but Babel will transpile jsx in normal `.js` files as well.  You can get this to work by setting the blacklist to an empty array (see the docs above) but I think it's popular enough that it should be enabled by default.

**Comment by pYr0x** [comment]
sice you are planing bable to be the default transpiler, should we upgrade to bable 6? and have a look if we found a good browser version of bable?

**Comment by matthewp** [comment]
Yeah, that's been worked on partially. Look at https://github.com/stealjs/steal/issues/546  we can discuss it further there.

**Comment by matthewp** [comment]
This is taken care of in our es6ml fork: https://github.com/stealjs/es6-module-loader/blob/base/src/transpiler.js#L96-L103

So assigning to myself.

**Comment by matthewp** [comment]
Closed by #732
