### ISSUE TITLE
`Cannot read property 'match' of undefined` - built version in browser

### ISSUE THREAD

**Issue by whitecolor** [stealjs/steal#689]
steal 0.16.0
here: `!!process.platform.match(/^win/),j=`

![image](https://cloud.githubusercontent.com/assets/736697/15148150/67557d76-16dd-11e6-94fd-21f45404eafb.png)

Crete one more time:
https://github.com/stealjs/steal/issues/448

**Comment by pYr0x** [comment]
dont think this is a steal bug....
let us know if you found out the module that require the process module

**Comment by matthewp** [comment]
Please don't create bugs for things you already know have issues.

**Comment by whitecolor** [comment]
just to notice that it should be fixed.
