### ISSUE TITLE
Wrong extraction of script content?

### ISSUE THREAD

**Issue by tschoening** [stealjs/steal#698]
I was using steal 0.4.0, upgraded to 0.16.10 today and ran into the problem that the following `script` block embedded into my HTML document produced an error:

    <script src="/de.am_soft.sm_mtg.frontend.bug2187/js/lib/bower_components/steal/steal.js" type="text/javascript" charset="UTF-8" data-config="/de.am_soft.sm_mtg.frontend.bug2187/js/config/stealConfig.js" data-main="main" data-env="development">/*<![CDATA[*/ /*]]>*/</script>

The error was:

    Uncaught SyntaxError: Unexpected token *

and while debugging I found that the following was executed:

    *<![CDATA[*/ /*]]>*/

The debugger showed some additional strings added at the end, but the point is the leading `*`, which is wrong JS syntax. I tested a bit with my server side Java code adding that tag and found that it seems that steal is always removing the first character of the text of the script tag, in the case above the `/´, leading to the wrong syntax. So I simply prepended a space character before `/*` and everything works as before now:

    <script src="/de.am_soft.sm_mtg.frontend.bug2187/js/lib/bower_components/steal/steal.js" type="text/javascript" charset="UTF-8" data-config="/de.am_soft.sm_mtg.frontend.bug2187/js/config/stealConfig.js" data-main="main" data-env="development"> /*<![CDATA[*/ /*]]>*/</script>

This very much looks like a parsing error in steal and in fact there are two places around dealing with the content of the `script` tag, where the first character is removed:

	var getScriptOptions = function () {

		var options = {},
			parts, src, query, startFile, env,
			scripts = document.getElementsByTagName("script");

		var script = scripts[scripts.length - 1];

		if (script) {
			options.stealURL = script.src;
			// Split on question mark to get query

			each(script.attributes, function(attr){
				var optionName =
					camelize( attr.nodeName.indexOf("data-") === 0 ?
						attr.nodeName.replace("data-","") :
						attr.nodeName );
				options[optionName] = (attr.value === "") ? true : attr.value;
			});

			var source = script.innerHTML.substr(1);
			if(/\S/.test(source)){
				options.mainSource = source;
			}
		}

		return options;
	};

[...]

    function ready() {
      var scripts = document.getElementsByTagName('script');
      for (var i = 0; i < scripts.length; i++) {
        var script = scripts[i];
        if (script.type == 'module') {
          var source = script.innerHTML.substr(1);
          // It is important to reference the global System, rather than the one
          // in our closure. We want to ensure that downstream users/libraries
          // can override System w/ custom behavior.
          __global.System.module(source)['catch'](function(err) { setTimeout(function() { throw err; }); });
        }
      }
    }

The old version didn't contain especially the following line:

    var source = script.innerHTML.substr(1);

Any special reason why 1 is used as start index? Looks wrong to me.

**Comment by matthewp** [comment]
The difference is that we now execute the contents of the script tag as a module. What is the reason for embedding CDATA there?

**Comment by matthewp** [comment]
Related: https://github.com/stealjs/steal/issues/699

**Comment by tschoening** [comment]
I use a server side Java framework which produces short closed tags on empty content by default, something like the following:

    <script ... />

The content chosen is a workaround for that, because it's formally correct XML, JS and some content for the framework.

Execution as a module is anyway not the problem in my case, the logic in `ready` is not triggered in the debugger, because my script has another type. the problem is only that you remove the first character.

**Comment by matthewp** [comment]
Are you sure that this is correct? The code you referenced should only be happening of the script's type === 'module', and it doesn't appear yours is.

**Comment by tschoening** [comment]
var getScriptOptions = function () [...]

This is called and uses substr(1) as well, I just wanted to mention both, in my mind, wrong places if I already found them.

**Comment by matthewp** [comment]
Ah, ok, @justinbmeyer have any insight as to why this does `.substr(1)` ? https://github.com/stealjs/steal/commit/4d7b597892dd5b04cc2a89e24179ecffa22a63c4#diff-7a9076d6d94e62c13d641aa71f19ae8eR517

**Comment by justinbmeyer** [comment]
@matthewp possibly to miss the first return character?  I don't know why that would be important.

**Comment by matthewp** [comment]
Ok, then we can just create a test like [this one](https://github.com/stealjs/steal/blob/master/test/basics/inline_code.html) remove the first return.  Will see if anyone wants to take this one, should be fairly easy.

**Comment by tschoening** [comment]
Just to mention, because I'm one of those rare Windows users: Even if it was to remove a first newline, simply removing one character is wrong, because the file could use \r\n.

**Comment by matthewp** [comment]
Right, no characters should be removed at all.

**Comment by matthewp** [comment]
This is fixed in 0.16.12. Thanks for reporting!
