### ISSUE TITLE
Move inner steal script module functionality to a script type

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#699]
This is an example of a bug caused by us doing this: https://github.com/stealjs/steal/issues/698

Instead of:

```html
<script src="steal.js">
  import foo from "bar";
</script>
```

Which causes the above bug, we could instead do:

```html
<script src="steal.js"></script>

<script type="text/steal-module">
  import foo from "bar";
</script>
```

**Comment by matthewp** [comment]
We should leave in the inner-script functionality for backwards-compat, but also add `type="text/steal-module"`

**Comment by matthewp** [comment]
Wait for `appDeferred` to complete: https://github.com/stealjs/steal/blob/b15388eb57d2bb35924f33f1f10c0deeeb287c3e/src/startup.js#L121

Then looks for scripts `document.getElementsByTagName('script')` that have this type attribute and do `System.module(script.innerHTML);` probably.

Also, we should rename all of these deferred variables, they are actually Promises, not deferreds.

**Comment by pYr0x** [comment]
close #752
