### ISSUE TITLE
Include the conditional plugin

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#702]
Bring it into core.

**Comment by pYr0x** [comment]
Why merge that plugin into core? I like that as a separate plugin....

**Comment by matthewp** [comment]
It's certainly up for debate. Perhaps it should be converted to the new plugins API when that is released... hm.

**Comment by pYr0x** [comment]
Yep I like that.. I am curious about the new plugin api

**Comment by matthewp** [comment]
Going to defer this to 1.1.0, likely will become a plugin.

**Comment by matthewp** [comment]
It's not going to be in core.
