### ISSUE TITLE
Remove script type=module "polyfill"

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#704]
Since the real thing is [landing in browsers](https://blogs.windows.com/msedgedev/2016/05/17/es6-modules-and-beyond/) we shouldn't mess with it. We're doing the wrong thing currently. We should do https://github.com/stealjs/steal/issues/699 instead.

**Comment by pYr0x** [comment]
how can i going to start at this issue?

**Comment by matthewp** [comment]
Yeah, for this one the polyfill part is in https://github.com/stealjs/es6-module-loader, just remove it (and tests if they exist).  I'll comment on #699 on what to do.

**Comment by matthewp** [comment]
Note that for https://github.com/stealjs/es6-module-loader we use the "base" branch, not "master". This is for historical fork reasons.

**Comment by matthewp** [comment]
Closed by #729, in major.
