### ISSUE TITLE
Answering Questions During Setup- Progressive Load

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#705]
**There Are a Set of Questions Given During Installation Not Mentioned in the Instructions**

**Environment:**
Ubuntu 16.04 LTS
Firefox

**Explanation:**
At the [Setup](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Setup) stage of the Progressive Loading guide, the user is instructed to run `npm init`. After they do this, the console poses a set of questions.  The instructions do not mention the questions:

![screenshot1_progressive_setup](https://cloud.githubusercontent.com/assets/18269875/15373763/fc2b4ea2-1cfb-11e6-98e1-df7bb5deb53b.png)

I understand that most developers will know to hit enter to default-answer the questions, but I suggest that the instructions let the user know to hit enter to answer the questions. The reason for this is that this is the way it is done throughout the donejs Quick Guide and the donejs In Depth Guide. I think it would be good to maintain consistency across our guides:

**As seen at**  [donejs Quick Guide- Generate the Application](https://donejs.com/Guide.html#section=section_Generatetheapplication)

![donejs_questions](https://cloud.githubusercontent.com/assets/18269875/15373879/823b2710-1cfc-11e6-99d0-090cab9a4f52.png)

**As seen at** [donejs Quick Guide- Generate Message Model](https://donejs.com/Guide.html#section=section_GenerateMessagemodel)

![donejs_questions2](https://cloud.githubusercontent.com/assets/18269875/15373963/e83cd59a-1cfc-11e6-9934-1348130c4a43.png)

**Comment by pYr0x** [comment]
@starlap I think you miss understand something. 
This is the stealjs repo. Your webstorm post is a 'npm init'.
The guide you posted is from donejs. Donejs has a app generator that will ask you the questions that you can find in the guide

**Comment by starlap** [comment]
Hi @pYr0x Thanks for checking in on this. I guess my original bug needed a bit more context. I've updated it. It actually does apply to the Steal project.

**Comment by matthewp** [comment]
@pYr0x She has gone through the progressive loading guide for us and given it a sanity check for things like clarity and consistency (and that it works).

**Comment by pYr0x** [comment]
@starlap ok.. now i understand.
we can add a simple paragraph like like donejs did.

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal-tools/pull/536
