### ISSUE TITLE
Difficulty in Using the Instructions in the Boxes in Progressive Load

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#706]
**Difficulty in Using the Instructions in the Boxes**

**Environment:**
Ubuntu 16.04 LTS
Firefox

**Explanation:**
Occasionally, I had issues with following the instructions in the highlighted boxes.  Many of these issues may not come up for users who are developers but I will still list them, in case they are helpful.

**Issue 1**
1.) **Go to** [app.js](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_app_js)
This is the first time that the guide is instructing the user in how to change the script.  I would suggest letting the user know that the area that is highlighted in red, indicates the script that is to be added/changed. This instruction is given in the donejs guides, and I suggest doing it, here, for the sake of consistency across our tools:

**Stealjs Instructions**
![highlighted_instructions1](https://cloud.githubusercontent.com/assets/18269875/15374767/b33e08e2-1d00-11e6-814f-24cd8e27c82e.png)

**vs Donejs Instructions**
![donejs_highlighted_instructions](https://cloud.githubusercontent.com/assets/18269875/15374854/274440a8-1d01-11e6-96de-72bb37710e0d.png)

**Issue 2**
1.)  **Go to** [package.json](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_package_json)
I broke my package.json by copying and pasting the contents of the entire box into my console.  Again, a developer would probably know not to copy the "..." lines, but I didn't.  I would suggest just removing them:

![packagejson_etc_lines](https://cloud.githubusercontent.com/assets/18269875/15375118/5a0f4b62-1d02-11e6-93c4-45f41d570372.png)

**Issue 3**
1.)  **Go to** [See It Live](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Seeitlive)
The red highlighted script is confusing.  The only script that needs to be added to the console is `env="production"></script>`

![seeitlive_script](https://cloud.githubusercontent.com/assets/18269875/15375382/a40488c6-1d03-11e6-9689-1532727c3753.png)

**Comment by matthewp** [comment]
1) will be dealt with when we do https://github.com/stealjs/steal/issues/891
2) I'll omit the unnecessary parts.

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal-tools/pull/536
