### ISSUE TITLE
Text Error- Progressive Load

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#708]
**Text Error in Progressive Load Guide**

**Explanation:**
1.)  Go to [Create Your Modules]( http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Createyourmodules)
2.)  In the "Create site/app.js.." paragraph, the signup hashtag needs a hashtag:

![signup_hashtag](https://cloud.githubusercontent.com/assets/18269875/15376433/cd5c3d76-1d09-11e6-82db-6c33ce3f411b.png)

**Comment by AryanJ-NYC** [comment]
Looks like this has been updated and can be closed.

**Comment by matthewp** [comment]
Indeed it has, thanks.
