### ISSUE TITLE
Include builtins by default

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#710]
Not sure how to do this.

**Comment by matthewp** [comment]
https://www.npmjs.com/package/steal-builtins

**Comment by pYr0x** [comment]
Where is the GitHub repo for that package?
How to start on this issue?

**Comment by matthewp** [comment]
Repo: https://github.com/stealjs/node-browser-builtins

I'm not sure the best way to implement this.  Probably how you should start is take a look at the example app: https://github.com/stealjs/steal-builtins-example  and familiarize yourself with how it works.

Basically what happens is in system-npm when we crawl the package.jsons, if steal-builtins is installed we will crawl it too: https://github.com/stealjs/system-npm/blob/bc26c76da765ead588fac0c65c0fb1eb1c1e66fb/npm-crawl.js#L41

This will cause it's configuration to be applied, especially these parts: https://github.com/stealjs/node-browser-builtins/blob/master/package.json#L56-L133

So, off the top of my head, I'm not sure what the best way to bring this into core. Maybe you can study the issue and come up with some ideas and we can then discuss them.

**Comment by matthewp** [comment]
@pYr0x I think I'm going to take this one, if it's ok. What I'm thinking is that steal-builtins can become a dependency of steal.js some how.

**Comment by pYr0x** [comment]
It is ok.. I am curious about the implementation

**Comment by matthewp** [comment]
This is in prerelease, https://github.com/stealjs/steal-builtins-example has been updated and is working.
