### ISSUE TITLE
Inconsistency with Behavior of Menu

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#717]
**Inconsistency with the Behavior of the Stealjs Menu Bar**

**Explanation:**
1.)  Go to:  [Stealjs Main](Page]http://stealjs.com/docs/index.html)
 When the user clicks on the links in the menu, the remaining menu links stay visible to the user.
2.)  Click on the "Contributing" link in the menu bar
Note that all of the other menu links disappear.

This seems like inconsistent behavior.  I would suggest keeping the menu stationary when the "Contributing" link is clicked on.

![menu bar](https://cloud.githubusercontent.com/assets/18269875/15622296/2f94e7a4-241c-11e6-93a6-f38fd4c90d27.gif)

**Comment by justinbmeyer** [comment]
This is fine.  It's because "Contributing" has a child (I assume eventually it will have another child?), but the documentation works correctly.  Thanks for pointing it out though!
