### ISSUE TITLE
Doesn't work if missing main

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#727]
https://github.com/stealjs/system-npm/issues/155

**Comment by pYr0x** [comment]
@matthewp do we need tests in steal and steal-tools also?
i added a test in system-npm

**Comment by matthewp** [comment]
No, just at the source of the problem.

**Comment by matthewp** [comment]
Reopening until the new system-npm version is added.

**Comment by matthewp** [comment]
This is in prerelease now.
