### ISSUE TITLE
Support node code that uses Buffer

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#731]
Some code that we want to load uses Node's `Buffer` constructor. There is a browserify shim included with our `steal-builtins` module, but we need to wrap code that needs it.  

Code looks like:

``` js
var zeroBuffer = new Buffer(intSize); zeroBuffer.fill(0);
```

Which we want to wrap like:

``` js
(function(Buffer){
var zeroBuffer = new Buffer(intSize); zeroBuffer.fill(0);
})(require("buffer").Buffer);
```

**Comment by matthewp** [comment]
Moving this to 1.1 as it's actually pretty hard. Looking into how Browserify does it they use a language parser, producing an AST that they traverse to detect globals.  We can't really get away with that in the browser so much rely on regular expressions. We have good support for regex language parsing in our require and import detection, it will exclude comments and the insides of strings. We could use that to better detect `Buffer`.  So I would say steps to make this work is:

1. Move the logic that looks for a regex excluding comments/strings somewhere so that it's reusable. Something like `loader.someFunction(/regex/, source)`.
2. Move out CommonJS / AMD detection, we only want to add this to CommonJS modules.
3. The https://github.com/stealjs/system-npm/tree/buffer3 branch has the start of detection but also needs:
  * shouldn’t detect things like arrayBuffer (should only be if Buffer is by itself)
  * shouldn’t happen if load.metadata.format is set manually to something like global
  * Shouldn’t wrap the Buffer shim itself

**Comment by frank-dspeed** [comment]
And about the Ast remember the build-tools lock file :) it can be a json i don't care but i think lock is more explaining that it is the result of processing and shouldn't get manualy touched ;)



no need for regex i have a more simple effectiv parsing trick :)

```
fileStr = "js code bla bla bla"

Power Array for detecting fileStr.split('new Buffer(') // 

```

**Comment by matthewp** [comment]
What would a lock file have to do with the AST?

**Comment by frank-dspeed** [comment]
@matthewp i think the name makes you confused we put into that lock file all information about how this gets processed we examin it all via steal-tools and build with it a additional file for steal and steal tools where we put in our processing results.

**Comment by matthewp** [comment]
@frank-dspeed I reopened your lock file issue, let's discuss your idea there.

**Comment by alexisvincent** [comment]
@matthewp just noticed this issue. I noticed jspm-nodelibs-buffer has a seemingly simple fix. Not sure if it will solve your issue but might be worth just checking it out. :)

**Comment by matthewp** [comment]
Thanks!
