### ISSUE TITLE
Consolidate core projects

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#746]
_Note_: this won't make 1.0, but can happen any time thereafter.

We have a lot of projects that are only used to build Steal. These are the "system-" extensions. For historical reasons they were developed as separate projects meant to be used with SystemJS, but since our APIs have diverged that's no longer possible. These are:
- steal-es6-module-loader
- steal-systemjs
- system-trace
- system-json
- steal-env

Then we also have some "core plugins" that could be in stealjs/steal:
- system-npm
- system-bower

Consolidating these modules into stealjs/steal would make development much easier. The problem will be bringing all of their tests in.  We really want:
- To be able to develop each extension in isolation.
- Have a test page just for that extension that can be ran in isolation.

To that end I propose we use the modlet pattern like we do in a lot of DoneJS projects.  It could look like this (I think):

```
src/
  json/
    json.js
    json_test.js
    test.html
    json.md
  trace/
    trace.js
    trace_test.js
    test.html
    trace.md
ext/
  npm/
    npm.js
    npm-extension.js
    // other npm-*.js files here
    npm_test.js
    test.html
```

In the above structure `src/` contains all of the extensions (everything that is built into steal.js) and `ext/` contains plugins (things that are dynamically loaded such as the npm plugin).

**Comment by matthewp** [comment]
cc @pYr0x, I know you've felt the pain of our currently structure.

**Comment by justinbmeyer** [comment]
I'm sorta wary of doing this.  We are doing the opposite in canjs and documentjs right now.  Keeping things isolated is good. It enforces logical separation of concerns, even if it creates a bit of an annoying dev experience.

**Comment by matthewp** [comment]
In this case all of the core components are built into a single file.  They are not usable in isolation the way can-compute is. A module loader can not be modular because it is the thing that provides modularity in the first place.  Using the modlet pattern in stealjs/steal is how we'll retain good separation of concerns; the json extension will still have it's own tests, it's own test page, etc.

**Comment by justinbmeyer** [comment]
A module loader not being modular is a decent argument, but yet it is already modular.  `npm` is already an extension.  Maybe `layered` is the right term then.  There is a nice layering.

ES6ML, System, Steal are already layered.  We were examples of using them in isolation and adding our own behavior.

**Comment by matthewp** [comment]
What is nice about the layering? steal.js has a IsWorker variabled defined [three](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L2548) [different](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L4870) [times](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L5076).  The [CommonJS](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L4028), [AMD](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L4145), and  [trace](https://github.com/stealjs/steal/blob/6cca9b3f7b567a02cecf8ae86f3bccc55a789c5d/steal.js#L5505) extensions all have duplicate code to search for a regular expression while ignoring code comments and strings.  The system-npm plugin depends [on a function](https://github.com/stealjs/system-npm/blob/master/npm-utils.js#L78) defined in steal.js. So to develop this I had to make a change in Steal, publish, update system-npm's Steal, make the change in system-npm, publish, update Steal again with new system-npm.

These projects aren't neatly layered with their own functionality.  Either they have duplicate code or they depend on some global functions that is defined in in another project.

**Comment by matthewp** [comment]
If we bring everything into core we can more easily do things like move normalizeURI into it's own module, and have extensions that depend on it define that dependency some how (code comments or something like that), and then use steal-tools to build Steal itself, building a dependency graph and then wrapping everything correctly in some custom export format.  This would give us the ability to create that "build your own Steal" thing that we've talked about forever.

**Comment by justinbmeyer** [comment]
> depend on some global functions that is defined in in another project.

That doesn't mean they aren't layered.  can-compute is layered ontop of can-util.

> This would give us the ability to create that "build your own Steal" thing that we've talked about forever.

This isn't possible now?  Couldn't `normalizeURI` be it's own project?

**Comment by pYr0x** [comment]
I agree with @matthewp maintaining steal is now horrible. 
I think that moving core modules into one repo is good. If in the future steal have the plugin feature, plugins we have the modularity again. And they are really independent and can maintained seperated

**Comment by matthewp** [comment]
> This isn't possible now? Couldn't normalizeURI be it's own project?

No, because then system-trace couldn't use it.  It would have to duplicate the code.

**Comment by justinbmeyer** [comment]
@matthewp I don't understand why that is.  Maybe we can talk about it more later.

@pYr0x / @matthewp are you considering moving everything into core?  I think things like less / etc should be moved out.  

> So to develop this I had to make a change in Steal, publish, update system-npm's Steal, make the change in system-npm, publish, update Steal again with new system-npm.

yeah, I think the cycle here is the "big" issue.  I wonder if there's a better way to structure things so that is avoided.

**Comment by pYr0x** [comment]
@justinbmeyer no we wont add all into core.
as @matthewp described we want to add

- steal-es6-module-loader
- steal-systemjs
- system-trace
- system-json
- steal-env
- system-npm
- system-bower

all the stuff that will load javscript modules. for less and sass it would be good to have that as a plugin (if matthew finished the plugin API)

as @matthewp also mentions, it would be great to build steal with steal-tools. the cools thing would be to build your own steal with only support for NPM and remove the AMD loader

**Comment by matthewp** [comment]
>  I don't understand why that is. Maybe we can talk about it more later.

Because in order to import things you have to have a module loader, and Steal doesn't have the benefit of a module loader loading its code.  Steal has to rely on globals and closures.

**Comment by matthewp** [comment]
@pYr0x 

> all the stuff that will load javscript modules. for less and sass it would be good to have that as a plugin (if matthew finished the plugin API)

The new plugin API is more for "advanced" types of plugins (stuff we call *extensions* today), less can still use the existing plugin API fine.  it's not going to be removed.

**Comment by m-mujica** [comment]
- [ ] steal-es6-module-loader (in progress)
- [x] steal-systemjs (open PR)
- [x] system-trace (done!)
- [x] system-json
- [x] steal-env
- [ ] system-npm
- [ ] system-bower

**Comment by m-mujica** [comment]
and https://github.com/stealjs/steal/pull/1129! 

I think this one can be closed now.
