### ISSUE TITLE
Document how to load scripts from CDN

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#747]
For loading scripts from a CDN only in production, use envs config:

```
"system": {
  "envs": {
    "window-production": {
      "paths": {
        "grecaptcha": "https://www.google.com/recaptcha/api.js"
      }
    }
  }
},
"paths": {
   "grecaptcha": "grecaptcha.js"
}
```

For loading scripts from a CDN all the time, add the script with a `<script>` tag, and set it as instantiated:

```
<script>
  steal = {
    instantiated: {
      grecaptcha: grecaptcha: { 'default': window.grecaptcha, __useDefault: true }
    }
  };
</script>
```

**Comment by matthewp** [comment]
Thanks!  Good contribution for anyone that needs one...

**Comment by phillipskevin** [comment]
See https://gist.github.com/matthewp/083d9fecf1ebfc98d061218ea85b905f for a working example.

**Comment by phillipskevin** [comment]
For SSR, you also need env configs for `server-development` and `server-production`.
