### ISSUE TITLE
Syntax error parsing package.json should call console.error.

### ISSUE THREAD

**Issue by bmomberger-bitovi** [stealjs/steal#765]
Currently it calls console.log instead.
Here: https://github.com/stealjs/steal/blob/e4068e643a16ba7c325f92f4f7989a5906f0ea51/src/startup.js#L95

and here: https://github.com/stealjs/steal/blob/11fe659b808059c307453d219870de58e7ff8c34/main.js#L1163

and here:
https://github.com/stealjs/steal/blob/11fe659b808059c307453d219870de58e7ff8c34/steal.js#L6214

This is a pretty egregious problem when it shows up and it should show up with more call-to-action (and increment the error count) so devs don't accidentally gloss over it and wonder why things are broken.

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-npm #190](https://github.com/stealjs/steal-npm/issues/190) via [**ZenHub**](https://www.zenhub.com/)
