### ISSUE TITLE
link broken

### ISSUE THREAD

**Issue by justinbmeyer** [stealjs/steal#767]
![stealjs_-_why_stealjs](https://cloud.githubusercontent.com/assets/78602/16358561/e7b28276-3adb-11e6-9117-060fa6962e15.png)

A production loader an optimizer

**Comment by leoj3n** [comment]
The anchor in the markdown file is `#build-optimization`.

On the site it is still linking to `#build-optimization` yet the actual ID of the anchor is `#section_BuildOptimization`.

Must be a problem with DocumentJS.

**Comment by leoj3n** [comment]
Here's the culprit for the adding of `section_` to the ID:

https://github.com/bitovi/documentjs/blob/6978b85952f27bcbd7749a15198570a8e92f081d/site/default/static/content_list.js#L35

I don't think anchor'd links in the markdown are accounted for. They need to be parsed and transformed to match for example the link list generation:

https://github.com/bitovi/documentjs/blob/6978b85952f27bcbd7749a15198570a8e92f081d/site/default/static/content_list.js#L7
