### ISSUE TITLE
Add ability to seamlessly transpile non-es6 formatted modules

### ISSUE THREAD

**Issue by isadovskiy** [stealjs/steal#768]
We have modules in CJS format contained ES6 statements (arrow functions, etc). These are library modules, which could be used both with NodeJS and inside the browser (via Steal). I don't see how it possible to transpile them while loading into browser in dev mode or building with StealTools. 

Please point me to an option if such exists. If not, probably mixed module formats should be supported (like "format": "es6+cjs"), which tells the steal to eanspile the module first.

**Comment by matthewp** [comment]
Yeah, so the issue, as you pointed out, is that Steal only transpiles modules with import/export statements. The plan is to release #671 which will allow creating more robust plugins. From there I hope to create a babel plugin that allows you to set options like "transpile everything" or "transpile everything, except what's in node_modules", etc.

**Comment by isadovskiy** [comment]
Thanks for letting me know, @matthewp. Any idea when in could be available (roughly)?

**Comment by matthewp** [comment]
I would say ~1 month before a beta-ish version is ready.

**Comment by isadovskiy** [comment]
I see. Should I closwe this issue then?

**Comment by matthewp** [comment]
No, need the reminder to create this plugin.

**Comment by matthewp** [comment]
The plugins issue has gone cold for a variety of issues (I will update that issue with explanation). However, we are working on improving our Babel integration in #1040 so I think we can provide a way to do this.

I can see a couple of ways of doing this, neither of which feel great. Adding here for discussion.

# transpileFiles

This is a new configuration object that lets you optionally transpile certain files.

```json
{
  "steal": {
    "transpileFiles": "*.js"
  }
}
```

Then a translate hook looks for `loader.transpileFiles` and if the `load.address` is a match, runs the transpiler.

# plugins

Another option is to utilize plugins. We could have a "steal-babel" plugin that adds the translate hook.

However, how would it add the translate hook? I think it would have to be done in configDependencies. However configDependencies currently doesn't run on dependency packages. And it would likely break things badly if we changed that.

An option could be for a new type of config that is like configDependencies but runs on dependency packages.

**Comment by matthewp** [comment]
For a possible path towards the "plugins" API from above, see [this comment](https://github.com/stealjs/steal/issues/671#issuecomment-285097143).

**Comment by matthewp** [comment]
I have a firmer proposal on this now: https://github.com/stealjs/steal/issues/1276
