### ISSUE TITLE
require('..') does not resolve to require('../index.js')

### ISSUE THREAD

**Issue by akagomez** [stealjs/steal#770]
I have  a project that depends on a package that imports a file using `require('..')`: https://github.com/jonschlinkert/markdown-toc/blob/master/lib/insert.js#L3

When I import that package errors are thrown: 

![](https://i.imgur.com/qIjlDXc.png)

If I rewrite the import to `require('../index.js')` the package is imported correctly.

**Comment by matthewp** [comment]
Thanks, I think we handle `../` but maybe not `..`, should be an easy fix, will take a look.

**Comment by matthewp** [comment]
Fixed in Steal 0.16.22
