### ISSUE TITLE
Process module missing version

### ISSUE THREAD

**Issue by joe-crick** [stealjs/steal#774]
Need to have version information added to the process module. See attached for details.

<img width="379" alt="screen shot 2016-07-01 at 1 47 16 pm" src="https://cloud.githubusercontent.com/assets/5924684/16534136/63680cdc-3f92-11e6-921b-055d4685322f.png">

**Comment by pYr0x** [comment]
Where are you? Where is this code called? In steal we only have a fake process by steal bulitins....

Need more info...

**Comment by matthewp** [comment]
@pYr0x the non plug in has a tiny one too, browserify just makes process.version be an empty string so we should do the same.

**Comment by pYr0x** [comment]
> the non plug in has a tiny one too

???

**Comment by matthewp** [comment]
Haha, was typing on my phone.  the npm plugin has `process`, a small version defined here: https://github.com/stealjs/system-npm/blob/master/npm-load.js#L106

just add `version: ''` I say.

**Comment by matthewp** [comment]
Published as 0.16.23
