### ISSUE TITLE
Doesn't append `index.js` when `main` is a directory

### ISSUE THREAD

**Issue by stucox** [stealjs/steal#783]
I came across this when trying to import the [history](https://github.com/ReactTraining/history) NPM module:

```js
// My code
import history from 'history';
```
Gave me this error:
```
GET http://localhost:8000/node_modules/history/lib.js 404 (File not found)
```

Looks like this is because [history's package.json](https://github.com/ReactTraining/history/blob/master/package.json#L8) declares `"main": "lib"` — npm would resolve this to `lib/index.js`, but SystemJS assumes it meant `lib.js`.

I fixed this in my project with a simple path config:

```json
  "system": {
    "npmAlgorithm": "flat",
    "paths": {
      "history": "node_modules/history/lib/index.js",
      "history/*": "node_modules/history/lib/*.js"
    }
  },
```

But thought I should report it in case this is something StealJS could/should handle seamlessly.

**Comment by matthewp** [comment]
Thanks, will take a look.

**Comment by matthewp** [comment]
@stucox Steal can't "know" that lib is a folder, what it does is assume it's a file, then if that files, retries with lib/index.js. Does it not do this now? there's no way avoid the initial 404, but it should retrieve the right module on a retry.

**Comment by matthewp** [comment]
I'm going to assume that it did load on a retry. Let me know if not.

**Comment by stucox** [comment]
Sorry, I didn’t get the chance to try again. I’m happy with your explanation + the workaround though (and you’re probably right that it would load anyway).
