### ISSUE TITLE
Inline Javascript - Ambiguous Error Message 

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal#794]
If I load my steal app without having a main, and instead use inline code to load the app, and an error occurs, the error message is very ambiguous. In some cases this method is beneficial because I can easily pass parameters from a python or php template to the javascript app. 

For example: 

```html
  <script src="/static_apps/crud/node_modules/steal/steal.js">
    import { AppViewModel } from 'app/crud';
    import qs from 'query-string';
    //place app loading logic here
    //this uses the query parameter http://www.example.com?config=config/myconfig
    let config = qs.parse(window.location.search).config || 'config/default/';
    System.import(config).then(module => {
      let app = new AppViewModel(module.config);
      app.startup('#app');
    });
  </script>
```

I ended up getting an error message like this: 
```
steal.js:140 Potentially unhandled rejection [3] Error loading "can-geo@0.1.0#ol-map/LayerFactory" at http://myserver/static_apps/crud/node_modules/can-geo/ol-map/LayerFactory.js
Error loading "can-geo@0.1.0#ol-map/LayerFactory" from "config/utilities/views/Workorder" at http://myserver/static_apps/crud/config/utilities/views/Workorder.js
undefined (WARNING: non-Error used)
```

There probably is something wrong with my app because the error message switches sometimes to a different module, and it doesn't occur consistently. But finding the source of the problem is very difficult without a more detailed error message.

**Comment by matthewp** [comment]
Yeah, I agree, I think we can provide special error messages for the inline modules.

**Comment by pYr0x** [comment]
@matthewp how can we do that? I can will make a PR

**Comment by matthewp** [comment]
@pYr0x The promise is created here: https://github.com/stealjs/steal/blob/master/src/startup.js#L118

So we could catch the error case and add better error messaging, something like "There was an error in the inline module" or something.

**Comment by pYr0x** [comment]
sorry i dont get it.
the problem is, that he loads a module with `System.import(config)` dynamic and we cant catch the error on this dynamic import in the inline module. or missed i something?

**Comment by matthewp** [comment]
Oh sorry, I didn't see that the error happened within the System.import(). Yeah, in that case you need to catch the error yourself.
