### ISSUE TITLE
Live reload doesn't work for async can-import two levels deep.

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#801]
In my index.stache I have the following:

``` html
<can-import from="mma/apps/dashboard/">
  {{#if isPending}}
    Loading...
  {{else}}
    <dashboard-app></dashboard-app>
  {{/if}}
</can-import>
```

In dashboard.stache I have the following:

``` html
<can-import from="mma/apps/dashboard/account">
  {{#if isPending}}
    Loading...
  {{else}}
    <dash-account></dash-account>
  {{/if}}
</can-import>
```

In account.stache I have the following:

``` html
<p>This is a test</p>
```

Making changes to account.stache will only update the page through live reload once, after that no updates will occur until after a full page reload.

If I change dashboard.stache to this, all changes to the account.stache file will immediately update through live-reload:

``` html
<can-import from="mma/apps/dashboard/account" />
<dash-account></dash-account>
```

I've tested this with the current DoneJS as well as the Can3 version of DoneJS.

**Comment by marshallswain** [comment]
Try manually making the inner one a bundle by adding it to the system.bundle array.

**Comment by matthewp** [comment]
@marshallswain Did this work when you added the System.bundle manually? the auto bundle discovery is a feature of steal-stache so if this works when adding manually the issue should be moved here: https://github.com/canjs/steal-stache

**Comment by marshallswain** [comment]
I'll try this out in a bit.  Thanks.

**Comment by matthewp** [comment]
Where you able to take a look again?

**Comment by matthewp** [comment]
Going to close, will reopen if you get a chance to try again.
