### ISSUE TITLE
steal.import() also loads "main" script

### ISSUE THREAD

**Issue by stucox** [stealjs/steal#802]
In a Node env, loading Steal & importing a script also imports the _main_ script (`"main"` property in package.json if defined, otherwise attempts to load `./index.js`)

```js
// start.js
const steal = require('steal');
steal.import('src/app');
```
```sh
$ node start.js
Potentially unhandled rejection [4] Error: Error loading "index" at file:/Users/stuartcox/code/tmp/index.js
ENOENT: no such file or directory, open '<cwd>/index.js'
    at Error (native)
```

On #800 @matthewp said this should be considered a bug: presumably `steal.import('src/app')` should just load `./src/app.js` (and its dependencies).

**Comment by matthewp** [comment]
Closed by #885
