### ISSUE TITLE
Steal should ignore bundle inside of node_modules package.json

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal#812]
If I have an app that uses other steal built or canjs projects as node_modules dependencies the issue arises where a child package can replace the top levels steal/system configuration, or at least that is what *i think* is happening.

If I have a project directory like this:
```
app/
        node_modules/
                module1/
                package.json
        package.json
```

The `package.json`  in `app/` might define a system.bundle property. 
Similarly, the package.json in module1 might define a system.bundle property also.

In this case, when steal-tools is run on the app directory, the bundles defined in the module1 package will be bundled, while bundles defined in app's package.json will not. *Maybe* module1 shouldn't have a system property at all, but if it does, this problem seems to arise.

**Comment by matthewp** [comment]
Thanks, I think the problem here is that we should ignore `bundle` in config inside node_modules

**Comment by roemhildtg** [comment]
Agreed. =)

**Comment by matthewp** [comment]
Fixed in master, will release a patch today. Thanks for the report.
