### ISSUE TITLE
Packages not installed in top level package aren't accessible in production build

### ISSUE THREAD

**Issue by roemhildtg** [stealjs/steal#816]
I'm encountering an issue when moving to steal.production. Running on windows, with `steal@beta` and `steal-tools@beta`

I have a node dependency package, which has another dependency on [`date-selector`](https://www.npmjs.com/package/date-selector). The file is being imported using the es6 syntax:
```
import dateSelector from 'date-selector';
```
During development, this file is imported correctly (`crud/node_modules/date-selectorand when it is built, the log shows that it is inserted into a bundle correctly along with its dependencies on `underscore` and `moment`.

During production though, steal is requesting `date-selector` from `

This is also happening with the following other files: 
  - `can-set.js` - a sub dependency imports this like: `import set from 'can-set';`
  - `when/es6-shim/Promise.js` - Imported by can-connect I think
  - `date-selector/less/datepicker.less` - imported like `import 'date-selector/less/datepicker.less!';`
 
This is using the default node_modules/steal/steal.production.js without bundling assets: 

```javascript
//build.js
var stealTools = require("steal-tools");
var path = require("path");

stealTools.build({
    config: path.join(__dirname,"package.json!npm")
},{
    // bundleSteal: true,
    // bundleAssets: true,
    // sourceMaps: true
});
```

![image](https://cloud.githubusercontent.com/assets/5471079/17258617/5c924d6c-558d-11e6-994b-8ac7ce3adfdb.png)

**Comment by matthewp** [comment]
Can you share what the package is that depends on date-selector? Otherwise I can't easily debug what is going on.

**Comment by roemhildtg** [comment]
Yes sir, I don't have it on npm yet but here's the repo. https://github.com/roemhildtg/can-crud

**Comment by matthewp** [comment]
Thanks, i'm actually getting an error just building, just requiring can-crud. Investigating that first.

**Comment by roemhildtg** [comment]
Interesting, I'm not having trouble building any more.. what is the error message? I have it set up like this in package.json: 
```
  "dependencies": {
    "bootstrap": "^3.3.7",
    "can": "^2.3.x",
    "can-connect": "^0.5.x",
    "can-crud": "git+https://github.com/roemhildtg/can-crud.git"
......
```

**Comment by pYr0x** [comment]
So we can close this?

**Comment by roemhildtg** [comment]
Well I'm not getting build errors, the problem is still occurring.

**Comment by pYr0x** [comment]
can you provide a simple app (accessible through github) that demostrate this issue, so we can solve it?

**Comment by roemhildtg** [comment]
Okay, I tried creating a simple example, but I'm unable reproduce the issue. The original problem consistently occurs in https://github.com/roemhildtg/can-crud-app but it must be something I'm doing, not an issue with steal.
