### ISSUE TITLE
dest option doesn’t seem to work with eachModule

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#831]
Steps to reproduce:
1. `git clone https://github.com/chasenlehara/steal-each-module-dest-function.git`
2. `cd steal-each-module-dest-function`
3. `npm install`
4. `donejs build`

Expected results: build succeeds with no errors and produces two built files, one for each module

Actual results: build fails with error: `Potentially unhandled rejection [1] TypeError: Path must be a string. Received [Function]`

Additional notes: if you comment out the `dest` config in `build.js`, the build succeeds but only produces one file at `dist/global/steal-each-module-dest-function.js` with the second module

**Comment by chasenlehara** [comment]
I’m hoping this is just user error and I’m not configuring things correctly, but [this build code](https://github.com/chasenlehara/steal-each-module-dest-function/blob/350281e7b70c89370072cfb29f34d486a1a82744/build.js) looks correct to me according to [the docs](https://stealjs.com/docs/steal-tools.export.output.html#section_dest).

**Comment by matthewp** [comment]
Can you file this against steal-tools? The problem is there. I'll update the docs with a better example when I fix this. Thanks!

**Comment by chasenlehara** [comment]
Closing in favor of https://github.com/stealjs/steal-tools/issues/513
