### ISSUE TITLE
Module name can not be found in graph

### ISSUE THREAD

**Issue by cherifGsoul** [stealjs/steal#833]
Let's assume I have a DoneJS ```foo``` plugin that contains modules in like ```foo/login/login``` I want to make a steal export with the following config:
```js
outputs: {
    "+standalone": {
       eachModule: ['foo/login/login']
    }
}
```
the build throws an error:
```Potentially unhandled rejection [1] Error: Can't find module 'foo@0.0.1#login/login' in graph.```
I tried with the ```1.0.rc``` I had the same error also

**Comment by matthewp** [comment]
is `foo` your package name?  is it loaded by your `main`?

**Comment by cherifGsoul** [comment]
yes ```foo``` is the package name, but I dont use it, I want to export standalone modules only.

**Comment by matthewp** [comment]
Then you need to include it in your `main` as well: `main: ["foo/login/login"]` in addition to the use of eachModule.

**Comment by matthewp** [comment]
Closing as I think this was resolved.
