### ISSUE TITLE
Missing Text in Progressive Load Guide

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#834]
**Missing Text in Progressive Load Guide**

**Steps:**
1.)  Go to [Create your modules](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Createyourmodules)

2.)  Go to the sentence that says "Next we'll a main module that loads only the bare minimum..."

**Explanation:**
Text is missing in the sentence.

**Example:**

![stealjs_progressiveload_missing_text](https://cloud.githubusercontent.com/assets/18269875/17789618/d5500ba8-6547-11e6-99f0-39448b7499f1.png)

**Comment by marshallswain** [comment]
Haha!   We will the entire module!  And we will the module whether you it or not!

**Comment by matthewp** [comment]
Thanks, fixed.
