### ISSUE TITLE
Changes to package.json are Unclear in Progressive Guide

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#836]
**Changes to package.json are Unclear in Progressive Guide**

**Steps:**
1.) Go to [Create your modules](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Createyourmodules)

2.) Go to the box that asks user to update package.json

**Explanation:**
I found the changes to the script to be confusing.  Would be helpful to have the commands that are to be updated highlighted or have a universal copy and paste.

<img width="945" alt="packagejson_confusion" src="https://cloud.githubusercontent.com/assets/18269875/17826811/57596f2c-6629-11e6-9fc3-cc384d304dd6.png">

**Comment by matthewp** [comment]
Will possibly do this when upgrading to bit-docs, that way we can use the highligher already created for it.

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal/pull/919
