### ISSUE TITLE
**See It Live Script Change Unclear in Progressive Load**

### ISSUE THREAD

**Issue by starlap** [stealjs/steal#837]
**See It Live Script Change Unclear in Progressive Load**

**Steps:**
1.) Go to [See it Live](http://stealjs.com/docs/steal-tools.guides.progressive_loading.html#section_Seeitlive)

**Explanation:**
I found the changes to the `div id`script to be confusing.  Not sure if you're supposed to copy and paste, get rid of everything else, or what.  Would be helpful to have the commands that are to be updated highlighted or have a universal copy and paste.

**Example:**

<img width="987" alt="dev_seeitlive_confusion" src="https://cloud.githubusercontent.com/assets/18269875/17827012/4fb42b3e-662b-11e6-94ba-573155bd1e38.png">

**Comment by matthewp** [comment]
This will also be taken care of along with https://github.com/stealjs/steal/issues/891
