### ISSUE TITLE
Feature Request: VUE Single File Format (*.vue)

### ISSUE THREAD

**Issue by boustanihani** [stealjs/steal#839]
Please support the VUE Single File Components Format (*.vue)

Check: http://vuejs.org/guide/application.html#Single-File-Components) ?

**Comment by pYr0x** [comment]
@boustanihani if you want you can look into https://github.com/donejs/done-component/blob/master/component.js
i dont know what should be the output file after parsing.
if you can provide that for me, i can try to make that loader work

**Comment by boustanihani** [comment]
I'll try but this might take some time because I'm new to this...

**Comment by boustanihani** [comment]
I forgot to mention that Webpack & Rollup also offer this feature:
- https://github.com/vuejs/vue-loader
- https://github.com/znck/rollup-plugin-vue
- https://github.com/thgh/rollup-plugin-vue2

**Comment by matthewp** [comment]
I've moved this to the [RFC repository](https://github.com/stealjs/rfcs/issues/1). Please continue any discussion there. If you'd like to create the plugin yourself, feel free to do so, no permission is needed :)

**Comment by marshallswain** [comment]
@boustanihani I wrote a plugin for `.vue` files: https://www.npmjs.com/package/steal-vue
