### ISSUE TITLE
es6-module-loader should not contain sourcemap

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#842]
as described in https://github.com/stealjs/steal/issues/803#issuecomment-240791361
our `es6-module-loader` (es6-module-loader/dist/es6-module-loader.src.js) should not contain any sourcemap

https://github.com/stealjs/es6-module-loader/blob/abd2a1c114558ce9abcfe78b68a3270f03027076/dist/es6-module-loader.src.js#L1268

**Comment by matthewp** [comment]
Arg, how can we remove that?

**Comment by pYr0x** [comment]
@matthewp lets use in your es6-module-loader the fix npm `when` version `3.7.5`.
the problem with the souremap come with version 3.7.6.

https://github.com/cujojs/when/releases

i think there is not reason why we need 3.7.7

**Comment by matthewp** [comment]
Thanks, I'll take a look and see if this will fix it.

**Comment by matthewp** [comment]
Fixed by #886
