### ISSUE TITLE
Add docs about circular dependencies

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#844]
Please add docs about how Steal handles circular dependencies ([if it does?](https://github.com/stealjs/steal-tools/issues/382)).

I’m requesting this because last week I gave [a talk](http://www.chasenlehara.com/blog/introduction-to-javascript-modules) and briefly covered Steal. I was asked how Steal handles circular dependencies but I [couldn’t find](https://www.google.com/search?client=safari&rls=en&q=site:steal.js+module&ie=UTF-8&oe=UTF-8#q=site:stealjs.com+circular) any docs about it.

**Comment by matthewp** [comment]
Yeah, this is a bit of a confusing subject for sure. The correct answer is "it depends on the module syntax", so that should definitely be explained.

**Comment by matthewp** [comment]
Fixed by https://github.com/stealjs/steal/pull/892
