### ISSUE TITLE
Browserify UMD modules using "self" reference can't be loaded SSR

### ISSUE THREAD

**Issue by Bajix** [stealjs/steal#862]
Browserify standalone builds use a UMD format that uses a "self" reference. This is a frequently occurring issue with anyone that uses this same conversion technique.

Modules built using this conversion technique will have a self reference that breaks during SSR / cordova build.

Not entirely sure what the rationale is for the self reference being made during conversion, but it would be nice if steal were to be able to load it regardless.

Any ideas?

See: https://github.com/nlp-compromise/nlp_compromise

The command:
`browserify + ' ./src/index.js --standalone nlp_compromise -t [ babelify --presets [ es2015 ] ] | derequire >> ./build/nlp_compromise.js`

Snippet of output
```
//export to window or webworker
if ((typeof window === 'undefined' ? 'undefined' : _typeof(window)) === 'object' || typeof DedicatedWorkerGlobalScope === 'function') {
  self.nlp_compromise = nlp;
}
//export to commonjs
if (typeof module !== 'undefined' && module.exports) {
  module.exports = nlp;
}
//export to amd
if (typeof define === 'function' && define.amd) {
  define(nlp);
}
```

**Comment by matthewp** [comment]
So it sounds like the issue is that done-ssr fakes being a window and it tries to set `self.nlp_compromise = nlp;`. Does this sound right?

**Comment by Bajix** [comment]
Exactly

**Comment by matthewp** [comment]
Thanks, moved this over to https://github.com/canjs/can-vdom/issues/5
