### ISSUE TITLE
Trying to use stealjs with bower

### ISSUE THREAD

**Issue by lguzzon** [stealjs/steal#876]
If in bower.json I use "\*" as version
` 
"dependencies": {
        "jquery": "*",
        "steal": "*"
    }
`
then 

> bower install
bower cached        https://github.com/jquery/jquery-dist.git#3.1.1
bower validate      3.1.1 against https://github.com/jquery/jquery-dist.git#*
bower cached        https://github.com/bitovi/steal.git#3.3.0
bower validate      3.3.0 against https://github.com/bitovi/steal.git#*
bower install       jquery#3.1.1
bower install       steal#3.3.0

**steal#3.3.0** WFT is this non working version ...
may be you can you fix it ...
Please

**Comment by matthewp** [comment]
You shouldn't use `*`, but instead use a range on the version you want.  You want `^0.16.0` currently.

**Comment by lguzzon** [comment]
Thanks
