### ISSUE TITLE
Build step breaks app when used with Angular 2 Router

### ISSUE THREAD

**Issue by AryanJ-NYC** [stealjs/steal#894]
build.js
```
'use strict';
let stealTools = require('steal-tools');

stealTools.build({
  config: __dirname + '/package.json!npm',
}, {
  bundleAssets: true
});
```

index.html
```
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap.min.css">
  <link rel="stylesheet" href="node_modules/bootstrap/dist/css/bootstrap-theme.min.css">
  <title>Voting App</title>
  <script src='dist/node_modules/steal/steal.production.js' main='src/main'></script>
  <!-- Polyfill(s) for older browsers -->
  <script src="node_modules/core-js/client/shim.min.js"></script>
  <script src="node_modules/zone.js/dist/zone.js"></script>
  <script src="node_modules/reflect-metadata/Reflect.js"></script>
</head>

<body>
  <my-app>Loading...</my-app>
</body>
</html>
```

app.module.ts:
```
import { BrowserModule } from '@angular/platform-browser';
import { HttpModule } from '@angular/http';
import { NgModule }      from '@angular/core';
import { RouterModule }   from '@angular/router';
import './rxjs-operators';

import { AppComponent }  from './app.component';
import { PollListComponent } from './polls/poll-list/poll-list.component';
import { NavModule } from './shared/nav/nav.module';
import { PollModule } from './polls/poll.module';
import { PollService } from './polls/shared/poll.service';
import { UserService } from './users/shared/user.service';

@NgModule({
  imports:      [
    BrowserModule,
    HttpModule,
    NavModule,
    PollModule,
    RouterModule.forRoot([
      { path: '', component: PollListComponent }
    ])
  ],
  declarations: [ AppComponent ],
  bootstrap:    [ AppComponent ],
  providers:    [ PollService, UserService ]
})

export class AppModule { }
```

I know it's a bunch of code, apologies. Anywho, it is the RouterModule import in app.module.ts that breaks the app on the build step (it runs fine with steal in dev).  I just get the following message:

<img width="1010" alt="screen shot 2016-10-27 at 10 19 04 pm" src="https://cloud.githubusercontent.com/assets/8263430/19795453/82670d6c-9ca9-11e6-9d43-84142d2ce752.png">

steal.production.js:10 Error loading "C" at http://localhost:8080/dist/C.js
Error loading "C" from "src/main" at http://localhost:8080/dist/src/main.js
Not Found: http://localhost:8080/dist/C.js undefined

Rest of my code can be found [here](https://github.com/AryanJ-NYC/voting-app).

**Comment by AryanJ-NYC** [comment]
So, funny story, I changed the `minify` option to `false` in order to paste it here so it'd be easier to see the C.js that is undefined. Turning it off was the solution. I guess it was specifically the minification process that broke the app.

**Comment by matthewp** [comment]
I would try to reduce this down. I can't really help with an app that's using a framework.  You might check `System.bundles` and see if there's a **C** in there.
