### ISSUE TITLE
Possible lingering babel 5 issue in steal 1.0-rc

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#901]
https://github.com/BigAB/react-view-models

```
[BABEL] unknown: Using removed Babel 5 option: base.blacklist - Put the specific transforms you want in the `plugins` option
```

**Comment by matthewp** [comment]
@BigAB I see this problem only when running SSR. done-ssr isn't compatible with Steal 1.0 or Can 3.0 yet. You can switch to 0.16 and the issue goes away, but then you have to add this configuration:

```json
"system" {
  "transpiler": "babel",
  "npmAlgorithm": "flat",
  "babelOptions": {
    "blacklist": []
  }
}
```

Of course this is only for SSR, but since this isn't an app I'm not sure if you really want ssr for this? Maybe you are using it for development though.

**Comment by BigAB** [comment]
So, you're saying just by having `done-serve` (I assume as I don't have `done-ssr`) in my `package.json`, that is somehow messing up the steal-tools build?

What?

Are you sure you want to close this issue?

**Comment by BigAB** [comment]
It turns out taking `done-serve` out doesn't seem to solve anything.

This problem is coming from running `npm run build` on the https://github.com/BigAB/react-view-models project. Where is SSR coming into play there?

**Comment by matthewp** [comment]
I didn't realize this was a build issue.

**Comment by matthewp** [comment]
Issue moved to [stealjs/steal-tools #551](https://github.com/stealjs/steal-tools/issues/551) via [**ZenHub**](https://www.zenhub.com/)
