### ISSUE TITLE
steal-socket to delay connnection

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#905]
This is necessary to be able to mock socket connection with `can-fixture-socket`

See [this gist](https://gist.github.com/ilyavf/c9665a6875d70b68a81ee2aeca4d95df) for details.

**Comment by matthewp** [comment]
Is this a steal-socket.io issue?  If so it should be in its repo.  Or do you need to make changes to steal itself?

**Comment by matthewp** [comment]
I think this is meant for another repo, closing.
