### ISSUE TITLE
Transpile issue with exports

### ISSUE THREAD

**Issue by dylanrtt** [stealjs/steal#911]
Using the latest release candidate (v1.0.0-rc.8), if I export a function in the same statement that I name it (e.g., `export function foo(){}`), that function is moved to the `execute()` method of the register output during transpilation (in dev, haven't tried prod).

```js
function privateBar() {
    return bar();
}

export function bar() {
    return 'bar result';
}

export function foo() {
    return privateBar();
}
```

transpiles to:

```
System.register([], function (_export, _context) {
    function privateBar() {
        return bar();  // bar is not defined
    }

    return {
        setters: [],
        execute: function () {
            function bar() {
                return 'bar result';
            }

            _export('bar', bar);

            function foo() {
                return privateBar();
            }

            _export('foo', foo);
        }
    };
});
```

This creates a problem where the parent function scope does not have access to the functions defined in `execute()`.

It would probably be better to avoid moving function declarations to the `execute()` method so that they are all in the same scope.

**Comment by matthewp** [comment]
Thanks, this is likely a Babel bug. I'll try upgrading our version and see if that resolves it.

**Comment by matthewp** [comment]
Fixed in major, Babel upgrade fixed it.
