### ISSUE TITLE
Problem with loading specific module

### ISSUE THREAD

**Issue by repolevedavaj** [stealjs/steal#916]
I am trying to load the newest version of the [ng2-resource-rest](https://github.com/troyanskiy/ng2-resource-rest) module, but the module throws always an error telling me that it should be loaded as AMD or CommonJS module. Is there any way to tell Steal of which type the module is, or do I have missed something in the configuration?

Thanks in advance for you help.

**Comment by matthewp** [comment]
Yes. In package.json

```json
"system": {
    "meta": {
        "whatever": {
            "format": "cjs"
        }
    }
}
```

Replacing whatever with the module.
