### ISSUE TITLE
Figure out a better design for anchor links

### ISSUE THREAD

**Issue by matthewp** [stealjs/steal#921]
As shown in the below image, there is left padding caused by the anchor links that show up on hover. This looks weird when there is no hover.  You can see an example [here](https://stealjs.github.io/stealjs/docs/).

We should come up with a better design that:

* Keeps the headings lined up with the content.
* Preserves the hover link image behavior.

![screen shot 2016-11-14 at 11 19 24 am](https://cloud.githubusercontent.com/assets/361671/20272604/6d7e5390-aa5c-11e6-9c8a-62469a70257d.png)

**Comment by matthewp** [comment]
Note that this behavior is the same as what GitHub does on its headings. GitHub doesn't have this same problem though, because there is enough padding in the content to fit the link as shown below.

![screen shot 2016-11-14 at 11 23 18 am](https://cloud.githubusercontent.com/assets/361671/20272759/e7156a40-aa5c-11e6-8ea5-7956ee5ba22b.png)

**Comment by blazepollard** [comment]
PR: https://github.com/bit-docs/bit-docs-docjs-theme/pull/17

**Comment by m-mujica** [comment]
I merged and released Blaze's PR, the change should be deployed next time the StealJS website is updated. https://github.com/bit-docs/bit-docs-docjs-theme/releases/tag/v0.3.5
