### ISSUE TITLE
Contact open source projects that use Steal 0.x

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#927]
After Steal 1’s announcement, reach out to open source projects that use an old version of Steal with links to the announcement and upgrade resources.

**Comment by matthewp** [comment]
I hate to be a pain, but do you mind putting this overall Stealjs kind of stuff in stealjs/stealjs?  Trying to consolidate issues that are about both steal and steal-tools there so the other repos can stay specific to their purpose.

**Comment by chasenlehara** [comment]
This issue was moved to stealjs/stealjs#22

**Comment by chasenlehara** [comment]
I thought about it but then I saw the [Migration guide](https://github.com/stealjs/steal/issues/875) here so I thought it’d be ok. Sorry!
