### ISSUE TITLE
StealJS Training

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#928]
From https://github.com/donejs/donejs/issues/713

**Comment by matthewp** [comment]
This has been done, there's slides in Google Drive.

**Comment by chasenlehara** [comment]
Google Drive link: https://drive.google.com/drive/u/0/folders/0Bx-kNqf-wxZeeE5nMmFtcGhGME0

@justinbmeyer, do we just need to update the training material for Steal 1, or did you have something else in mind in https://github.com/donejs/donejs/issues/713?

**Comment by matthewp** [comment]
I updated them to reflect the code changes.

**Comment by chasenlehara** [comment]
Thanks @matthewp; I’ll review it as soon as I can.

**Comment by matthewp** [comment]
This is now v3 in Google Drive.  I gave the training, it works.

**Comment by BigAB** [comment]
@matthewp on slide 40 it still has `system` in the config

**Comment by matthewp** [comment]
Then I'll fix it!

**Comment by matthewp** [comment]
Ok, I double checked and I think that was the only one. Thanks for the catch @BigAB !
