### ISSUE TITLE
steal.done() returns undefined for SSR

### ISSUE THREAD

**Issue by ilyavf** [stealjs/steal#933]
When used within `done-ssr-middleware`:

```js
var ssr = require('done-ssr-middleware');
module.exports = ssr({
  config: __dirname + "/package.json!npm",
  main: "bitcentive/index.stache!done-autorender",
  liveReload: true
});
```
index.stache
```html
<can-import from="bitcentive/test-done" />
```
test-done.js
```js
console.log('!!!!! steal.done() ' + typeof steal.done());
```
Shows `undefined`

**Comment by matthewp** [comment]
Can you recreate it without done-ssr? I can't tell if this is a Steal issue otherwise. You should be able to write an example that is like one of these: https://github.com/stealjs/steal/blob/master/test/node_test.js

That doesn't use done-ssr, just loads a module in Node that uses steal.done()

**Comment by matthewp** [comment]
Also, which version of Steal are you using?

**Comment by ilyavf** [comment]
@matthewp No, I can't reproduce this without SSR.
We are on `0.16.43` but it is also an issue for `1.0.0-rc.11`.

> You should be able to write an example that is like one of these...

Will try.

**Comment by ilyavf** [comment]
@matthewp I can't make a test similar to `node_test.js` for the case.

**Comment by ilyavf** [comment]
For now closing this issue and open one in `done-ssr`: https://github.com/donejs/done-ssr/issues/194
