### ISSUE TITLE
plugins() appends '!function Object() { [native code] }' to loads that end with '.constructor'

### ISSUE THREAD

**Issue by bmomberger-bitovi** [stealjs/steal#938]
To fix this, change https://github.com/stealjs/steal/blob/master/src/system-extension-ext.js#L8 to:

```javascript
		loader.ext = Object.create(null);
```

and https://github.com/stealjs/steal/blob/master/src/config.js#L38 to:

```javascript
	System.ext = Object.create(null);
```

[`Object.create(null)` creates objects with no constructor or proto -- better for dictionaries than `{}`]

**Comment by matthewp** [comment]
I don't follow what the problem is, care to clarify?

**Comment by bmomberger-bitovi** [comment]
It throws an error instead of loading the script, because it gets a bogus extension handler.  Here's a JSBin demonstrating it:  https://jsbin.com/sulekovohi/1/edit?html,output

**Comment by matthewp** [comment]
I'm still not quite following. You are saying that there is a bug in `ext` config, is that right?  That jsbin doesn't use `ext` config though. So maybe you are talking about something else?

**Comment by bmomberger-bitovi** [comment]
That's the point; there's an `ext` property on the system loader whether I configure it or not.  And because it's a plain object, it has a `constructor` property.  So the script whose path ends with `.constructor.js` isn't treated as a plain script by the loader; it's treated as something that needs the nonexistent `.constructor` processor extension.

**Comment by matthewp** [comment]
Ok, makes sense now!
