### ISSUE TITLE
Cryptic error messages when using "ext" instead of "plugins" to load steal-less

### ISSUE THREAD

**Issue by bmomberger-bitovi** [stealjs/steal#945]
Using a steal config like: 

```
{
  "system": {
    "ext" : {
       "css": "steal-css",
       "less: "steal-less"
    }
  }
}
```
results in this:
<img width="1039" alt="screen shot 2016-12-07 at 4 29 47 pm" src="https://cloud.githubusercontent.com/assets/18686722/20989730/680d7a7a-bc9b-11e6-938d-97fa207d025c.png">

The first four console errors are due to steal-less looking for steal-css in its own node_modules folder rather than at the top level (this doesn't happen when using "plugins" to load steal-less)

The last three are bizarre loads that attempt to load the less engine through `#less` and `less` without proper mapping.

This isn't the expected behavior, according to @matthewp , but it also is unhelpful in directing the user to load them as plugins.

**Comment by matthewp** [comment]
@m-mujica First step here is just to create a test project that recreates these errors. I think it can be done by creating the above configuration, but leaving out the "plugins" config.

I think the solution here is better error messages. I'm not sure *how* that should happen. Before proceeding with a fix, let me know what you think could be a good solution here; meaning how can we detect this mistake and give a good error message about it.

**Comment by m-mujica** [comment]
@matthewp could not replicate the error message https://github.com/stealjs/steal-error-messages/tree/master/ext-instead-of-plugins

mind if I close this one? :D
