### ISSUE TITLE
Running a steal-tools build fails when using steal-clone

### ISSUE THREAD

**Issue by phillipskevin** [stealjs/steal#952]
If your "main" (or any other module you're loading) imports `steal-clone`, the build will fail with this error:

```
ERROR: Error loading "steal-clone-build@1.0.0#index" at file:/Users/kevin/dev/temp/steal-clone-build/index.js
definer.call is not a function
ERROR:
Build failed
```

In my example app, the main is just

```js
import clone from 'steal-clone';
```

I am using steal@1.0.0-rc2 and steal-tools@1.0.0-rc2, but this also happens on 0.16.

You can clone [this gist](https://gist.github.com/phillipskevin/d68b02f1e2a92e1abeef83250ba7b1f4) to try it out.

**Comment by matthewp** [comment]
Just need to check here if definer is a function: https://github.com/stealjs/steal/blob/cdf45ec81184b414ee4abc64970170eac2e69e65/src/system-extension-contextual.js#L30  if not return an empty object.

**Comment by matthewp** [comment]
@m-mujica might need to add "steal-clone" here: https://github.com/stealjs/steal-tools/blob/886040c60f6c343c452c3c74446322abf0da4028/lib/graph/make_predefined_plugin_dependencies.js#L3

**Comment by m-mujica** [comment]
@matthewp I tried that but the error happens before steal-tools gets to use that module. 

https://github.com/stealjs/steal/blob/master/src/system-extension-contextual.js#L31

That's the line, when steal is normalising "steal-clone", definer is an empty object. Thoughts?
