### ISSUE TITLE
Help making an svg loader

### ISSUE THREAD

**Issue by marshallswain** [stealjs/steal#966]
Hey @matthewp, would you mind helping me put together an SVG loader.  I want to be able to import an SVG file, turn it into a string and inline it in a template.  I started creating a plugin, but I couldn't figure out how to access the file content.  Which step should I be using?

```js
export function instantiate(load) {
  debugger;
}

export function locate(load) {
  debugger;
}

export function fetch(load) {
  debugger;
}

export function translate(load) {
  load.metadata.format = 'svg';
  debugger;
}
```

**Comment by justinbmeyer** [comment]
Translate. Look at steal-stache as an example. Maybe steal-json if it still exists.

**Comment by pYr0x** [comment]
I would say also say translate is the right place.
Here you can put the source into a img tag and return it.
Matthews wrote a guide 
http://stealjs.com/docs/StealJS.writing-plugins.html

**Comment by matthewp** [comment]
Yeah that's a good example. Let's try and keep non-bugs to the forums though: http://forums.donejs.com/

**Comment by marshallswain** [comment]
Thanks, guys.  I figured out my problem.  I was trying to create a local file called steal-svg and not load the plugin into the package.json.  This was resulting in the `load.source` attribute being undefined.  As soon as i linked a folder into `node_modules` and set it up like other plugins, the `source` was populated.
