### ISSUE TITLE
why system-format-steal.js exits in root folder?

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#974]
why does this file exits in the root folder
https://github.com/stealjs/steal/blob/master/system-format-steal.js

should i not be unter '/src' ?
https://github.com/stealjs/steal/blob/master/Gruntfile.js#L36
https://github.com/stealjs/steal/blob/master/Gruntfile.js#L48

**Comment by matthewp** [comment]
I believe it is dated back to when Steal was meant to play nicely with SystemJS, so the idea was that SystemJS users could use system-format-steal to get the `steal("./foo")` syntax. So at this point that's not needed.

**Comment by pYr0x** [comment]
should i create a PR that removes the grunt task and remove the file from root?

**Comment by matthewp** [comment]
👍 sounds good to me. Make sure the tests aren't still using it, they used to be. But that could be changed to use steal.js instead (if it hasn't already been).
