### ISSUE TITLE
simplify and reorder steal creation

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#975]
today we concat some files into `system-format-steal.js`
https://github.com/stealjs/steal/blob/master/Gruntfile.js#L41-L48

my suggestion is, get rid of system-format-steal.js creation and remove 
- src/system-format-start.js
- src/system-format-end.js

and rename `system-format-steal.js` to `system-extension-steal.js`

**Comment by matthewp** [comment]
Can we combine this issue with #976 ? I think it's really about the same thing.

**Comment by matthewp** [comment]
I believe the reason for the weird ordering is that system-format-start -> system-format-end is all within a common closure like:

```js
// system-format-start
(function(){

// some stuff

// system-format-end
})();
```

It's definitely weird but I think the closure is needed? Anyways, open to a better way for sure.

**Comment by pYr0x** [comment]
i dont know why a IIFE is needed for the steal-extension. because we have other system extensions that work the same way.

i would prefer a refactor the whole `addExtension` stuff.
we have a lot of this code in steal
```
if (typeof System !== "undefined") {
	_SYSTEM_addJSON(System);
}
```
maybe it would be better to create a function called `addStealExtension`
that function can handle all the common stuff like
- is System not undefined
- add the extension to the `loader._extensions`

**Comment by matthewp** [comment]
Sounds good to me:

```js
addStealExtension(function(){
  // Whatever goes here, this is the function that is pushed into loader._extensions
});
```

Also would be good to expose to 3rd part extensions like live-reload:

```js
var steal = require("@steal");

steal.addExtension(function(){
  // extension goes here.
});
```
