### ISSUE TITLE
Improve the error message when steal-less isn’t installed

### ISSUE THREAD

**Issue by chasenlehara** [stealjs/steal#995]
While upgrading [a project](https://github.com/donejs/donejs-number-input) to StealJS 1, I ran my build before installing `steal-less` and got this error:

```
Error: Error loading "donejs-number-input@0.1.1#donejs-number-input.less!less" at <unknown>
Error loading "donejs-number-input@0.1.1#donejs-number-input.less!less" from "donejs-number-input@0.1.1#donejs-number-input" at file:/Library/WebServer/Documents/donejs-number-input/src/donejs-number-input.js
Error loading "less" at file:/Library/WebServer/Documents/donejs-number-input/less.js
ENOENT: no such file or directory, open '/Library/WebServer/Documents/donejs-number-input/less.js'
    at Error (native)
```

For plugins that were previously included in StealJS, it’d be nice if the error messages were more friendly and either:
1) Included a link to [the docs that explain the issue](http://stealjs.com/docs/StealJS.topics.migrating-one.html#css-and-less-plugins).
2) Included the exact instructions in the error.
3) Offered to fix the issue for me (in my case, by installing `steal-less` and updating my `package.json` with the `plugins` configuration).

**Comment by matthewp** [comment]
Could add a default `less` handler here: https://github.com/stealjs/steal/blob/master/src/core.js#L27 that just warns and points at the docs.

**Comment by leoj3n** [comment]
Thank you for making this issue and https://github.com/donejs/donejs-number-input/blob/stealjs-1-upgrade/package.json

Otherwise I think I would have been really stuck with my issue here:

https://github.com/donejs/donejs/issues/852#issuecomment-289191909
