### ISSUE TITLE
Improve the Quick Start Guide

### ISSUE THREAD

**Issue by pYr0x** [stealjs/steal#996]
- [ ] Show adding a CSS file and configuring the plugin.

- [ ]  quickstart guide says `npm install steal steal-tools jquery --save-dev` but it should be 
`npm install steal jquery --save` and `npm install steal-tools --save-dev`

- [ ] use http-server with `no-caching-flag` => `-c-1`

- [ ] update  repo  https://github.com/stealjs/quick-start

**Comment by mikedane** [comment]
Another Issue:
- [ ] package.json editing instructions [here](https://stealjs.com/docs/StealJS.guides.progressive_loading.html#update-packagejson-with-the-right-main) need to be changed. `"main:"` should have the value `"myhub.js"` not `"index.js"`

    `"main": "myhub.js",`

**Comment by michaelzcheng** [comment]
- [ ] Installing justifiedGallery for the demo should use version <=3.6.5, as the latest has changed the location of it's jquery plugin.

**Comment by matthewp** [comment]
@mikedane @michaelzcheng I've updated these things. Thanks for reporting!
