### ISSUE TITLE
require("./folder") doesn't retry loading "folder/index.js"

### ISSUE THREAD

**Issue by nlundquist** [stealjs/steal#997]
I've created an example of this issue at https://github.com/nlundquist/steal-folder-index-test.

When loading the 'faker' npm package, the top level file at faker/index.js is correctly loaded since the index.js is listed as the main in the package.json. However index.js then requires the folder './lib' which is a folder. According to NPM conventions this should load 'faker/lib/index.js'. 

Obviously steal doesn't know that 'faker/lib' is a folder, but after trying to load 'faker/lib.js' and failing, it should attempt to load 'faker/lib/index.js' to see if that works. I believe that's the intent of the first point under "Improve NPM Workflow" on [this StealJS forum post](http://forums.donejs.com/t/stealjs-roadmap-discussion/131): "folder/index convention of NPM modules. That is if we are unable to load folder.js, try folder/index.js. Additionally we should cache the results of these so that there are no 404s on refresh.".

Is that functionality still on the roadmap?

**Comment by matthewp** [comment]
We don't have caching of the result yet, but we do retry with /index.js already. So probably just a bug here, I'll take a look.

**Comment by matthewp** [comment]
Hm, it worked for me. There's a bug in the code though, this `faker.Name.firstName()` should be a lower-case name like `faker.name.firstName()`. If I change that the code works.

If you filter your console to warnings you should see this:

<img width="829" alt="screen shot 2017-01-10 at 8 32 51 am" src="https://cloud.githubusercontent.com/assets/361671/21808033/6a58736e-d70f-11e6-9000-4347170da946.png">

**Comment by nlundquist** [comment]
Ahh I can see that it does retry for /index.js it just does so quite a bit later that I expected to see. Asynchronous nature of loads. Thanks for looking at this.
